### ISSUE TITLE
Mercenary Contract

### ISSUE THREAD

**Issue by admadm123** [dufernst/LegionCore-7.3.5#100]
DONT WORK 
This is the buff obtained upon speaking to a mercenary recruiter and becoming a mercenary for the opposing faction.

The mercenary recruiters can only be seen by the appropriate faction when their queue times are very high (at present this is most often available for Alliance).

The two Horde recruiters are:
[Sergeant Wilson](https://www.wowhead.com/npc=98219/sergeant-wilson) (Battleground Recruiter)
[Kayvon Quinnstar](https://www.wowhead.com/npc=98218/kayvon-quinnstar) (Ashran Recruiter)
The two Alliance recruiters are:
[Nassar](https://www.wowhead.com/npc=98148/nassar) (Battleground Recruiter)
[Valmaun](https://www.wowhead.com/npc=98171/valmaun) (Ashran Recruiter)
Here are some notes about mercenary mode:
The recruiters can be found near the entrance to Ashran.
The recruiter NPCs are ONLY visible when the queue time for your faction is exceptionally high.
Speaking to a recruiter gives you a 30 minute buff - [ Mercenary Contract](https://www.wowhead.com/spell=193475/mercenary-contract) for Horde or [ Mercenary Contract](https://www.wowhead.com/spell=193472/mercenary-contract) for Alliance. While you have this buff, you can queue for non-rated battlegrounds or Ashran as the opposite faction.
Speaking to the Ashran recruiter automatically queues you for Ashran, as well as giving you the [ Mercenary Contract](https://www.wowhead.com/spell=193475/mercenary-contract) buff. Speaking the the Battleground recruiter does not queue you - you need to queue manually.
Mercenaries are indistinguishable from regular Horde/Alliance members, and cannot be identified by other mercenaries or non-mercenary players.
Switching from Horde to Alliance or vice versa via the mercenary system changes your race to a set race on the opposing faction based on your starting race and class. These are listed in the chart below.

**Comment by welder1976** [comment]
add later fix

**Comment by ReyDonovan** [comment]
need detailed test
