### ISSUE TITLE
Database sql files are incompatible with core

### ISSUE THREAD

**Issue by kakukkokkal** [dufernst/LegionCore-7.3.5#106]
If you create and import databases based on the SQL files found in the source tree during worldserver initialization the creation of a lot of prepared statements will fail due to missing columns in table schema.

**Comment by c0per0** [comment]
Now that you have installed the updates that come in the updates folder?, you have updates for all the databases.

**Comment by kakukkokkal** [comment]
Yes, I forgot to mention.

**Comment by c0per0** [comment]
Well, in my case simply installing the database and its corresponding updates has worked for me, in fact I have it mounted on a local server in linux, the only thing that occurs to me is that you delete the databases and put them from again just in case, anyway I doubt very much that with only the information you have given they can help you a lot, you should be more specific not just the message you have posted, with that it can be many things, from just 1 table to all of them.

**Comment by kakukkokkal** [comment]
Yep, I know this bug report as it is is fairly useless if it should work OOTB, was written from memory.
I'll retry this afternoon.

**Comment by dufernst** [comment]
@kakukkokkal as @c0per0 mentioned it should work just fine with all the updates in this repo applied.
Let me know if you manage to get it to work, or if you still have issues.

**Comment by kakukkokkal** [comment]
I couldn't import them cleanly, had to edit the SQL files, and putting the preamble in the auth sql file to the other files.

When I start the server it complains about invalid SQL syntax when creating the prepared statements. 

Sorry, I am usually writing from phone, can't access the exact error messages.

**Comment by XueYingjie1983** [comment]
When I install database with the source in the tree and updates on ubuntu,when I start worldserver,I receive this message:ERROR Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.but I have update all the file.and some other errors exist ,like some item don't exist...etc


here is the some error message:
ERROR Table gossip_menu_option for menu 20350, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20353, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20358, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20359, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20361, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20401, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20402, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20403, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20404, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20405, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20409, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
ERROR Table gossip_menu_option for menu 20410, id 0 has GOSSIP_ICON_SHIPMENT, but handler 28 != GOSSIP_OPTION_GARRISON_SHIPMENT  
INFO  >> Loaded 9085 gossip_menu_option entries in 396 ms
INFO  Loading Vendors...
INFO  >> Loaded 75097 Vendors in 2861 ms
INFO  Loading Donate Vendors...
ERROR [1146] Table 'legion_auth.store_product_locales' doesn't exist
ERROR TRANSFERT ERROR 1146 : query : SELECT `s_p`.`category`, `s_p`.`item`, `s_p_r`.`token`, `s_p`.`enable`, `s_p`.`bonus`, `s_p`.`id`, `s_c`.`type`, `spl`.type, `spl`.`ru`, `spl`.`us`, `spl`.`kr`, `spl`.`fr`, `spl`.`de`, `spl`.`cn`, `spl`.`tw`, `spl`.`es`, `spl`.`mx`,`spl`.`pt`, `spl`.`br`, `spl`.`it`, s_p.faction FROM `store_products` AS s_p JOIN `store_categories` AS s_c ON `s_c`.`id` = `s_p`.`category` JOIN `store_product_realms` AS s_p_r ON `s_p_r`.`product` = `s_p`.`id` LEFT JOIN `store_product_locales` AS spl ON `spl`.`product` = `s_p`.`item` WHERE `s_p`.`enable` = '1' AND `s_p_r`.`realm` = '1' AND `s_p_r`.`enable` = 1  ORDER by `s_p`.`category`;
ERROR Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Comment by zTerragor** [comment]
i have same problem, when worldserver start. problem in characters DB , such as prepared statements will fail due to missing columns in table schema.

**Comment by dufernst** [comment]
Considering it closed due to a lack of activity, the mysql version might have been wrong, version 5.6 should be preferred or otherwise the latest 5.* release.
For versions after 5.6 the following should be considered in the readme:
Disable the NO_ZERO_IN_DATE sql_mode.

**Comment by miaolin1993** [comment]
i use mysql5.6.51，遇到了相同问题，world and hotfix 这两个表，导入sql直接会报错并失败
