### ISSUE TITLE
Unable to get server problem!

### ISSUE THREAD

**Issue by 9cwow** [dufernst/LegionCore-7.3.5#108]
You can't get the role when you exit the role selection page and you can't get the server when you log in. You have to restart the worldserver.exe. Excuse me, how to solve the problem?

**Comment by dufernst** [comment]
What do you mean with "can't get the role" and with "you can't get the server when you log in"?

**Comment by 9cwow** [comment]
It felt like standing in line. It has been stuck in which step to connect to the server!

**Comment by dufernst** [comment]
Then something is wrong with your server configuration, hard to tell what is exactly wrong without more information.
But in general you are probably helped by looking up some information on the TrinityCore wiki.

**Comment by dufernst** [comment]
The defaults are mostly fine, but things like database connection details definitely have to be changed.

**Comment by dufernst** [comment]
closing as resolved, otherwise feel free to open a new issue
