### ISSUE TITLE
Fix quest=40205/respect-for-the-past

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#109]
did not count the condition when clicking on the object https://www.wowhead.com/quest=40205/respect-for-the-past
SmartScript
`INSERT INTO `smart_scripts` VALUES (245241, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 33, 99316, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Kill_Credit');
INSERT INTO `smart_scripts` VALUES (245254, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 33, 99317, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Kill_Credit');
INSERT INTO `smart_scripts` VALUES (245287, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 33, 99318, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Kill_Credit');
INSERT INTO `smart_scripts` VALUES (245274, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 33, 99319, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Kill_Credit');
`

**Comment by Elgrimm** [comment]
@yudian1944 Si tiene una versión diferente de los códigos fuente de estos, comparta las correcciones para no escribirlos en vano, pero en esta versión no encontré estas entradas y la búsqueda no funcionó.!

**Comment by yudian1944** [comment]
no he testeado las profesiones estoy testeando todas las campañas de  clases incluyendo todas las cadenas de misiones de 
 artefactos

**Comment by Elgrimm** [comment]
@yudian1944 Entonces, ¿por qué escribes si no lo has comprobado? ¡Escribo con lo que me encuentro personalmente y personalmente vuelvo a verificar si hago una corrección!

**Comment by Elgrimm** [comment]
@yudian1944 No entiendo a la gente que habla de lo que ellos mismos no saben.... Como tú, por ejemplo. Con tus palabras, suena como " hiciste esta corrección, pero funcionó, pero no sé qué es y no lo he probado."¿Estás loco?

**Comment by Elgrimm** [comment]
![a7a88a7d-b652-4ceb-9dae-6205b9f8f116](https://user-images.githubusercontent.com/36525398/192424323-4210ace5-0ba4-4e85-886b-ed4c1146a47f.jpg)

**Comment by Elgrimm** [comment]
En la pantalla, ya probé la corrección y completé esta búsqueda.

**Comment by yudian1944** [comment]
@Elgrimm Me entendiste mal quise decir que personalmente yo  me añadi la mision en mi servidor para comprobar si estaba rota o no antes de poner tu correccion pero la pude completar normalmente sin problema.  
![WoWScrnShot_092722_095420](https://user-images.githubusercontent.com/34819144/192544970-2abec93e-05b0-4002-9d16-59f834293027.jpg)

**Comment by Elgrimm** [comment]
@yudian1944 Veo que tiene un significado diferente y ya lo ha arreglado. En este proyecto no hay una solución, así que lo tiré.

**Comment by yudian1944** [comment]
@Elgrimm Si todo argus funciona 100% 
![WoWScrnShot_093022_093540](https://user-images.githubusercontent.com/34819144/193285747-90aca84c-f6ff-4eac-a4e1-269585588f4b.jpg)

![WoWScrnShot_093022_095255](https://user-images.githubusercontent.com/34819144/193285662-215c3ddc-e1bc-4279-be42-31fcc7f6f9af.jpg)
![WoWScrnShot_093022_095344](https://user-images.githubusercontent.com/34819144/193285695-975c0c35-6b2c-49c8-9c74-9ad11adcc561.jpg)

![WoWScrnShot_093022_094022](https://user-images.githubusercontent.com/34819144/193285649-c902b9af-feac-43df-87c4-8c88caa852b7.jpg)

![WoWScrnShot_093022_093723](https://user-images.githubusercontent.com/34819144/193285598-4048e755-4692-4a6f-953c-762d27558d61.jpg)
![WoWScrnShot_093022_093834](https://user-images.githubusercontent.com/34819144/193285618-2d116881-5597-443f-bae9-d5bcab7a68bb.jpg)
![WoWScrnShot_093022_093957](https://user-images.githubusercontent.com/34819144/193285632-c836bd2b-6402-4064-98a1-0734bbdd5a8d.jpg)

![WoWScrnShot_093022_093559](https://user-images.githubusercontent.com/34819144/193285511-189ddcda-47db-48da-8069-91c2e33e4d90.jpg)

**Comment by Elgrimm** [comment]
@yudian1944 Allí resulta que en las islas Divididas no se han implementado puntos de invasión para la tarea https://www.wowhead.com/quest=46247/defending-broken-isles
