### ISSUE TITLE
Garrison System

### ISSUE THREAD

**Issue by Thordekk** [dufernst/LegionCore-7.3.5#11]
Garrisson mission table and class hall not work?

**Comment by dufernst** [comment]
Class halls do work, and the garrison table should also works.
At least last time I checked.

**Comment by Thordekk** [comment]
Maybe can be updated to 8.0.1? or can start a new branch using this source for bfa?

**Comment by dufernst** [comment]
I won't be supporting BfA in this repo, but if someone feels like forking and taking it from there, then by all means :)

**Comment by dufernst** [comment]
In the latest commit all the WoD garrison command tables should work and class hall seemed to work in previous testing.
Closing this for now, if something is not working feel free to open a new issue @Thordekk .
