### ISSUE TITLE
About, phased opening   7.1   7.2   7.3

### ISSUE THREAD

**Issue by 9cwow** [dufernst/LegionCore-7.3.5#110]
Hello, brother. Excuse me, where is this controlled about the level of falling items in stages? For example, the 7.1 dungeon drop should be 810, but because the server uses 7.35, the drop will be 845+! How to make him drop the setting of 7.1 instead!

**Comment by dufernst** [comment]
@9cwow 
Support for releasing 7.1, 7.2 and 7.3 is supported out of the box.
Here you can see the SQL you have to run to disable content:
https://github.com/dufernst/LegionCore-7.3.5/tree/master/sql/optional
E.g. if you want to only have 7.1 content, run both [disable-patch-7.2-content.sql](https://github.com/dufernst/LegionCore-7.3.5/blob/master/sql/optional/disable-patch-7.2-content.sql) and [disable-patch-7.3-content.sql](https://github.com/dufernst/LegionCore-7.3.5/blob/master/sql/optional/disable-patch-7.3-content.sql).

Also set the corresponding game version with the Game.Patch setting in:
https://github.com/dufernst/LegionCore-7.3.5/blob/master/src/server/worldserver/worldserver.conf.dist#L21

**Comment by dufernst** [comment]
closing as resolved :)

**Comment by Nexon99** [comment]
Hi @dufernst ! 

If we set "Game.Patch = 0", it's the 7.0 ?

**Comment by dufernst** [comment]
@Nexon99 support for that is not implemented. You can only use 7.1, 7.2 or 7.3.
