### ISSUE TITLE
BattlePay Loading Glue screen

### ISSUE THREAD

**Issue by Axdrell** [dufernst/LegionCore-7.3.5#113]
Hi,

Does anyone know what part of the code controls the Client Gluescreen that shows up when BattlePay is loading? I ported over the battlepay code from the DuferNST branch to the Mobious Dev branch. I can see the Bpay products load correctly, but the "Loading - wait" screen does not go away. I confirmed is not an endless loop problem. Also tried sending out the client code to signal the battlepay finished. Still no go. 

If anyone can provide some pointers on what to check would be great.

Thanks so much.

Axdrell.

**Comment by Axdrell** [comment]
Does anyone have any suggestions? I checked the code multiple times and have not been able to identify why the loading screen is being called. Logs dont show anything and all the opcodes are working (I validated each opcode function).

**Comment by Axdrell** [comment]
@dufernst  - To troubleshoot this further, I commented out all the code from the Battlepay code (just passing empty functions) - to rule out issues with the ported code - still the BattlePay store UI shows up empty but the "Loading please wait" glue screen still shows up. Do you know what part of the code controls the "Loading please wait" glue screen? I search the dufernst branch code and I do not see anywhere where to turn this off.   thx

**Comment by dufernst** [comment]
@Axdrell with my master branch without modifications BattlePay works for the 1 supported item.
For anything else I don't provide support atm but BattlePay changes might arrive in the coming months on my master branch anyway.
