### ISSUE TITLE
How to double the artifact power acquisition?

### ISSUE THREAD

**Issue by EvilCalf** [dufernst/LegionCore-7.3.5#119]
How to double the artifact power acquisition?

**Comment by dufernst** [comment]
https://wowpedia.fandom.com/wiki/Artifact_Knowledge
you can raise the artifact knowledge in the database, that increases AP gain.

**Comment by EvilCalf** [comment]
> https://wowpedia.fandom.com/wiki/Artifact_Knowledge you can raise the artifact knowledge in the database, that increases AP gain.
Which table.....I hope for further help,thank you.

**Comment by dufernst** [comment]
Check this code: https://github.com/dufernst/LegionCore-7.3.5/blob/f8a73c84522bf49331c3696b182c3d32d37a0052/src/server/game/World/World.cpp#L3425
You can use the config option corresponding with CONFIG_ARTIFACT_KNOWLEDGE_START to set the initial artifact knowledge value. Or are you can see you can just set the worldstate corresponding with WS_CURRENT_ARTIFACT_KNOWLEDGE to the higher value.
