### ISSUE TITLE
Server start error

### ISSUE THREAD

**Issue by EvilCalf** [dufernst/LegionCore-7.3.5#120]
[2966212](https://github.com/dufernst/LegionCore-7.3.5/commit/2966212a72b7d9dc02680402135322c2d3a73489)
In new update,change the database.
ALTER TABLE `account_donate_token_log`
	ADD COLUMN `tokenType` TINYINT(3) UNSIGNED NOT NULL AFTER `change`,
	CHANGE COLUMN `change` `change` BIGINT(20) NOT NULL DEFAULT 0 AFTER `characterId`,
	CHANGE COLUMN `type` `buyType` TINYINT(3) UNSIGNED NOT NULL AFTER `tokenType`;

Then,when I restart the server. It shows as follows:

ERROR In mysql_stmt_prepare() id: 73, sql: "INSERT INTO `account_donate_token_log` (`accountId`, `realmId`, `characterId`, `change`, `type`, `productId`) VALUES (?, ?, ?, ?, ?, ?)"
ERROR Unknown column 'type' in 'field list'

**Comment by dufernst** [comment]
You are not using the C++ changes, or have not recompiled:
https://github.com/dufernst/LegionCore-7.3.5/commit/f8a73c84522bf49331c3696b182c3d32d37a0052#diff-db6d4ca92ceba4fe6913b1fad1f7fb1df8e948570a7989a77e8438ddce9b9fbfR111
