### ISSUE TITLE
Eye Beam Lag

### ISSUE THREAD

**Issue by EvilCalf** [dufernst/LegionCore-7.3.5#121]
When dh cast Eye Beam on much target,it will be huge lag.

**Comment by dufernst** [comment]
I have no such issues, maybe your client/server cannot handle the load?

**Comment by EvilCalf** [comment]
> I have no such issues, maybe your client/server cannot handle the load?

My server is 4 core and 16gRam. Is there any config related to this.

**Comment by dufernst** [comment]
No config option, you would have to monitor resource usage on your server/client to see what is going on.

**Comment by EvilCalf** [comment]
> No config option, you would have to monitor resource usage on your server/client to see what is going on.

All the resource usage is on a low level. They all above 10%, and the network is under 20kb/s.

Only when target over about 20, it will be lag.Display in the game about 200-300ms.

**Comment by dufernst** [comment]
I'd have to try it, but don't remember ever running into this issue.
Don't know when I'll get to this, maybe someone else can confirm?

**Comment by EvilCalf** [comment]
> I'd have to try it, but don't remember ever running into this issue. Don't know when I'll get to this, maybe someone else can confirm?

Thank you a lot.We are several people fighting Dungeons above 2.When target over 20，it will occur.All the memmber have lag.

Or how to help you to confirm.

**Comment by dufernst** [comment]
I'll see if I can reproduce it this evening.

**Comment by EvilCalf** [comment]
OK,thank you.I played challenge mode with 4 guys between 15:30-16:40.
My server is 4core,16gRam and 1 Mb/s bandwidth
Here are my resource usage:
Cpu
![image](https://user-images.githubusercontent.com/35754619/210543325-e9b4ff23-1ef3-4a5f-9647-7a492753aa85.png)
IO
![image](https://user-images.githubusercontent.com/35754619/210543725-04367ec4-3e68-45d4-b456-f670220bac8f.png)
Network In
![image](https://user-images.githubusercontent.com/35754619/210543762-5df2a3b3-6625-43fc-aba9-c7b6c02b4636.png)
Network Out
![image](https://user-images.githubusercontent.com/35754619/210543855-3aecf3f4-e45c-4438-80a8-43b58db06119.png)

**Comment by EvilCalf** [comment]
The skill is completely casted on the monster, and the delay will be higher and higher

**Comment by dufernst** [comment]
Any particular creatures you cast it on, or do you get the same effect regardless of which creature?

**Comment by EvilCalf** [comment]
> Any particular creatures you cast it on, or do you get the same effect regardless of which creature?

Any creature in Dungeons. T attracted a lot of creatures hatred, and the i(dh) cast eye beam.Then everyone lags.Of course ,these creature can't be killed by one eye beam.

Oh, i equip the dh orange head,

**Comment by dufernst** [comment]
Which item do you mean with DH orange head? And do you get the same issues without gear equipped?

**Comment by EvilCalf** [comment]
Raddon's Cascading Eyes.And I get the same issues without gear equipped. It seems that lag is more serious.

**Comment by dufernst** [comment]
I tested with 30 guards in Stormwind that didn't give me any issues.
I know you mentioned it was in a dungeon, which one in particular?
And can you confirm you don't experience the issue outside of dungeons?
Last question, can you share which talents you are using, maybe something goes wrong with one that I am not using.

**Comment by EvilCalf** [comment]
> I tested with 30 guards in Stormwind that didn't give me any issues. I know you mentioned it was in a dungeon, which one in particular? And can you confirm you don't experience the issue outside of dungeons? Last question, can you share which talents you are using, maybe something goes wrong with one that I am not using.

Thank you for your all help.You are so kind.
Frist of all, my server is remote server. This is maybe a reason, but my bindwidth did not reach the limit.
Sencond, outside of dungeons the lag is few, and i cant feel it.
Third, If you can, please help me to test Vault of the Wardens as follows location.
![image](https://user-images.githubusercontent.com/35754619/210677791-c79ae88d-df6c-4bf4-9950-d59d6e17e5e2.png)
It has a lmp mother and lots of lmps here.When gather all of them, the targets are over 30.
At this time, team maybe is up to 3 characters.In my server, it 100% occur lag.
And, my talents are as follow:
![image](https://user-images.githubusercontent.com/35754619/210678490-e73c3820-b227-474c-a4ab-96fde2d85763.png)

The last, thank you very much.

**Comment by dufernst** [comment]
I'll test it again this evening in that exact spot with the same talents.

**Comment by dufernst** [comment]
@EvilCalf tested it with the same talents at the same spot, no issue to be found :|
Anything else that comes to mind for you? Do you also have the issue when you are killing those npcs on your own?
Maybe it is one of the other classes with a talent that does not play nice together with eye beam.

If you also have the issue when you are alone then we need to create  packetlog of the situation so I can see what you are sending/receiving from the server.
