### ISSUE TITLE
Error loading server

### ISSUE THREAD

**Issue by zTerragor** [dufernst/LegionCore-7.3.5#123]
Server error log:
`In mysql_stmt_prepare() id: 82, sql: "SELECT guildid, rank FROM guild_member WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM guild_member WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 147, sql: "INSERT INTO guild_member (guildid, guid, rank, pnote, offnote) VALUES (?, ?, ?, ?, ?)"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, pnote, offnote) VALUES (?, ?, ?, ?, ?)' at line 1
In mysql_stmt_prepare() id: 150, sql: "UPDATE guild_member SET rank = ? WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank = ? WHERE guildid = ? AND rank = ?' at line 1
In mysql_stmt_prepare() id: 177, sql: "UPDATE guild_member SET rank = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 191, sql: "UPDATE guild_member SET BankResetTimeMoney = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 210, sql: "UPDATE guild_member SET BankResetTimeTab0 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 211, sql: "UPDATE guild_member SET BankResetTimeTab1 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 212, sql: "UPDATE guild_member SET BankResetTimeTab2 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 213, sql: "UPDATE guild_member SET BankResetTimeTab3 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 214, sql: "UPDATE guild_member SET BankResetTimeTab4 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 215, sql: "UPDATE guild_member SET BankResetTimeTab5 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 216, sql: "UPDATE guild_member SET BankResetTimeTab6 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 217, sql: "UPDATE guild_member SET BankResetTimeTab7 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 309, sql: "INSERT INTO gm_subsurveys (surveyId, subsurveyId, rank, comment) VALUES (?, ?, ?, ?)"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, comment) VALUES (?, ?, ?, ?)' at line 1
In mysql_stmt_prepare() id: 320, sql: "INSERT INTO groups (guid, leaderGuid, lootMethod, looterGuid, lootThreshold, icon1, icon2, icon3, icon4, icon5, icon6, icon7, icon8, groupType, difficulty, legacyRaidDifficulty, raiddifficulty) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (guid, leaderGuid, lootMethod, looterGuid, lootThreshold, icon1, icon2, i' at line 1
In mysql_stmt_prepare() id: 324, sql: "UPDATE groups SET leaderGuid = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET leaderGuid = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 325, sql: "UPDATE groups SET groupType = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET groupType = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 329, sql: "UPDATE groups SET difficulty = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET difficulty = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 330, sql: "UPDATE groups SET raiddifficulty = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET raiddifficulty = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 331, sql: "UPDATE groups SET legacyRaidDifficulty = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET legacyRaidDifficulty = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 407, sql: "DELETE FROM groups WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups WHERE guid = ?' at line 1
`

**Comment by dufernst** [comment]
You must be missing some database updates or have incorrectly configured your worldserver.

**Comment by zTerragor** [comment]
already applied full updates. and  check worldserver configs

**Comment by JerryDevR** [comment]
I'm getting the exact same error attempting to boot up the world server.

In mysql_stmt_prepare() id: 82, sql: "SELECT guildid, rank FROM guild_member WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM guild_member WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 147, sql: "INSERT INTO guild_member (guildid, guid, rank, pnote, offnote) VALUES (?, ?, ?, ?, ?)"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, pnote, offnote) VALUES (?, ?, ?, ?, ?)' at line 1
In mysql_stmt_prepare() id: 150, sql: "UPDATE guild_member SET rank = ? WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank = ? WHERE guildid = ? AND rank = ?' at line 1
In mysql_stmt_prepare() id: 177, sql: "UPDATE guild_member SET rank = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 191, sql: "UPDATE guild_member SET BankResetTimeMoney = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 210, sql: "UPDATE guild_member SET BankResetTimeTab0 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 211, sql: "UPDATE guild_member SET BankResetTimeTab1 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 212, sql: "UPDATE guild_member SET BankResetTimeTab2 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 213, sql: "UPDATE guild_member SET BankResetTimeTab3 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 214, sql: "UPDATE guild_member SET BankResetTimeTab4 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 215, sql: "UPDATE guild_member SET BankResetTimeTab5 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 216, sql: "UPDATE guild_member SET BankResetTimeTab6 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 217, sql: "UPDATE guild_member SET BankResetTimeTab7 = 0 WHERE guildid = ? AND rank = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= ?' at line 1
In mysql_stmt_prepare() id: 309, sql: "INSERT INTO gm_subsurveys (surveyId, subsurveyId, rank, comment) VALUES (?, ?, ?, ?)"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, comment) VALUES (?, ?, ?, ?)' at line 1
In mysql_stmt_prepare() id: 320, sql: "INSERT INTO groups (guid, leaderGuid, lootMethod, looterGuid, lootThreshold, icon1, icon2, icon3, icon4, icon5, icon6, icon7, icon8, groupType, difficulty, legacyRaidDifficulty, raiddifficulty) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (guid, leaderGuid, lootMethod, looterGuid, lootThreshold, icon1, icon2, i' at line 1
In mysql_stmt_prepare() id: 324, sql: "UPDATE groups SET leaderGuid = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET leaderGuid = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 325, sql: "UPDATE groups SET groupType = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET groupType = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 329, sql: "UPDATE groups SET difficulty = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET difficulty = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 330, sql: "UPDATE groups SET raiddifficulty = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET raiddifficulty = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 331, sql: "UPDATE groups SET legacyRaidDifficulty = ? WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups SET legacyRaidDifficulty = ? WHERE guid = ?' at line 1
In mysql_stmt_prepare() id: 407, sql: "DELETE FROM groups WHERE guid = ?"
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups WHERE guid = ?' at line 1

**Comment by JerryDevR** [comment]
Are you using Sql server 8.0? Try dropping down to 5.7 and rebuild your database and sln targeting the 5.7 directory. This cleared this up for me.

**Comment by dufernst** [comment]
MySQL 5.6 is easier, with anything after that you have to at least do (as mentioned in the readme):
Disable the NO_ZERO_IN_DATE sql_mode.
I consider it closed for now, feel free to reopen if needed.
