### ISSUE TITLE
Garrison 

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#124]
Tell me, who tested the Garrison? What doesn't work there and what needs to be fixed? I can make simple NPC quest fixes if you tell me what exactly is not working

**Comment by dufernst** [comment]
Warlords of Draenor garrisons you mean? Most of the actual building functionality doesn't work yet, but the base does work. Building new buildings and their spawns.

**Comment by Elgrimm** [comment]
Yes Draenor! =)

**Comment by dufernst** [comment]
Well the basics should mostly work, except for the shipyard, but quite a bit of the actual content in the garrison is not working. You could playtest and soon enough you will run into some issues :)

**Comment by Elgrimm** [comment]
The problem is that there is no time to test, I am doing a little other fixes for Scenarios in draenor.

**Comment by dufernst** [comment]
Maybe someone else will have the time then :)

**Comment by Elgrimm** [comment]
@dufernst Have you ever faced such a problem that when you use this item in the arena https://www.wowhead.com/item=58860/gurubashi-challenge-flag A message is displayed that this cannot be done in the PVP zone

**Comment by dufernst** [comment]
No, but I only test things when I think it is urgent enough. This doesn't sound all that important :)?

**Comment by Elgrimm** [comment]
Yes, it's a trifle, I'll just double-check, maybe what I'm doing is wrong, but there is no explicit condition on the proc of the spell, only the condition that the player must be in that zone.

**Comment by Elgrimm** [comment]
![8cb6104e-4d8b-48da-8737-4b6242476df1 (1)](https://user-images.githubusercontent.com/36525398/212550629-26014039-64d2-4f3b-862f-9238f1ad23b5.jpeg)

**Comment by Elgrimm** [comment]
@dufernst yes not work

**Comment by dufernst** [comment]
Still, doesn't look all that important to fix :P?

**Comment by Elgrimm** [comment]
@dufernst I think it's important. Only if there is a condition that you should not be in the pvp instance zone, then how to write so that it is ignored?

**Comment by Elgrimm** [comment]
if (player==PVP_INSTANCE)
SPELL_CAST_OKK
???

**Comment by dufernst** [comment]
The best way to go about it is to first, using a debugger, see where in the code it actually goes wrong.
Or you can try to find the particular trigger in the source code and hopefully make sense out of it why it happens.

**Comment by Elgrimm** [comment]
@dufernst I made a script with a check for the zone of application and so that the item was triggered being in this zone, and I made a script for the spell itself, but still the same error.... Now I don't understand how to fix it in this case. I need your help.

**Comment by Elgrimm** [comment]
class spell_item_gurbashi_flags_vpvp : public SpellScript
{
    PrepareSpellScript(spell_item_gurbashi_flags_vpvp);

    SpellCastResult CheckRequirement()
    {
        if (auto caster = GetCaster()->ToPlayer())
        {
            if (caster->GetMap()->IsBattleground())
                return SPELL_CAST_OK;
            else if (caster->GetCurrentZoneID() == 5287 && caster->GetCurrentAreaID() == 2177)
                return SPELL_CAST_OK;
        }

        return SPELL_CAST_OK;
    }

    void Register() override
    {
        OnCheckCast += SpellCheckCastFn(spell_item_gurbashi_flags_vpvp::CheckRequirement);
    }

};

**Comment by dufernst** [comment]
If I were you I would run the server in a debugger to see what is going on.
Without knowing what is causing the issue it is hard to come with a proper fix.
