### ISSUE TITLE
WorldServer database errors

### ISSUE THREAD

**Issue by LoveBeforT** [dufernst/LegionCore-7.3.5#126]
i'm using the latest sql files in this source, and imported the sql updates.
[World.log](https://github.com/dufernst/LegionCore-7.3.5/files/10495799/World.log)

**Comment by Elgrimm** [comment]
UPDATE `creature_template` SET `InhabitType`='7' WHERE `InhabitType`=8;
UPDATE `creature_template` SET `flags_extra`='0' WHERE `entry` IN (37813, 124445, 124445);

**Comment by Elgrimm** [comment]
And then, by analogy, you read errors and see what value should stand ..... Do you know how to write queries in sql?

**Comment by LoveBeforT** [comment]
ok, I'll try it~

**Comment by LoveBeforT** [comment]
this works for me,

**Comment by dufernst** [comment]
Based on the response, I assume this is closed, otherwise feel free to reopen.
