### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ooinini** [dufernst/LegionCore-7.3.5#127]
Need some help! Please. 7.35Legion. There are some problems with my server. When the number of players reaches "100", they will be drop. This "100" is not a fixed value. It can reach 128 people at most. I looked up my source code and didn't find the value of the number limit. I also tried to modify the number of threads in worldconfig, but it didn't work.

**Comment by dufernst** [comment]
@ooinini did you resolve the issue and can this be closed or?

**Comment by ooinini** [comment]
Yeah ,resolved. Thanks.
















At 2023-02-15 03:31:52, "dufernst" ***@***.***> wrote:

@ooinini did you resolve the issue and can this be closed or?

**Comment by dufernst** [comment]
Resolved so closed :)
