### ISSUE TITLE
requerimientos para compilar en windows

### ISSUE THREAD

**Issue by Maxyazraell** [dufernst/LegionCore-7.3.5#128]
me gustaria sacer que verciones de programas se requieren para compilar este codigo en windows10
bosst
cmake
openssl
git

**Comment by dufernst** [comment]
boost 1.64 as mentioned in the readme
cmake 3.9 as indicated when you try to run cmake
openssl a version like 1.* should be fine
git version does not matter

**Comment by Maxyazraell** [comment]
![image](https://user-images.githubusercontent.com/104529567/216743659-1adcfd8f-65e5-4a8c-a98b-e000ea278203.png)

ps no sirvio 

CMake Error at CMakeLists.txt:15 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    



Configuring incomplete, errors occurred!
See also "C:/Users/hacker9/Desktop/leg3/CMakeFiles/CMakeOutput.log".

**Comment by Maxyazraell** [comment]
> @dufernst still confused too. I made it past configuring and generating for VS 2017 but while building it would fail on bnet, world server, etc.
> 
> CMAKE 3.26.0 Boost 1_64_0 64 bit Visual Studio 2017

 ps CMake Error at CMakeLists.txt:15 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    



Configuring incomplete, errors occurred!
See also "C:/Users/hacker9/Desktop/leg3/CMakeFiles/CMakeOutput.log".
tampoco

**Comment by Maxyazraell** [comment]
ps con el cmake tampoco 
![image](https://user-images.githubusercontent.com/104529567/216744082-8a30e790-d638-4e92-839d-075cd71ecdd6.png)

**Comment by T-R-I-X** [comment]
@Maxyazraell which boost type are you using x64 or x32?

**Comment by Maxyazraell** [comment]
64

**Comment by T-R-I-X** [comment]
File > Delete Cache

Click configure again and show me the prompt

**Comment by Maxyazraell** [comment]
voy a reinstalar todo aver y ya le cuento

**Comment by Maxyazraell** [comment]
![image](https://user-images.githubusercontent.com/104529567/216746015-42481840-59b5-4e26-be07-578e722a3893.png)

**Comment by Maxyazraell** [comment]
y antes de lo ue l diga si la variable esta bien 
![image](https://user-images.githubusercontent.com/104529567/216746041-c428de5e-e68a-4242-a7fb-241daa46d974.png)

**Comment by Maxyazraell** [comment]
![image](https://user-images.githubusercontent.com/104529567/216746059-52d8032f-eee9-47f6-870a-1e1ec6877f94.png)

**Comment by Maxyazraell** [comment]
bueno con el visual 2019 si me dejo compilar normal

**Comment by T-R-I-X** [comment]
Did you fix it? I have been having issues with compiling on VS17

**Comment by dufernst** [comment]
@Maxyazraell like @T-R-I-X is showing set the BOOST_ROOT variable manually and then configure.
@T-R-I-X can you share the compilation logs? If I remember correctly you have to compile either Release or RelWithDebugInfo for it to work but I can tell you more based on the logs.

**Comment by T-R-I-X** [comment]
I have compiled using RelWithDebugInfo. I get thousands of MySQL errors and then common will fail to compile which leads to the rest failing. @dufernst

**Comment by dufernst** [comment]
@T-R-I-X which MySQL version are you using? 5.6 is the preferred version, otherwise 5.7 by disabling the NO_ZERO_IN_DATE sql_mode.

**Comment by T-R-I-X** [comment]
5.7 I've set `sqlmode=""` and restarted my server to disable ZERO_IN_DATE

**Comment by dufernst** [comment]
And can you check in your cmake output that cmake is really using 5.7?

**Comment by T-R-I-X** [comment]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/24784631/216770669-463a1a7a-156c-4f70-aca2-5b1e6467b397.png">

**Comment by T-R-I-X** [comment]
I used to have 8 installed but I removed it via the installer and installed 5.7

**Comment by dufernst** [comment]
It is possible that the files in C:/tools/mysql/current/include are still from 8. Or it could be a mix of 5.7 and 8.*.
Can you delete the whole C:/tools/mysql directory and reinstall 5.7?

**Comment by T-R-I-X** [comment]
If I am reinstalling I am just going to get mysql 5.6. Which version do you recommend?

**Comment by dufernst** [comment]
5.6 because then it works fine by default 👍

**Comment by T-R-I-X** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/24784631/216770964-3b38ddaf-8a0e-4b46-a17a-3fb1b4ca85a8.png">
Does it matter which minor release I pick?

**Comment by dufernst** [comment]
The latest minor version is fine, but any will do.

**Comment by T-R-I-X** [comment]
I will let you know. Do I have to change my boost from 64 to 32 bit as mysql 5.6 is only 32 bit?

**Comment by dufernst** [comment]
64 bit is fine, and also according to their forum the 32 bit installer actually has the option to install the 5.6 64 bit version.
https://forums.mysql.com/read.php?169,578507,578570#msg-578570

**Comment by T-R-I-X** [comment]
According to the installer it can't find packages suitable for me?

**Comment by T-R-I-X** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/24784631/216771321-8cc5f4d2-fa7d-4df3-b0bd-5ae6ca7dec7e.png">

**Comment by dufernst** [comment]
2 options:
You can try the web installer:
https://downloads.mysql.com/archives/get/p/25/file/mysql-installer-web-community-5.6.51.0.msi
I guess it will allow you to download the right version during install.

Alternatively you can download the zipped version:
https://downloads.mysql.com/archives/get/p/23/file/mysql-5.6.51-winx64.zip
This is not an installer so you would have to manually configure access to it, but it is the 64 bit version of 5.6.

**Comment by T-R-I-X** [comment]
I will try web rq

**Comment by dufernst** [comment]
Otherwise the second option will definitely work but it is a bit more of a hassle.
1. You would have to extract the zip and put the content somewhere.
2. You would have to manually start the executable when you want to use mysql (creating a shortcut is easy enough).
3. You would have to manually point cmake to the right directory for mysql (but I think you know how to do that).

I am offline the remainder of the day, good luck, if it isn't working I will see it tomorrow :)

**Comment by T-R-I-X** [comment]
It worked I am installing 5.6

**Comment by T-R-I-X** [comment]
It worked

**Comment by Maxyazraell** [comment]
yo tengo el mysql 5.7 funciono bien

lo que si es un error en el ultimo update del auth

**Comment by dufernst** [comment]
@T-R-I-X great :)
@Maxyazraell please share the specific errors if you have any.

**Comment by T-R-I-X** [comment]
@dufernst i compiled trinity core tools, where do I generate the .txt file I need also mysqllib.DLL is missing

**Comment by T-R-I-X** [comment]
@dufernst he probably has VS17 cmake configured in a Win32 environment even though he has the 64bit boost libs installed. You can get the "no boost libs found" error when configuring the wrong environment.

**Comment by Maxyazraell** [comment]
5 queries executed, 2 success, 3 errors, 0 warnings

Query: ALTER TABLE `account_donate_token_log` ADD COLUMN `tokenType` TINYINT(3) UNSIGNED NOT NULL AFTER `change`, CHANGE COLUMN `change...

Error Code: 1054
Unknown column 'type' in 'account_donate_token_log'

Execution Time : 0 sec
Transfer Time  : 0 sec
Total Time     : 0.002 sec
-----------------------------------------------------------

Query: UPDATE `account_donate_token_log` SET `tokenType` = 1

0 row(s) affected

Execution Time : 0 sec
Transfer Time  : 0 sec
Total Time     : 0 sec
-----------------------------------------------------------

Query: CREATE TABLE `account_tokens` ( `account_id` INT(10) UNSIGNED NOT NULL, `tokenType` TINYINT(3) UNSIGNED NOT NULL, `amount` BIGIN...

Error Code: 1050
Table 'account_tokens' already exists

Execution Time : 0 sec
Transfer Time  : 0 sec
Total Time     : 0.001 sec
-----------------------------------------------------------

Query: INSERT INTO account_tokens SELECT id, 1, balans FROM account WHERE balans > 0

0 row(s) affected

Execution Time : 0.001 sec
Transfer Time  : 0 sec
Total Time     : 0.001 sec
-----------------------------------------------------------

Query: ALTER TABLE `account` ADD COLUMN `first_ip` VARCHAR(15) NOT NULL DEFAULT '127.0.0.1' AFTER `joindate`, CHANGE COLUMN `referer` `...

Error Code: 1366
Incorrect integer value: '' for column 'referer' at row 1

Execution Time : 0 sec
Transfer Time  : 0 sec
Total Time     : 0.469 sec


eso esta en el update 0003_battlepay_rework.sql

**Comment by dufernst** [comment]
@Maxyazraell did you run the queries in the right order?
The table you are trying to modify is created in the following file (which should be executed before 0003):
https://github.com/dufernst/LegionCore-7.3.5/blob/master/sql/updates/auth/0002_battlepay_cleanup.sql

**Comment by Maxyazraell** [comment]
Si los ejecute en el orden que presisa

**Comment by dufernst** [comment]
Uhhhhhh. Hard to say what is going wrong then, for me the queries work fine :)

**Comment by Maxyazraell** [comment]
Mm PS raro cuando ejecuto el último update de los auth me da esos errores
Los dos anteriores cargan bien

**Comment by dufernst** [comment]
@Maxyazraell I just noticed: `Table 'account_tokens' already exists`, you are rerunning the query (probably by accident).
Rerunning these queries won't work, so you would have to manually check if it is correct now or try to recreate the auth table.

**Comment by Maxyazraell** [comment]
Ok en un rato que llegue. Ala casa me pongo en eso y le cuento cómo me va

**Comment by Maxyazraell** [comment]
2023-02-04_22:51:37 INFO  Using configuration file bnetserver.conf.
2023-02-04_22:51:37 INFO  Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
2023-02-04_22:51:37 INFO  Using Boost version: 1.64.0
2023-02-04_22:51:37 ERROR In mysql_stmt_prepare() id: 33, sql: "UPDATE account SET first_ip = ? WHERE id = ?"
2023-02-04_22:51:37 ERROR Unknown column 'first_ip' in 'field list'
2023-02-04_22:51:37 ERROR In mysql_stmt_prepare() id: 76, sql: "INSERT INTO account_tokens (account_id, tokenType, amount) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE amount = amount + ?;"
2023-02-04_22:51:37 ERROR Table 'leg_auth.account_tokens' doesn't exist
2023-02-04_22:51:37 ERROR In mysql_stmt_prepare() id: 78, sql: "INSERT INTO `account_donate_token_log` (`accountId`, `realmId`, `characterId`, `change`, `tokenType`, `buyType`, `productId`) VALUES (?, ?, ?, ?, ?, ?, ?)"
2023-02-04_22:51:37 ERROR Unknown column 'tokenType' in 'field list'
2023-02-04_22:51:38 ERROR DatabasePool leg_auth NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors. Read wiki at http://collab.kpsn.org/display/tc/TrinityCore+Home

**Comment by dufernst** [comment]
@Maxyazraell you didn't run https://github.com/dufernst/LegionCore-7.3.5/blob/master/sql/updates/auth/0003_battlepay_rework.sql because that one adds that "missing" column: `tokenType`.

**Comment by Maxyazraell** [comment]
![image](https://user-images.githubusercontent.com/104529567/216848302-481fbdc2-b24f-4b13-9abd-282dff612223.png)

**Comment by dufernst** [comment]
@Maxyazraell I updated:
https://github.com/dufernst/LegionCore-7.3.5/blob/master/sql/updates/auth/0003_battlepay_rework.sql
now it should work even though you already have rows in the table.
Depending on your skill you might have to recreate the whole table again :)

**Comment by Maxyazraell** [comment]
ok montare todo de nuevo y le cuento

**Comment by Maxyazraell** [comment]
ok ya abrio todo ya puedo entrar al juego ahora sii  gracias master por la ayuda

ahora a tratar de arregar todos los errores que muertra el worldserver xD

**Comment by dufernst** [comment]
No problem and good luck, closing this one now :)
