### ISSUE TITLE
How do i add new Items to the BattlePay System?

### ISSUE THREAD

**Issue by DuelistRag3** [dufernst/LegionCore-7.3.5#13]
Simple Question above in header ^^

**Comment by dufernst** [comment]
Adding new items in BattlePay is not supported, only the 1 hardcoded shop item will work.

**Comment by Elgrimm** [comment]
Hi. I have an incomprehensible problem. When buying, he writes that "Establishing a connection with the store" is endless ...

**Comment by dufernst** [comment]
You did run this mandatory SQL update?
https://github.com/dufernst/LegionCore-7.3.5/blob/master/sql/updates/world/0003_battlepay_cleanup.sql

**Comment by Elgrimm** [comment]
Yes. The only thing I didn’t do was download this update.
https://github.com/dufernst/LegionCore-7.3.5/commit/5e124f4236e1270c6d3b601c0cfe11e207708909

**Comment by dufernst** [comment]
You might have to add this column:
ADD COLUMN `balans` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `hwid`
to the account table.

**Comment by Elgrimm** [comment]
![Uploading Новый точечный рисунок.jpg…]()

**Comment by Elgrimm** [comment]
![Новый точечный рисунок](https://user-images.githubusercontent.com/36525398/115146371-e5efcc80-a05e-11eb-912e-e8c86c0e8412.jpg)

**Comment by dufernst** [comment]
Any errors in the worldserver log?

**Comment by fluxurion** [comment]
The shop only works ingame. We should figure out how to hide the button in the character screen but show it ingame..

**Comment by dufernst** [comment]
Ah, I hadn't noticed that he was on the character select screen @fluxurion 
I guess I will pick this up soon~ish.

**Comment by Ragelezz** [comment]
to add additional items you need to remove the hardcoded code about the service option which is at BattlePayPackets.cpp file.

**Comment by dufernst** [comment]
All the above is fixed in:
https://github.com/dufernst/LegionCore-7.3.5/commit/f8a73c84522bf49331c3696b182c3d32d37a0052
