### ISSUE TITLE
solucion temporal

### ISSUE THREAD

**Issue by yudian1944** [dufernst/LegionCore-7.3.5#131]
Esta muy bueno este core lo unico que me molesta en el es no poder jugar mi cazador Bestia por el molesto bug que ocurre cuando con la mascota cuando viajas de un mapa a otro que se queda con 0p de vida y no se puede revivir ni retirar  esto ocurre incluso al entrar en arenas y bg y obligado hay que relogear el cliente para que la mascota vuelva a salir con vida, mi pregunta @dufernst  como podria crear una solucion temporal en el codigo para que al menos al viajar de un mapa a otro que la mascota del cazador automaticamente  se retire y haya que volver a invocarla al menos de esta forma no hay que relogear el cliente

**Comment by dufernst** [comment]
@yudian1944 fixing pet behaviour is actually on top of my current todolist so hopefully it will already get addressed the coming weeks.

**Comment by Elgrimm** [comment]
@dufernst cool

**Comment by Elgrimm** [comment]
game\Spells\SpellEffects.cpp
`void Spell::EffectSummonDeadPet(SpellEffIndex /*effIndex*/)
{...
Pet* pet = player->GetPet();
  --  if (!pet)
++ if (pet && pet->isAlive())
 ++       return;
-- return;

--    if (pet->isAlive())
--        return;
if (damage < 0)
        return;

    float x, y, z;
    player->GetPosition(x, y, z);
++ if (!pet)
 ++   {
     ++   player->SummonPet(0, x, y, z, player->GetOrientation(), SUMMON_PET, 0);
   ++     pet = player->GetPet();
  ++  }
 ++   if (!pet)
    ++    return;
player->GetMap()->CreatureRelocation(pet, x, y, z, player->GetOrientation());`

**Comment by Elgrimm** [comment]
I apologize for the incorrect design of the comment

**Comment by yudian1944** [comment]
> return;
lo probare aver si resuelvo mientras dufernst  corrige las  mascotas

**Comment by yudian1944** [comment]
Elgrimm  al menos  ya no hay que relogear,  si se pudiera modificar para que la mascota se mantenga con toda su salud y no se quede con solo 1p quedaria  bastante bien.

**Comment by Elgrimm** [comment]
in ...game\Entities\Pet.cpp

bool Pet::LoadPetFromDB(Player* owner, uint32 petentry, uint32 petnumber)
{
...........

-- if (!savedhealth && getPetType() == HUNTER_PET)
    --    setDeathState(JUST_DIED);
--    else if (getPetType() == HUNTER_PET)
--    {
   --     SetHealth(savedhealth > GetMaxHealth() ? GetMaxHealth() : savedhealth);
 --       SetFullHealth();
 --       SetPower(getPowerType(), savedmana > uint32(GetMaxPower(getPowerType())) ? GetMaxPower(getPowerType()) : savedmana);
--    }
+
+ if (getPetType() == SUMMON_PET && !current) 
    +    {
      +       SetPower(POWER_MANA, GetMaxPower(POWER_MANA));
   +          SetFullHealth();
   +      }
 +        else
    +     {
  +           if (!savedhealth && getPetType() == HUNTER_PET)
    +             setDeathState(JUST_DIED);
    +         else
      +       {
      +           SetHealth(savedhealth > GetMaxHealth() ? GetMaxHealth() : savedhealth);
        +         SetPower(POWER_MANA, savedmana > GetMaxPower(POWER_MANA) ? GetMaxPower(POWER_MANA) : savedmana);
      +       }
   +      }
SetTratsport(owner->GetTransport());

**Comment by yudian1944** [comment]
> in ...game\Entities\Pet.cpp
> 
> bool Pet::LoadPetFromDB(Player* owner, uint32 petentry, uint32 petnumber) { ...........
> 
> -- if (!savedhealth && getPetType() == HUNTER_PET) -- setDeathState(JUST_DIED); -- else if (getPetType() == HUNTER_PET) -- { -- SetHealth(savedhealth > GetMaxHealth() ? GetMaxHealth() : savedhealth); -- SetFullHealth(); -- SetPower(getPowerType(), savedmana > uint32(GetMaxPower(getPowerType())) ? GetMaxPower(getPowerType()) : savedmana); -- } ++ ++ if (getPetType() == SUMMON_PET && !current) ++ { ++ SetPower(POWER_MANA, GetMaxPower(POWER_MANA)); ++ SetFullHealth(); ++ } ++ else ++ { ++ if (!savedhealth && getPetType() == HUNTER_PET) ++ setDeathState(JUST_DIED); ++ else ++ { ++ SetHealth(savedhealth > GetMaxHealth() ? GetMaxHealth() : savedhealth); ++ SetPower(POWER_MANA, savedmana > GetMaxPower(POWER_MANA) ? GetMaxPower(POWER_MANA) : savedmana); ++ } ++ } SetTratsport(owner->GetTransport());

Cuando aplico estos cambios me da error en VS2019 
![Captura](https://user-images.githubusercontent.com/34819144/217916215-c288f5fe-e1d4-4abb-94a3-c344e4d9fbcd.PNG)

**Comment by dufernst** [comment]
Thanks for sharing @Elgrimm maybe it will be useful for when I am diving into the issue in the coming days/weeks :)

**Comment by Elgrimm** [comment]
> if (getPetType() == SUMMON_PET && !current)
@yudian1944 
-- if (getPetType() == SUMMON_PET && !current) 
++ if (getPetType() == SUMMON_PET)

**Comment by Elgrimm** [comment]
@yudian1944 
or add identifier current in bool Pet::LoadPetFromDB
But try it first without him, let there be a check only on the pet.  if (getPetType() == SUMMON_PET)

**Comment by yudian1944** [comment]
@Elgrimm Ahora si me funciono muchas gracias genio y cierro tema.

**Comment by Elgrimm** [comment]
@yudian1944 Have you checked? Does this solve the problem? I haven't tested the bath theory, but I think it should solve the problem with the pet's standard of living.

**Comment by yudian1944** [comment]
@Elgrimm  si ya lo comprobe  y funciona quizas no este blizzlike pero  solo buscaba una solucion temporal a este bug y con tu ayuda lo hice gracias de nuevo

**Comment by Elgrimm** [comment]
@yudian1944 Good!
