### ISSUE TITLE
Fix Silithius phase

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#133]
```
UPDATE `creature` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10277);
UPDATE `creature` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10435);
UPDATE `creature` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10436);
UPDATE `gameobject` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10277);
UPDATE `gameobject` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10436);
UPDATE `gameobject` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10435);
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=128607;
DELETE FROM `condition` WHERE `SourceGroup`=1377;
INSERT INTO `conditions` VALUES (23, 1377, 3, 0, 1, 12, 0, 86, 0, 0, 1, 0, '', 'True If Event Active');
INSERT INTO `conditions` VALUES (23, 1377, 10, 0, 0, 6, 0, 469, 0, 0, 0, 0, '', 'True If Player has Alliance Faction');
INSERT INTO `conditions` VALUES (23, 1377, 13, 0, 0, 8, 0, 50049, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 10, 0, 0, 6, 0, 67, 0, 0, 0, 0, '', 'True If Player has Horde Faction');
INSERT INTO `conditions` VALUES (23, 1377, 13, 0, 0, 28, 0, 50049, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 15, 0, 0, 14, 0, 50300, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 14, 0, 0, 8, 0, 50057, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 13, 0, 0, 14, 0, 50373, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 12, 0, 0, 14, 0, 50360, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 11, 0, 0, 14, 0, 49977, 0, 0, 0, 0, '', 'Activate Phase - If Player NHCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 2, 0, 1, 12, 0, 86, 0, 0, 1, 0, '', 'True If Event Active');
INSERT INTO `conditions` VALUES (23, 1377, 13, 0, 0, 9, 0, 50049, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 14, 0, 0, 14, 0, 50056, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 12, 0, 0, 9, 0, 50055, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 12, 0, 0, 8, 0, 50055, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 12, 0, 0, 28, 0, 50055, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 15, 0, 0, 8, 0, 50057, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 2, 0, 0, 6, 0, 67, 0, 0, 0, 0, '', 'True If Player has Horde Faction');
INSERT INTO `conditions` VALUES (23, 1377, 3, 0, 0, 6, 0, 469, 0, 0, 0, 0, '', 'True If Player has Alliance Faction');
INSERT INTO `conditions` VALUES (23, 1377, 11, 0, 0, 14, 0, 50371, 0, 0, 0, 0, '', 'Activate Phase - If Player NHCR Quest');
INSERT INTO `creature` VALUES (2461706708, 128607, 1, 1377, 3077, 1, 1, '', 0, 0, -6468.42, -217.66, 4.90634, 6.23745, 300, 0, 0, 1039267, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` VALUES (12936348, 128607, 1817, 1377, 3077, 1, 1, '', 0, 0, -6467.53, -219.91, 5.90872, 2.20993, 180, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `smart_scripts` VALUES (128607, 0, 1, 0, 62, 0, 100, 0, 21720, 1, 0, 0, 28, 255152, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Change Legion');
INSERT INTO `smart_scripts` VALUES (128607, 0, 2, 0, 62, 0, 100, 0, 21720, 1, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Close');
INSERT INTO `smart_scripts` VALUES (128607, 0, 3, 0, 62, 0, 100, 0, 21720, 1, 0, 0, 62, 1817, 0, 0, 0, 0, 0, 7, 0, 0, 0, -6467.53, -219.91, 5.90872, 2.20993, 'ReturnTeleLegion');
INSERT INTO `smart_scripts` VALUES (128607, 0, 4, 0, 62, 0, 100, 0, 21720, 1, 0, 0, 75, 129809, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Change Phase Blasted Lands');
INSERT INTO `smart_scripts` VALUES (128607, 0, 5, 0, 62, 0, 100, 0, 21720, 0, 0, 0, 75, 255152, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Change Phase Blasted Lands');
INSERT INTO `smart_scripts` VALUES (128607, 0, 6, 0, 62, 0, 100, 0, 21720, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Close');
INSERT INTO `smart_scripts` VALUES (128607, 0, 7, 0, 62, 0, 100, 0, 21720, 0, 0, 0, 62, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, -6467.53, -219.91, 5.90872, 2.20993, 'ReturnTeleLegion');
```

in player_special.cpp
```

class quest_silithius_110 : public PlayerScript
{
public:
    quest_silithius_110() : PlayerScript("quest_silithius_110") {}


    void OnUpdate(Player* player, uint32 diff) override
    {
        if ((player->GetQuestStatus(49982) == QUEST_STATUS_INCOMPLETE) || (player->GetQuestStatus(49982) == QUEST_STATUS_COMPLETE) || (player->GetQuestStatus(49981) == QUEST_STATUS_COMPLETE) || (player->GetQuestStatus(49981) == QUEST_STATUS_INCOMPLETE) || (player->GetQuestStatus(49981) == QUEST_STATUS_REWARDED) || (player->GetQuestStatus(49982) == QUEST_STATUS_REWARDED))
        {
            if (!player->HasAura(255152))
            {
                if (player->GetMapId() == 1 && player->GetCurrentZoneID() == 1377)
                {
                    player->TeleportTo(1817, -6467.526f, -219.9097f, 5.90872f, 2.209932f);
                    
                }
            }
        }
        if ((player->GetQuestStatus(50056) == QUEST_STATUS_COMPLETE))
            if (player->GetTeam() == ALLIANCE)
                    if (player->GetDistance(-7536.31f, 1774.1f, 1062.08f) >= 20.0f)
                    {
                        player->TeleportTo(1817, -7536.31f, 1774.1f, 1062.08f, 2.161f);

                    }
        if ((player->GetQuestStatus(50300) == QUEST_STATUS_COMPLETE))
            if (player->GetTeam() == HORDE)
                if (player->GetDistance(-7544.08f, 1778.5f, 1007.86f) >= 20.0f)
                {
                    player->TeleportTo(1817, -7544.08f, 1778.5f, 1007.86f, 5.383f);

                }
    }
};

new quest_silithius_110();
```

**Comment by dufernst** [comment]
Thanks for sharing, I'll take a look at this as soon as I have time :)

**Comment by yudian1944** [comment]
@Elgrimm Man con esto funciona la opción de zidormi de retroceder el tiempo para atrás  porque como está actualmente antes de aplicar esto eso no funciona y una vez que matas a Argus la zona fasea y  las misiones  que tengas que hacer en una fase anterior de la zona quedan  imposibles de hacer

**Comment by Elgrimm** [comment]
@yudian1944 I don't quite understand you. I made the phases so that they do not apply to the old silithu, and all NPCs and objects are transferred to another map 1817 and when taking the story quest to Silithus Rana, you can already get into Silithus of the present or the past.

**Comment by Elgrimm** [comment]
If you have started quests related to Silithius wound, then you need to complete the quest to get to the old Silithius.

**Comment by Elgrimm** [comment]
Today I will check Argus and what phase he sets, but in general, when you kill Argus and get to the capital of the horde or Alliance, a quest becomes available that opens a new Silithius.

**Comment by Elgrimm** [comment]
@yudian1944 After Argus, the phase does not change.... I don't understand what your problem is?

**Comment by yudian1944** [comment]
> Hoy comprobaré a Argus y qué fase establece, pero en general, cuando matas a Argus y llegas a la capital de la horda o Alianza, una misión está disponible que abre un nuevo Silithius.

eso a ese es el cambio que me refiero  no me acordaba que el faseo era al tomar la misión

**Comment by Elgrimm** [comment]
If you have taken the quest "To see everything with your own eyes" or it is completed, but not passed, then yes you will be thrown back to the phase where the new silithius.

**Comment by Elgrimm** [comment]
@yudian1944 I have not added a couple of lines on zidormi, I will add today.

**Comment by Elgrimm** [comment]
INSERT INTO `conditions` VALUES (15, 21720, 0, 0, 1, 8, 0, 50371, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 0, 0, 1, 22, 0, 1817, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 1, 0, 0, 22, 0, 1, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 1, 0, 0, 8, 0, 49977, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 1, 0, 1, 22, 0, 1, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 1, 0, 1, 8, 0, 50371, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 0, 0, 0, 8, 0, 49977, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (15, 21720, 0, 0, 0, 22, 0, 1817, 0, 0, 0, 0, '', NULL);

**Comment by Elgrimm** [comment]
UPDATE `creature_template` SET `gossip_menu_id`=21720 WHERE `entry`=128607;

**Comment by Elgrimm** [comment]
@yudian1944 By Zidormi all fixes

**Comment by yudian1944** [comment]
Estas consurtas me dan error 
UPDATE `creature` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10277);
UPDATE `creature` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10435);
UPDATE `creature` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10436);
UPDATE `gameobject` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10277);
UPDATE `gameobject` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10436);
UPDATE `gameobject` SET `map`=1817 WHERE (`map`=1 AND `PhaseId`=10435);
DELETE FROM `condition` WHERE `SourceGroup`=1377;
INSERT INTO `conditions` VALUES (23, 1377, 3, 0, 1, 12, 0, 86, 0, 0, 1, 0, '', 'True If Event Active');
INSERT INTO `conditions` VALUES (23, 1377, 15, 0, 0, 14, 0, 50300, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 13, 0, 0, 14, 0, 50373, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 12, 0, 0, 14, 0, 50360, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 11, 0, 0, 14, 0, 49977, 0, 0, 0, 0, '', 'Activate Phase - If Player NHCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 2, 0, 1, 12, 0, 86, 0, 0, 1, 0, '', 'True If Event Active');
INSERT INTO `conditions` VALUES (23, 1377, 14, 0, 0, 14, 0, 50056, 0, 0, 1, 0, '', 'Activate Phase - If Player HCR Quest');
INSERT INTO `conditions` VALUES (23, 1377, 2, 0, 0, 6, 0, 67, 0, 0, 0, 0, '', 'True If Player has Horde Faction');
INSERT INTO `conditions` VALUES (23, 1377, 3, 0, 0, 6, 0, 469, 0, 0, 0, 0, '', 'True If Player has Alliance Faction');
INSERT INTO `conditions` VALUES (23, 1377, 11, 0, 0, 14, 0, 50371, 0, 0, 0, 0, '', 'Activate Phase - If Player NHCR Quest');
INSERT INTO `creature` VALUES (2461706708, 128607, 1, 1377, 3077, 1, 1, '', 0, 0, -6468.42, -217.66, 4.90634, 6.23745, 300, 0, 0, 1039267, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` VALUES (12936348, 128607, 1817, 1377, 3077, 1, 1, '', 0, 0, -6467.53, -219.91, 5.90872, 2.20993, 180, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

[Errores.txt](https://github.com/dufernst/LegionCore-7.3.5/files/10714528/Errores.txt)

**Comment by yudian1944** [comment]
Este valor de guid 2461706708 me causo crach en world server creo que es demasiado alto por si a alguien le sucede igual que lo cambie

**Comment by yudian1944** [comment]
He probado esto y falta algo al comenzar las misiones de silithus después de matar a argus  cuando llegas a la zona se encuentra faseada hasta ahí esta bien pero los npc no se pueden ver  
![WoWScrnShot_021123_164931](https://user-images.githubusercontent.com/34819144/218282664-82044cda-9de2-480d-b2ea-b86af342f2fe.jpg)

**Comment by Elgrimm** [comment]
UPDATE `creature` SET `PhaseId`=0 WHERE (`map`=1817 AND `PhaseId`=10277);
This phase is no longer needed as all creatures are transferred to another ID card, which becomes available when the player completes the quest.

**Comment by yudian1944** [comment]
> CONJUNTO DE ACTUALIZACIÓN =0 DONDE (=1817 Y =10277); Esta fase ya no es necesaria ya que todas las criaturas se transfieren a otra tarjeta de identificación, que estará disponible cuando el jugador complete la misión.`creature``PhaseId``map``PhaseId`
Con esto ya se pueden ver todos los npc, ya probe la cadena de misiones  con un jugador alianza y se puede completar, pero con la de la horda la misión id:50300 tiene problemas, al hablar con el npc que te transporta para el barco  este te transporta  pero no para la parte en que esta magni  y no te deja moverte. Muestra (https://youtu.be/4i6x0-yp8ho)

**Comment by yudian1944** [comment]
Para que la mision 50300 sea pueda completar debe corregir las coordenadas del script en la parte de la horda 

      --  if ((player->GetQuestStatus(50300) == QUEST_STATUS_COMPLETE))  
          -- if (player->GetTeam() == HORDE)
                 --if (player->GetDistance(-7544.08f, 1778.5f, 1007.86f) >= 20.0f)
                -- {
                 --    player->TeleportTo(1817, -7544.08f, 1778.5f, 1007.86f, 5.383f);
 
                -- }
    -- }
 --};

++if ((player->GetQuestStatus(50300) == QUEST_STATUS_COMPLETE))
            ++if (player->GetTeam() == HORDE)
                ++if (player->GetDistance(-7546.53f, 1791.53f, 1057.42f) >= 20.0f)
                ++{
                   ++ player->TeleportTo(1817, -7546.53f, 1791.53f, 1057.42f, 5.064f);

               ++ }
   ++ };

UPDATE `creature_template` SET `AIName` = SmartAI WHERE `entry` = 133388;

**Comment by Elgrimm** [comment]
@yudian1944 Why change them? These coordinates were a little higher than the ship in case the player did not have time to load the texture and he starts to fall... If you changed the coordinates here, then the flights where you accept this quest should also change them to these coordinates so that he sends them.

**Comment by Elgrimm** [comment]
The coordinates are correct, I have not yet thrown off just fixes for this quest.

**Comment by Elgrimm** [comment]
DELETE FROM `smart_scripts` WHERE (`entryorguid`=132140 AND `sourcetype`=0);
INSERT INTO `smart_scripts` VALUES (132140, 0, 0, 1, 62, 0, 100, 0, 22143, 0, 0, 0, 33, 132140, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'GS - KC');
INSERT INTO `smart_scripts` VALUES (132140, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 62, 1817, 0, 0, 0, 0, 0, 7, 0, 0, 0, -7544.08, 1778.5, 1007.86, 5.383, 'L - TP');
DELETE FROM `smart_scripts` WHERE (`entryorguid`=132995 AND `sourcetype`=0);
INSERT INTO `smart_scripts` VALUES (132995, 0, 0, 1, 62, 0, 100, 0, 22129, 0, 0, 0, 33, 132995, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'GS - KC');
INSERT INTO `smart_scripts` VALUES (132995, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 62, 1817, 0, 0, 0, 0, 0, 7, 0, 0, 0, -7536.31, 1774.1, 1062.08, 2.161, 'L - TP');

INSERT INTO `smart_scripts` VALUES (133387, 0, 3, 0, 20, 0, 100, 0, 50057, 0, 0, 0, 62, 1817, 0, 0, 0, 0, 0, 7, 0, 0, 0, -6421.17, 180.337, 8.588, 4.91, 'L - ICS');
INSERT INTO `smart_scripts` VALUES (133388, 0, 3, 0, 20, 0, 100, 0, 50057, 0, 0, 0, 62, 1817, 0, 0, 0, 0, 0, 7, 0, 0, 0, -7254.98, 332.338, 23.177, 5.834, 'L - ICS');

UPDATE creature_template SET AIName = SmartAI WHERE entry = 133388;
UPDATE creature_template SET AIName = SmartAI WHERE entry = 133387;

**Comment by Elgrimm** [comment]
In the source code, the coordinates are correct, just upload these lines to the database.

**Comment by qqwqqwe** [comment]
Good

**Comment by dufernst** [comment]
Keeping this one open till I have had the time to get it into the main branch.

**Comment by Elgrimm** [comment]
@dufernst ok. In the near future I will download the github application so that I can normally add it to the pull requests section.

**Comment by hiyoo11** [comment]
INSERT INTO `creature` VALUES (2461706708, 128607, 1, 1377, 3077, 1, 1, '', 0, 0, -6468.42, -217.66, 4.90634, 6.23745, 300, 0, 0, 1039267, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
Why use such a huge guid？it causes the program to use more memory.

**Comment by Elgrimm** [comment]
> INSERT INTO `creature` VALUES (2461706708, 128607, 1, 1377, 3077, 1, 1, '', 0, 0, -6468.42, -217.66, 4.90634, 6.23745, 300, 0, 0, 1039267, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0); Why use such a huge guid？it causes the program to use more memory.

You can put any free value in the guid. I put what I have available in order. So, the ones below are already occupied with events and other creatures! And if you can’t run a server with more creatures than 1000000000, then what’s the point of running it?
