### ISSUE TITLE
Gunship_battle dont work!

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#137]
There are no scripts in the source code. Icecrown Citadel

**Comment by yudian1944** [comment]
@Elgrimm These scripts are in Trinity Core so you have to know how to adapt them to this code

**Comment by Elgrimm** [comment]
yes

**Comment by Elgrimm** [comment]
trinity core bad fix

**Comment by Elgrimm** [comment]
my fix good =)
