### ISSUE TITLE
Cazador talento id: 155228 [Lobo solitario] bug

### ISSUE THREAD

**Issue by yudian1944** [dufernst/LegionCore-7.3.5#139]
![WoWScrnShot_030423_112407](https://user-images.githubusercontent.com/34819144/222919131-e4bae864-42f1-49fc-ab92-4d7cc511106a.jpg)
Función: Cuando escoges este talento tu daño aumenta un 18% pero a cambio dejas de invocar a tu mascota.
Error: Cuando tienes el talento activo puedes usar [Domesticar bestia]id:1515, Domesticar una nueva mascota y seguir usándola.

**Comment by Elgrimm** [comment]
add PlayerScripts 
void OnUpdate(Player* player, uint32 diff) override
    {
        if (player->HasSpell(155228))
                {
                     player->RemoveAurasDueToSpell(1515);
                }
    }

**Comment by Elgrimm** [comment]
@yudian1944 
class playerScriptLearnAndRemoveNew : public PlayerScript
{
public:
    playerScriptLearnAndRemoveNew () : PlayerScript("playerScriptLearnAndRemoveNew ") { }

void OnUpdate(Player* player, uint32 diff) override
{
if (player->HasSpell(155228))
{
player->RemoveAurasDueToSpell(1515);
}
}
};

**Comment by Elgrimm** [comment]
in ->
void AddSC_player_special_scripts()
{
new playerScriptLearnNew();
...........
};

**Comment by yudian1944** [comment]
@Elgrimm donde  añado todas estas líneas  no me especificaste.

**Comment by yudian1944** [comment]
> in -> void AddSC_player_special_scripts() { new playerScriptLearnNew(); ........... };

Deberia ser asi: new playerScriptLearnAndRemoveNew();

**Comment by yudian1944** [comment]
Ya añadí las líneas,  y con el talento no deja domesticar nuevas mascotas pero el problema no  viene solo por ahí, también sucede que cuando corregimos el issue #131 al modificar estas líneas :
**`void Spell::EffectSummonDeadPet(SpellEffIndex /*effIndex*/)
{...
Pet* pet = player->GetPet();
  --  if (!pet)
++ if (pet && pet->isAlive())
 ++       return;
-- return;

--    if (pet->isAlive())
--        return;
if (damage < 0)
        return;

    float x, y, z;
    player->GetPosition(x, y, z);
++ if (!pet)
 ++   {
     ++   player->SummonPet(0, x, y, z, player->GetOrientation(), SUMMON_PET, 0);
   ++     pet = player->GetPet();
  ++  }
 ++   if (!pet)
    ++    return;
player->GetMap()->CreatureRelocation(pet, x, y, z, player->GetOrientation());`*

Spell Id: 982 [Revivir mascota] ahora está invocando  la mascota, o sea está haciendo la función de (llamar a mascota)

**Comment by Elgrimm** [comment]
@yudian1944 You can register in playerscript
in \src\server\scripts\World\player_special.cpp
........
+ class playerScriptLearnAndRemoveNew : public PlayerScript
+ {
+ public:
+ playerScriptLearnAndRemoveNew () : PlayerScript("playerScriptLearnAndRemoveNew ") { }

+ void OnUpdate(Player* player, uint32 diff) override
+ {
+ if (player->HasSpell(155228))
+ {
+ player->RemoveAurasDueToSpell(1515);
+ player->RemoveAurasDueToSpell(982);
+ }
+ }
+ };
void AddSC_player_special_scripts()
{
.....
+ new playerScriptLearnNew();
...........
};

**Comment by Elgrimm** [comment]
This repository is abandoned, apparently I will make a new branch soon and I will fix it there already

**Comment by Elgrimm** [comment]
@yudian1944 
void AddSC_player_special_scripts()
{
.....

- new playerScriptLearnNew();
- + new playerScriptLearnAndRemoveNew();
...........
};

**Comment by yudian1944** [comment]
Ya lo he hecho pero aún sigue sin funcionar te dejo un video para que veas donde está el problema https://youtu.be/GgRMBHyfcW0

**Comment by Elgrimm** [comment]
@yudian1944 
-- void OnUpdate(Player* player, uint32 diff) override
++ void OnSpellLearned(Player* player, uint32 spellID) override
{

-- if (player->HasSpell(155228))
++ if (spellID == 155228)

{

-- player->RemoveAurasDueToSpell(1515);
++ player->removeSpell(1515);
-- player->RemoveAurasDueToSpell(982);
++ player->removeSpell(982);

}

}

};
void AddSC_player_special_scripts()

**Comment by yudian1944** [comment]
@funciona pero al relogear el cliente los hechizos 1515 y 982 vuelven a estar disponibles y se pueden seguir utilizando con el talento.

**Comment by Elgrimm** [comment]
@yudian1944 ok, Changing the code by adding the update function

**Comment by Elgrimm** [comment]
void OnSpellLearned(Player* player, uint32 spellID) override
{
 if (spellID == 155228)
{
 player->removeSpell(1515);
 player->removeSpell(982);

}

}

void OnUpdate(Player* player, uint32 diff) override

{

if (player->HasSpell(155228))

{

player->removeSpell(1515);
 player->removeSpell(982);

}

}

};

**Comment by yudian1944** [comment]
Bueno ahora si ha quedado solucionado el uso de este bug,  gracias nuevamente @Elgrimm  por el arreglo y sierro tema.
