### ISSUE TITLE
Firebolt_Imp_NoAnimation

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#14]
Fix
src/server/game/Handlers/PetHandler.cpp 

```
 Spell* spell = new Spell(caster, spellInfo, triggerData);
+	spell->m_fromClient = true;
+	spell->m_miscData[0] = cast.Cast.Misc[0];
+	spell->m_miscData[1] = cast.Cast.Misc[1];
    spell->m_targets = targets;

    if (spellInfo->Categories.StartRecoveryCategory) // Check if spell is affected by GCD
----------------------------------------------------------------------------------------------
  if (p->getPetType() == SUMMON_PET && (urand(0, 100) < 10))
                    pet->SendPetTalk(static_cast<uint32>(PET_TALK_SPECIAL_SPELL));
                else
                    pet->SendPetAIReaction(cast.PetGUID);
            }
        }

+		WorldPackets::Spells::SpellPrepare spellPrepare;
+		spellPrepare.ClientCastID = cast.Cast.SpellGuid;
+		spellPrepare.ServerCastID = spell->m_castId;
+		SendPacket(spellPrepare.Write());

        spell->prepare(&(spell->m_targets));
    }
```
------------------------------------------------------------------------------------------------
```
 TriggerCastData triggerData;
            Spell* spell = new Spell(pet, spellInfo, triggerData);
            spell->preparePetCast(&(spell->m_targets), unit_target, pet, petGuid, GetPlayer());
+			spell->m_targets.SetUnitTarget(unit_target);
+			spell->prepare(&(spell->m_targets));

            break;

src/server/game/Spells/Spell.cpp

m_skipCheck(triggerData.skipCheck), m_spellMissMask(0), m_auraScaleMask(0), m_currentExecutedEffect(SPELL_EFFECT_NONE)
{
+	m_fromClient = false;

    if (!m_castedTime)
```

-------------------------------------------------------------------
```
-           if ((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell)

+    if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell) && !m_fromClient)
```

--------------------------------------------------------------------------
```
-                     if ((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell)
+                    if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell) && !m_fromClient)

        castFlags |= CAST_FLAG_PENDING;

src/server/game/Spells/Spell.h

uint32 m_miscData[2];

+		ObjectGuid m_castId;
+		bool m_fromClient;


        ObjectGuid m_spellGuid;
```

**Comment by Elgrimm** [comment]
it was a little impossible to show which lines are replaced here = (

**Comment by Elgrimm** [comment]
--       if ((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell)
replaced by
if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell) && !m_fromClient)

**Comment by Elgrimm** [comment]
spell->preparePetCast(&(spell->m_targets), unit_target, pet, petGuid, GetPlayer());
replace by
spell->m_targets.SetUnitTarget(unit_target);
			spell->prepare(&(spell->m_targets));
and
if ((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell)
replace by 
if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell() && !m_spellInfo->HasAttribute(SPELL_ATTR4_TRIGGERED)) || m_triggeredByAuraSpell) && !m_fromClient)


it's in PetHandler.cpp and Spell.cpp
![Новый точечный рисунок](https://user-images.githubusercontent.com/36525398/115145351-c5714380-a059-11eb-9481-0b209196d9d0.jpg)

**Comment by Elgrimm** [comment]
![Новый точечный рисунок](https://user-images.githubusercontent.com/36525398/115145390-f05b9780-a059-11eb-87d9-98c8c790530f.jpg)

**Comment by dufernst** [comment]
You can use triple ` to indicate a code block in Github :)
I formatted your first post for you.

**Comment by dufernst** [comment]
Could you talk me through why this is the way to fix this particular issue?
It seems a bit like a significant hack to solve the animation of one spell for one pet?

Or is this an issue for all pets?

By the way, thank you very much for going out of your way to contribute, very much appreciated!

**Comment by Elgrimm** [comment]
This problem is only with the pets of the warlock, specifically with the Imp. This code solves this problem for them. The rest of the animation is fine.

**Comment by dufernst** [comment]
Thanks for the clarification, unfortunately it will be a couple of weeks before I have enough time to take a closer look at these issues.
Currently have some more urgent things to finish up as well, for example the WoD garrisons.

**Comment by Elgrimm** [comment]
With world quests, too, not everything is in order, there not everyone has a task completion time and, accordingly, not all are updated ... I'm looking at the essence of the problem now.

**Comment by dufernst** [comment]
90% of the world quests I had tested worked fine.
But at the moment you have to manually select them on the map.
