### ISSUE TITLE
Pets not working in Legion

### ISSUE THREAD

**Issue by Crandalius** [dufernst/LegionCore-7.3.5#142]
Hunter, Warlock, DK pets don't seem to work in legion at all. 

Nothing happens once you force it to attack

This issue only occurs in Legion alll other maps work perfectly fine

**Comment by dufernst** [comment]
That issue was fixed in the following commit:
https://github.com/dufernst/LegionCore-7.3.5/commit/460fb83de17ef3c9ce67843229f27e33a37ac31e
If not please reopen this issue.

**Comment by Crandalius** [comment]
Nope, it's still the same
