### ISSUE TITLE
problem in start broken shore q

### ISSUE THREAD

**Issue by Arshiya051** [dufernst/LegionCore-7.3.5#145]
For the broken island scenario, the player is out of the game, but the account has no problem with the Game Master rank.
Can you find the problem why the player gets out as soon as he enters the scenario?
@dufernst

**Comment by dufernst** [comment]
@Arshiya051 I am a bit confused as to what problem you are referring to?
How would I be able to reproduce this? On my side entering the scenario seems to be working just fine?

**Comment by Arshiya051** [comment]
What I mean exactly is that: he enters the scenario with an account that has the rank of Game Master and there is no problem. But with a normal account, it does not enter the scenario and disconnects.

**Comment by Arshiya051** [comment]
Create a normal account, then level up, then level 98, start the Legion quest, then start the scenario, then disconnect. please check? Then let me know if the scenario works for you or not?

**Comment by dufernst** [comment]
When I test it, gm account or normal account, it always works.
I am sorry to say that you will have to do some local debugging to see what is going on :|

**Comment by Arshiya051** [comment]
can u send here file worldserver.conf?

**Comment by Arshiya051** [comment]
@dufernst  :  I also tried repack uwow and it still has a problem. It is probably from the maps and vamps, or from the game itself, which I may have downloaded incorrectly.
logs in worldserver:
2023-05-09_01:49:12 Added aura spellid 2645, effectmask 31
2023-05-09_01:50:16 Server Population (0.001000).
2023-05-09_01:50:21 Player (guidlow 2) have problems with transport guid (25662823). Teleport to bind location.
2023-05-09_01:50:21 Added aura spellid 2645, effectmask 31
2023-05-09_01:50:21 Added aura spellid 228128, effectmask 1
2023-05-09_01:50:21   ...at loading, and will deleted in DB also
2023-05-09_01:50:21   ...at loading, and will deleted in DB also
2023-05-09_01:50:21   ...at loading, and will deleted in DB also
2023-05-09_01:50:21   ...at loading, and will deleted in DB also

**Comment by Arshiya051** [comment]
@dufernst I tested with all kinds of accounts. Only with Gamemaster account, rank 6 is ok and there is no problem.
With a normal account and even with a Game Master account, rank 1 2 3, it throws the hero out of the game. It doesn't crash. It just exits the game and then goes to the first game where you make the hero.
I also tested it with uwow repack and it's still the same.
You can give me your worldserver.conf so I can check it.

**Comment by dufernst** [comment]
Feel free to share your realmlist table data and config (with the credentials removed) then I can take a look and see if anything is wrong. But a mostly default config should work just fine, if I remember correctly all you need to do is change the database credentials. Are you certain the expansion is correctly set to 6 for all accounts? Otherwise you will be thrown out of Legion maps.

**Comment by Arshiya051** [comment]
https://s8.uupload.ir/filelink/sPzRa5KLQdnL_3cf9f51d52/auth_2zcm.sql
auth.sql full

I'm sure it's expansion 6. The problem is probably from the player.cpp part. or from the brokenshore map.

**Comment by yudian1944** [comment]
> https://s8.uupload.ir/filelink/sPzRa5KLQdnL_3cf9f51d52/auth_2zcm.sql auth.sql full @dufernst I'm sure it's expansion 6. The problem is probably from the player.cpp part. or from the brokenshore map.

Amigo prueba a desactivar  el sistema antitrampas del servidor en worldserver.conf a mí me expulsaba debido a eso.

**Comment by Arshiya051** [comment]
@yudian1944  thank you. Yes, the problem was anti-cheat. I disabled it and the problem was solved.
