### ISSUE TITLE
error trying to create a new account

### ISSUE THREAD

**Issue by kaelthasmanu** [dufernst/LegionCore-7.3.5#149]
hello guys i get this error when i go to create a new user from the trinity console

C>TC>INFO  LegionCore 2020-04-25 (Unix, Release) (worldserver-daemon) ready...
.account create anoobaccount asd
TC>ERROR Entry 1029 not found in `trinity_string` table.
<error>
TC>

**Comment by dufernst** [comment]
@kaelthasmanu sounds like something went wrong with setting up your database, if everything is correctly done you wouldn't get this error.

**Comment by kaelthasmanu** [comment]
I populated the database with the sql that is in the code and it did not return any error, I don't know what could have gone wrong

**Comment by dufernst** [comment]
Nobody else has this issue, so I am not sure what is wrong on your end :|

**Comment by qqwqqwe** [comment]
You error，you look up tc 7.35，gm command.

**Comment by yudian1944** [comment]
recuerda que el comando para crear la cuenta ya no es .account create en legión es .bnetaccount create  ej@ej.com password password (en algunos servidores es battlenetaccount create, según como este programado el comando)

**Comment by kaelthasmanu** [comment]
thanks guys the error is that @ was missing but the text that shows you the error was missing in the database
![image](https://github.com/dufernst/LegionCore-7.3.5/assets/39976595/2c362383-cf87-4914-b322-f1d94decbe20)
![image](https://github.com/dufernst/LegionCore-7.3.5/assets/39976595/24b79404-3943-4b3c-9fb7-61114a7827ff)
solved :)
