### ISSUE TITLE
Quest does not work id 43705

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#15]
Quest does not work https://www.wowhead.com/quest=43705/nobundos-last-stand
Can't talk to Nobundo Fix in DB creature_template column npcflag 3
and does not summon creatures to be killed after dialogue.

i did, but very crooked half through smart half through code

since I did not do it right at all and you can’t do it!
![Новый точечный рисунок](https://user-images.githubusercontent.com/36525398/115145575-e8e8be00-a05a-11eb-86af-bfe64cd0128f.jpg)

**Comment by dufernst** [comment]
I have taken a short look at the code, and I guess that whole scenario is currently not implemented?

**Comment by Elgrimm** [comment]
Yes. Outdoor Exodar I believe it should be implemented here in folder OutdoorPvP

**Comment by Elgrimm** [comment]
![Новый точечный рисунок](https://user-images.githubusercontent.com/36525398/115152024-1f810180-a078-11eb-8ae4-c73009fc2aaa.jpg)

**Comment by dufernst** [comment]
Those scenario's are PVE content for as far as I am aware.
Should probably be added to: `src\server\scripts\Scenario`

**Comment by welder1976** [comment]
yes src\server\scripts\Scenario
