### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by Arshiya051** [dufernst/LegionCore-7.3.5#151]
Hello. Since the server is 7.3.5 and it is possible to start the server from 7.1 through the database and word server, I wanted to know if it is not possible to start the client from 7.1.5=23420?
If possible, please advise. Thankful
@dufernst

**Comment by dufernst** [comment]
@Arshiya051 without modification of the code that would not be possible.
Practically speaking you are tied to the particular version that LegionCore supports.

**Comment by Arshiya051** [comment]
I found a way. I need win64AuthSeed code in build.info.sql. I couldn't find anything, can you help me? 7.1.5 = 23420
@dufernst 
https://s6.uupload.ir/files/15_dbf.png

**Comment by dufernst** [comment]
You could look at the source code for a 7.1.5 emulator, or look at the old commits for TrinityCore.
But adding that won't help much. There are differences between the data objects send over the wire between those versions. So at the very least some things will be broken in your 7.1.5 client.

**Comment by Arshiya051** [comment]
I'm going to move the server forward step by step. I have to check this item for experience and test. I looked in the commits and did not find the code. I also checked many client codes, but I could not understand the code inside SQL Build Info with the client. If you can help me and find win64AuthSeed(7.1.5 = 23420) code for me. Thankful. I check here every 30 minutes.
@dufernst

**Comment by Arshiya051** [comment]
It is interesting for 3.3.5, 2.4.3 and 1.12.1.
I want to know how to get this code that is related to the client?
https://s6.uupload.ir/files/16_w0iv.png
https://s6.uupload.ir/files/17_jot7.png
@dufernst

**Comment by dufernst** [comment]
For what do you need these?

**Comment by Arshiya051** [comment]
I said it was for a test. I want to see if I can run the server first with 7.1.5 client, then with 7.2.5 and then with 7.3.5. I have the game. I tried with the 7.1.5 client, it recognized you, then it also recognized Realm, but it did not log into the account. It got stuck in the first loading. If I type this win64AuthSeed(7.1.5 = 23420) code, there is a high probability that it will enter. After it goes inside, I will test everything again to see if there is a problem or not.
@dufernst

**Comment by dufernst** [comment]
You should enable packet logging in the server and then check using the WoWPacketParser where it gets stuck.
To enable logging you have to configure a log file in the config: `PacketLogFile = something.pkt`

**Comment by Arshiya051** [comment]
Hello. Unfortunately, I could not find the client code with WowPacketParser. In the log, it gives the error related to the client. It says that the client is not allowed to enter. This way, as I understood, all the codes of 7.3.5 clients are entered into the build info, and for this reason, by entering the codes related to 7.3.5 clients, for example (26124, 26365, 26654, 26822, 26899 , 26972) You can enter the game with all these clients. Now, if I can find and enter the client codes for 7.1 and 7.2, I can enter the game. Now, if you can correct or find these codes for me, I would be grateful. Because I couldn't do it myself.
@dufernst

**Comment by qyh214** [comment]
This may be a bit difficult because each version of the update will also be accompanied by API adjustments, addressing changes in opcodes, and changes in functionality
In this project, it was actually developed based on the last build of 7.3.5 and achieved progressive updates similar to Open 7.1, 7.2, and 7.3 through database

**Comment by Arshiya051** [comment]
So how is it available for 2.4.3 and 3.3.5 and 1.12.1 clients?
https://s6.uupload.ir/files/16_w0iv.png
There must be a way to fix this code, if you need a 7.1.5 client. I have. I will upload it, check it.

https://mega.nz/42f2ed34-eb3d-41a0-ab04-07b15dfe6382        7.1.5 for Stormcore
https://uupload.ir/view/world.of.warcraft.legion.v7.1.5_lyr7.rar/    7.1.5 for wowcore 

I can also provide the complete link of Wow 7.1.5 if you need it.
@qyh214 
@dufernst

**Comment by Arshiya051** [comment]
I spent all day looking for win64AuthSeed code for 7.1.5 = 23420. But I could not fix or find this code. Please, if you can, help me and fix this code for me. Only win64AuthSeed is enough.
@dufernst
@qyh214

**Comment by Arshiya051** [comment]
In order to change the client version, which files should I edit?
  I want the asthma files. I don't like it to be incomplete, that's why I'm asking.
@dufernst
