### ISSUE TITLE
CMS Sait

### ISSUE THREAD

**Issue by Arshiya051** [dufernst/LegionCore-7.3.5#153]
What is your suggested cms to build this source and database site?
@dufernst

**Comment by Arshiya051** [comment]
How to install aowow? I did not understand at all. Please make an easy tutorial. Thankful
@dufernst 
@LordJZ
@Sarjuuk

**Comment by dufernst** [comment]
I have a repository with very poor 7.3.5 support.
https://github.com/dufernst/aowow/commits/master
This is not really fit for production and requires a lot of manual work to make it work.

So for now nothing I can give instructions on.

**Comment by Arshiya051** [comment]
I installed FusionCMS with wamp server, but I encountered an emulators error related to the source. Can't you try and make or update a suitable emulator for the source?
https://github.com/FusionWowCMS/FusionCMS
@dufernst

**Comment by dufernst** [comment]
Theoretically I could, but I won't be, I only provide limited support if I have time and this would be perfect for someone else making use of this source to contribute.

**Comment by Arshiya051** [comment]
I tried myself but I could not. There is a problem in Armory and entering the account profile. Otherwise, the site will be created and the account will be created, but the created account will not enter the site.
Work on this CMS whenever you can. And share. Thankful. I am waiting for your answer.
@dufernst
