### ISSUE TITLE
Need displayID Gameobject 248831

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#154]
Gameobject 248831 need displayid

**Comment by Elgrimm** [comment]
https://www.wowhead.com/ru/object=248831/%D0%BF%D0%B0%D0%BD%D1%86%D0%B8%D1%80%D1%8C-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8F-%D0%B7%D0%B5%D0%BC%D0%BB%D0%B8#contains

**Comment by Arshiya051** [comment]
world > gameobject_template :
(258947,5,37943,'Appearance of the Earth Guardian\'s Shell','','','',0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','',0,0,0,0,0,0,0,0,0,0,1),
(37843 > displayId)
(259067,5,37948,'Appearance of the Earth Guardian\'s Shell','','','',0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','',0,0,0,0,0,0,0,0,0,0,1),
(37948 > displayId)
