### ISSUE TITLE
Exception thrown: read access violation. this->m_stmt->bind was nullptr.

### ISSUE THREAD

**Issue by SoongXiaoTong** [dufernst/LegionCore-7.3.5#159]
hi Team,
sorry to trouble your time. but I have no idea what is the root issue. when I running the server, will get below error. but complie can be successful, just will get error when running the server both of release and debug. should I can get your help or some idea? thanks.

Core: newest source code complie with no error.
DB: Mysql 5.6.51
BOOT:boost_1_64_0

![image](https://github.com/dufernst/LegionCore-7.3.5/assets/113569749/89ca7a30-cdfe-4389-b92c-cf5bddac7b03)

**Comment by SoongXiaoTong** [comment]
seems like the issue come from connection of mysql, but I have no idea what happened as I used the recommand version of mysql.
tryed make database used "latin1 -- cp1252 West European" and "utf8 -- UTF-8 Unicode", also have this issue.
is there anything need correct?

**Comment by SoongXiaoTong** [comment]
add a condition to skip the nullptr bind, the error has been gone. but still not sure what else will be take effect after skip that.

**Comment by dufernst** [comment]
> hi Team, sorry to trouble your time. but I have no idea what is the root issue. when I running the server, will get below error. but complie can be successful, just will get error when running the server both of release and debug. should I can get your help or some idea? thanks.
> 
> Core: newest source code complie with no error. DB: Mysql 5.6.51 BOOT:boost_1_64_0
> 
> ![image](https://private-user-images.githubusercontent.com/113569749/273449490-89ca7a30-cdfe-4389-b92c-cf5bddac7b03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3Mjk4MzgsIm5iZiI6MTcwMjcyOTUzOCwicGF0aCI6Ii8xMTM1Njk3NDkvMjczNDQ5NDkwLTg5Y2E3YTMwLWNkZmUtNDM4OS1iOTJjLWNmNWJkZGFjN2IwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxMjI1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODdjMWIxZDE4M2E1Njk2NjExNDFkZDAxNWQzMDFmODg0ZTZkODI0ZmRlZTA4MDg2NTYwZTBlMGNkZDA4YmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g5f3WUKMHQAvSShoyukDP-XuYg1v8Kr510jGl5gQDiw)

Could you share the full stacktrace then maybe it would be possible to see what is going wrong.

**Comment by dufernst** [comment]
@SoongXiaoTong I assume you have already managed to resolve this? If not feel free to reopen.
