### ISSUE TITLE
World quests are not accepted

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#16]
On the territory of Azsuna, world quests where you need to kill one creature work fine, and all the rest are shown on the map, but they are not taken!

**Comment by Elgrimm** [comment]
Perhaps this problem is solved through the Database, since the problem is only in the Azsuna location.

**Comment by dufernst** [comment]
I think you can manually take the world quests by clicking on their icon on the map?
But if you want to fix this you can take a look at this trinitycore pull request:
https://github.com/TrinityCore/TrinityCore/pull/25584/

And specifically:
https://github.com/TrinityCore/TrinityCore/pull/25584/files#diff-59e59afabb9e07b951f9cd43dc7ef08e8c894b2aa889ae394fc4ace2eef09242R10378

**Comment by eddydjcuba** [comment]
im having the same mistake what should i do ?
