### ISSUE TITLE
cmake遇到问题，跟openssl相关的

### ISSUE THREAD

**Issue by miaolin1993** [dufernst/LegionCore-7.3.5#160]
系统版本: ubuntu22.04
cmake: 3.18.4, 之前是最新版，但报错，就按着文档降级了
openssl：1.0.2， 之前是最新版但报错，就按文档降级了

但现在还是报错，完整日志如下：
`
wower@VM-8-2-ubuntu:~/code/LegionCore-7.3.5/build$ cmake ../
CMake Deprecation Warning at CMakeLists.txt:18 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:20 (cmake_policy):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (libdw) does
  not match the name of the calling package (Backward).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/macros/FindBackward.cmake:57 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR) 
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (libbfd)
  does not match the name of the calling package (Backward).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/macros/FindBackward.cmake:68 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR) 
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (libdwarf)
  does not match the name of the calling package (Backward).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/macros/FindBackward.cmake:83 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR) 
-- WARNING - Missing repository tags - you may need to pull tags with git fetch -t
-- WARNING - Continuing anyway - note that the versionstring will be set to 0000-00-00 00:00:00 (Archived)

* LegionCore
* LegionCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes - "hierarchical"

Boost 1.64 found.
Found Boost components:
   system;filesystem;thread;program_options;iostreams;regex
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
CMake Error at cmake/macros/FindOpenSSL.cmake:211 (list):
  list GET given empty list
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)

CMake Error at cmake/macros/FindOpenSSL.cmake:212 (list):
  list GET given empty list
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)

CMake Error at cmake/macros/FindOpenSSL.cmake:213 (list):
  list GET given empty list
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)

CMake Error at cmake/macros/FindOpenSSL.cmake:214 (list):
  list GET given empty list
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)

CMake Error at cmake/macros/EnsureVersion.cmake:76 (MATH):
  MATH cannot parse the expression: "..`*10000 + ..`*100 + 0": syntax error,
  unexpected exp_TIMES (4).
Call Stack (most recent call first):
  cmake/macros/EnsureVersion.cmake:111 (NORMALIZE_VERSION)
  cmake/macros/FindOpenSSL.cmake:232 (ENSURE_VERSION_RANGE)
  dep/openssl/CMakeLists.txt:16 (find_package)

CMake Error at cmake/macros/FindOpenSSL.cmake:234 (message):
  TrinityCore needs OpenSSL version 1.0 but found version ..`
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/wower/code/LegionCore-7.3.5/build/CMakeFiles/CMakeOutput.log".
wower@VM-8-2-ubuntu:~/code/LegionCore-7.3.5/build$ 

`

求大佬们帮看下

**Comment by miaolin1993** [comment]
自己解决了，首先是把cmake升级到了3.9，之后发现找寻的openssl路径不对，手动指定了一下openssl路径就好了

**Comment by muchiiun** [comment]
老哥你参照哪里的文档安装的，方便贴一下文档地址吗

**Comment by miaolin1993** [comment]
@muchiiun 没有完全是配这个项目的文档，我看的就是readme那个，那个文档大概的流程是没问题的，就是依赖版本有些不一样，我看源码里cmake写的是需要3.9的，我目前cmake3.9 openssl1.0.2 boost1.64 前面的报错都解决了，mysql好像说是需要5.7，我从8降下来之后现在还是报错，还在研究中

**Comment by muchiiun** [comment]
老哥方便加下联系方式吗，请教下

**Comment by miaolin1993** [comment]
@muchiiun miaolin_1993
