### ISSUE TITLE
编译时遇到mysql类型问题

### ISSUE THREAD

**Issue by miaolin1993** [dufernst/LegionCore-7.3.5#161]
报错日志在下图：
ubuntu22.04
cmake3.9
openssl1.0.2
boost1.64.0
mysql  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

前面几个依赖的问题都处理好了，再次make又出现这几个错误

![image](https://github.com/dufernst/LegionCore-7.3.5/assets/31845185/fc2303cb-19f9-4158-858f-633c1e3f13c5)

看报错的文件源码是有这个
![image](https://github.com/dufernst/LegionCore-7.3.5/assets/31845185/bb3af5ed-789b-4b25-9071-d762206bf360)

没学过c++不是很懂这代码干啥的，看样子像是哪个依赖版本有问题

有大佬知道原因吗

**Comment by qqwqqwe** [comment]
no mysql 8.0，5.6&amp;5.7



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 凌晨1:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dufernst/LegionCore-7.3.5] 编译时遇到mysql类型问题 (Issue #161)




 
报错日志在下图：
 ubuntu22.04
 cmake3.9
 openssl1.0.2
 boost1.64.0
 mysql  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
 
前面几个依赖的问题都处理好了，再次make又出现这几个错误
 

 
看报错的文件源码是有这个
 
 
没学过c++不是很懂这代码干啥的，看样子像是哪个依赖版本有问题
 
有大佬知道原因吗

**Comment by miaolin1993** [comment]
@qqwqqwe 非常感谢收到您的回复，我尝试吧mysql版本降级到了5.7，出现usr/include/mysql不存在的问题

于是用sudo apt-get install libmysqlclient-dev命令安装了usr/include/mysql工具

继续make编译还是同样的错误

![image](https://github.com/dufernst/LegionCore-7.3.5/assets/31845185/f67c8cba-2e19-4cb1-9a98-e34bee3ea139)

**Comment by qqwqqwe** [comment]
no need install,5.7.4 greed public



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dufernst/LegionCore-7.3.5] 编译时遇到mysql类型问题 (Issue #161)




 
@qqwqqwe 非常感谢收到您的回复，我尝试吧mysql版本降级到了5.7，出现usr/include/mysql不存在的问题
 
于是用sudo apt-get install libmysqlclient-dev命令安装了usr/include/mysql工具
 
继续make编译还是同样的错误

**Comment by qqwqqwe** [comment]
set bin，library &amp;library dir



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dufernst/LegionCore-7.3.5] 编译时遇到mysql类型问题 (Issue #161)




 
@qqwqqwe 非常感谢收到您的回复，我尝试吧mysql版本降级到了5.7，出现usr/include/mysql不存在的问题
 
于是用sudo apt-get install libmysqlclient-dev命令安装了usr/include/mysql工具
 
继续make编译还是同样的错误

**Comment by miaolin1993** [comment]
@qqwqqwe 您好

这是我的编译语句，指定了lib库和openssl的dir

`cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wower/server -DTOOLS=0 -DOPENSSL_INCLUDE_DIR=/usr/local/ssl/include -DOPENSSL_LIBRARIES=/usr/local/ssl`

从上面报错来看好像还是mysql版本有问题，我现在整体的版本是：

ubuntu 22.04
cmake 3.9
openssl 1.0.2
boost1.64.0
mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64) using  EditLine wrapper


no need install,5.7.4 greed public 这个具体是指什么呀，没理解

**Comment by qqwqqwe** [comment]
5.4.7绿色版，不用安装，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dufernst/LegionCore-7.3.5] 编译时遇到mysql类型问题 (Issue #161)




 
@qqwqqwe 您好
 
这是我的编译语句，指定了lib库和openssl的dir
 
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wower/server -DTOOLS=0 -DOPENSSL_INCLUDE_DIR=/usr/local/ssl/include -DOPENSSL_LIBRARIES=/usr/local/ssl
 
从上面报错来看好像还是mysql版本有问题，我现在整体的版本是：
 
ubuntu 22.04
 cmake 3.9
 openssl 1.0.2
 boost1.64.0
 mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64) using  EditLine wrapper
 
no need install,5.7.4 greed public 这个具体是指什么呀，没理解

**Comment by miaolin1993** [comment]
@qqwqqwe 感谢回复，是5.4.7这个版本不对吗，要改成5.6吗，我现在不知道要怎么解决上面图片里的报错

**Comment by qqwqqwe** [comment]
cmake&nbsp;well&nbsp;prompt you&nbsp;mysql&nbsp;root


来无影
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dufernst/LegionCore-7.3.5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 晚上11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dufernst/LegionCore-7.3.5] 编译时遇到mysql类型问题 (Issue #161)





 
@qqwqqwe 感谢回复，是5.4.7这个版本不对吗，要改成5.6吗，我现在不知道要怎么解决上面图片里的报错
