### ISSUE TITLE
这个项目有测试过能稳定能运行的依赖版本列表吗

### ISSUE THREAD

**Issue by miaolin1993** [dufernst/LegionCore-7.3.5#162]
如题

**Comment by miaolin1993** [comment]
就比如ubuntu22.04 需要cmake多少，openssl多少，boost多少，mysql多少这种，目前就是完全在踩坑，报错再改版本，时间成本太高了。求一个能稳定编译的环境，centos或是ubuntu都可以

**Comment by ntlf9t** [comment]
Ubuntu20.04 或者 debian11 
编译环境配置

sudo apt update && sudo apt full-upgrade -y && sudo apt install git cmake make gcc g++ clang libssl-dev libbz2-dev libreadline-dev libncurses-dev mariadb-server mariadb-client libmariadb-dev libmariadb-dev-compat


##安装boost1.64
wget -O boost_1_64_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
tar xzvf boost_1_64_0.tar.gz
cd boost_1_64_0/

./bootstrap.sh --prefix=/usr/

./b2

sudo ./b2 install

使用MariaDB编译报错修复
src/common/Database/MySQLConnection.cpp

    {
        case CR_SERVER_GONE_ERROR:
        case CR_SERVER_LOST:
// for compatibility with newer versions of MariaDB
#ifdef CR_INVALID_CONN_HANDLE
        case CR_INVALID_CONN_HANDLE:
#endif
        case CR_SERVER_LOST_EXTENDED:
        {
            m_reconnecting = true;

**Comment by Simonlamb1979** [comment]
只用过window编译，没使用过linux

**Comment by miaolin1993** [comment]
我已经编译成功了，需要稍微改下cmakelist指定下openssl路径就可以了
