### ISSUE TITLE
The search for a group takes you to the void

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#17]
When you click on Find Group on the Raid Finder contribution, and then Enter Raid takes the character into the void ...
![WoWScrnShot_042121_121750](https://user-images.githubusercontent.com/36525398/115529879-f2ad3400-a29b-11eb-9b00-8cc5c93dbc04.jpg)

**Comment by Elgrimm** [comment]
There was a similar issue with the graveyard in the Exodar by writing PlayerScript

```
[+] class player_grave_exodar : public PlayerScript
[+] {
[+] public:
[+] 	player_grave_exodar() : PlayerScript("player_grave_exodar") { }
[+] 
[+] 	std::map<ObjectGuid, uint64> timers{};
[+] 
[+] 	void OnUpdate(Player* player, uint32 diff) override
[+] 	{
[+] 
[+] 		```
[+] if (player->GetMapId() == 1624 && player->GetCurrentZoneID() == 0 && player->GetCurrentAreaID() == 0)
[+] 
[+] 			{
[+] 				player->TeleportTo(1624, -4071.420654f, -11434.146484f, -141.419647f, 1.862795f);
[+] 			}
[+] 	}
[+] 
[+] };
```
Only this will not help in the case of searching for a group, since there are the same mapid.

**Comment by dufernst** [comment]
I see you are using SoloCraft, are you certain that that is not breaking this?
The fix also seems a bit like a hack, if anything, something seems wrong with the teleport location when starting.
I haven't looked at the code yet, so I am not sure if the teleport location has to come from the database or from the DBC.
Either way this needs more research to properly fix it.

**Comment by Elgrimm** [comment]
I'll test Solocraft today, maybe he, but not likely!

**Comment by dufernst** [comment]
Yeah, you are probably right :)
But either way the current solution is not really addressing the underlying issue, whatever it may be.
So we should figure out what the real issue is.

**Comment by fluxurion** [comment]
Have you tried with another dbc files? Cuz i use this source for a while now and i use solocraft too but these problem never occurred.

**Comment by Elgrimm** [comment]
I tried to extract the dbc myself, but transfer it to the void with them, then I took the dbc from SPPV2 ready already, to transfer it to the void. Gamebuild in the table is 26972, as in bnetserver.conf Game.Build.Version = 26972

**Comment by fluxurion** [comment]
Let's check the lfg_entrances table in the world database. [Here is mine. ](https://codeshare.io/aJ0zwZ)

**Comment by dufernst** [comment]
As stated in the README you have to get the data files from here:
https://www.emucoach.com/forums/threads/new-repack-7-3-5-legion-wow-repack-wow-legion-7-3-5-repack-blizzlike-fun.6945/
Unfortunately we don't have extractors that output correct data for this source.

**Comment by Elgrimm** [comment]
lfg_entrances for some reason, it turned out to be completely empty = /

**Comment by Elgrimm** [comment]
fluxurion thanks! the problem was in this table lfg_entrance, but why it didn’t fill up with me I still didn’t understand =) I filled it in like you did and the problem was eliminated!

**Comment by fluxurion** [comment]
In that case you may have more tables without fully inserted.
