### ISSUE TITLE
Condition and phase_definition

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#171]
When creating a phase in phase_definition 
139 31 0 7895 0 0 0 16 43533 CH Quest Ph
And let's put in condition the conditions for the phase
23    139    31    0    0    28    0    43533    0    0    0    0
23    139    31    0    1    8    0    43533    0    0    0    0
23    139    31    0    0    55    0    70    0    0    0    0
23    139    31    0    1    55    0    70    0    0    0    0
Which say that the phase should occur if the quest is completed and the character’s spec is retrebution or the quest is passed and the character’s spec is.  But the phase only looks at these two conditions 
23    139    31    0    0    28    0    43533    0    0    0    0
23    139    31    0    1    8    0    43533    0    0    0    0
And what specialization the character has does not matter to her. Why is that?

**Comment by dufernst** [comment]
@Elgrimm so even if you are not in retri spec you still see the phase?
How can I test this? So far I have never had issues with phasing conditions :|

**Comment by Elgrimm** [comment]
@dufernst Now I will describe in detail what I want to do!

**Comment by Elgrimm** [comment]
@dufernst In Class Hall, paladins have NPCs in the form of Ashbringer swords of different types (Illuminated, Corrupted, Broken). They appear when completing certain quests. Also, when changing the paladin's specialization from retrebution to protection or light, NPCs should appear in the form of weapons of this specialization instead of swords.

**Comment by Elgrimm** [comment]
@dufernst https://www.wowhead.com/item=120978/ashbringer
https://www.wowhead.com/npc=110293/ - Display ID 71507
- stands in the stronghold if the quest is completed https://www.wowhead.com/ru/quest=38376/search-for-the-high-lord


https://www.wowhead.com/npc=110294/ - Display ID 71508
- stands in the stronghold if the quest is completed https://www.wowhead.com/ru/quest=43424/hero-weapon

https://www.wowhead.com/npc=110295/ - Display ID 71509
- stands in the stronghold if the quest is completed https://www.wowhead.com/ru/quest=43533/balance-of-power

https://www.wowhead.com/npc=110296/ - Display ID 71510
- stands in the stronghold if the quest is completed https://www.wowhead.com/ru/quest=42987/winner reward

**Comment by Elgrimm** [comment]
Take this npc https://www.wowhead.com/npc=110293/ - Display ID 71507
- stands in the stronghold if the quest is completed https://www.wowhead.com/ru/quest=38376/search-for-the-high-lord
- INSERT INTO `creature` (guid, id, map, zoneId, areaId, spawnMask, phaseMask, PhaseId, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, MovementType, npcflag, npcflag2, unit_flags, dynamicflags, AiID, MovementID, MeleeID, isActive, skipClone, personal_size, isTeemingSpawn, unit_flags3) VALUES (2462096817, 110293, 0, 139, 2268, 1, 1, '7894 ', 0, 0, 2395.42, -5317.33, 55.6288, 1.06729, 180, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
- INSERT INTO legion_world.phase_definitions (zoneId, entry, phasemask, phaseId, PreloadMapID, VisibleMapID, UiWorldMapAreaID, flags, comment) VALUES (139, 35, 0, '7894', 0, 0, 0, 16, '38376 CH Artefact');
- INSERT INTO `conditions` VALUES (23, 139, 35, 0, 0, 8, 0, 38376, 0, 0, 0, 0, '', 'If rewarded quest');
- INSERT INTO `conditions` VALUES (23, 139, 35, 0, 0, 55, 0, 70, 0, 0, 0, 0, '', 'If spec retrebution');
-

**Comment by Elgrimm** [comment]
SPEC_PALADIN_HOLY           = 65,
    SPEC_PALADIN_PROTECTION     = 66,
    SPEC_PALADIN_RETRIBUTION    = 70,

**Comment by dufernst** [comment]
@Elgrimm does it work if you relog after switching spec?
I could imagine it does not properly trigger phase updates on spec changes.

If it works with relogging, then that would point us to a way to fix it.

**Comment by Elgrimm** [comment]
@dufernst I changed my specialization, completely left the game, cleared the Cache and entered the game. The phase remained, but should have disappeared since the condition states that the quest must be completed and the character must have the retrebution specialization

**Comment by dufernst** [comment]
@Elgrimm I'll check it out next weekend, hopefully Friday.

**Comment by dufernst** [comment]
@Elgrimm hopefully the changes in this merge request will fix it: https://github.com/dufernst/LegionCore-7.3.5/pull/173
Let me know if it works as expected :+1:

**Comment by Elgrimm** [comment]
@dufernst I'll check today

**Comment by Elgrimm** [comment]
@dufernst Yes it works! Now you can add a condition to the spec_id of the phases! Thank you!

**Comment by dufernst** [comment]
@Elgrimm I did not find any reason to think it would have any negative effects/that it could break anything.
But I'll wait for a week with merging it just to give any potential issues with it the time to come to the surface.
Let me know if anything seems to be broken due to it then I can take a further look.

**Comment by Elgrimm** [comment]
Yes, I will let you know if something goes wrong.

**Comment by Elgrimm** [comment]
@dufernst This condition works, nothing is violated. I think we can close this topic.

**Comment by dufernst** [comment]
Great, merging 👍
