### ISSUE TITLE
Character stucked in Azsuna

### ISSUE THREAD

**Issue by ImmortalusDev** [dufernst/LegionCore-7.3.5#174]
When you enter or teleport yourself to Azsuna, you will be stucked in the zone right after. You can move, but that's all. Character cannot be teleported out.

**Comment by Elgrimm** [comment]
@ImmortalusDev This happened to me when the game client was not complete! Need full client

**Comment by ImmortalusDev** [comment]
Alright, can be

**Comment by ImmortalusDev** [comment]
@Elgrimm Do we have 26972 client?

**Comment by Elgrimm** [comment]
@ImmortalusDev https://elisgrimm.ru/WoWLegion.torrent Here the client seems to be complete, I looked at it.

**Comment by ImmortalusDev** [comment]
It needs more seeds
