### ISSUE TITLE
connection_patcher need for clinet 26124

### ISSUE THREAD

**Issue by Arshiya051** [dufernst/LegionCore-7.3.5#179]
connection_patcher need for clinet 26124
Unfortunately, I did not find any source about this client anywhere. Please help if you can.
@dufernst

**Comment by Fragrus** [comment]
Hi, most likely you need about this commit and from it you can see which patcher will be able to patch. At the Legion, he was still working.
https://github.com/TrinityCore/TrinityCore/tree/ccbe4404f1806f047c009d14ed1dea9806dd5736/src/tools/connection_patcher

**Comment by Arshiya051** [comment]
Thank you for the subscription. It helps a lot.
However, I want to find a way to create a 7.1.5 client so that there is no problem with the player.
Considering that the 7.2.5 and 7.3.5 patches are off in the world server, I need the client to be 7.1.5. With the aim of making the player experience the feeling of playing season after season.

**Comment by ReyDonovan** [comment]
it's easy) if you have time..

**Comment by Arshiya051** [comment]
OK. So I leave this issue and work on other bugs. thanks
@Fragrus
