### ISSUE TITLE
Broken Shore level requirement vs Allied Races

### ISSUE THREAD

**Issue by fluxurion** [dufernst/LegionCore-7.3.5#19]
If u want to start any allied race who starts on 1220 map id (Legion: Broken Isles) then the character will be ported out to main city.

Problem: 

There is a script which ports out low level players from broken isles, but the exception to the allied races not working.

Solution: 
Replace this line in src\server\game\Entities\Player.cpp: 
```if (m_areaId == 7999 || m_areaId == 9502)```  
to 
```if (GetAreaId() == 7999 || GetAreaId() == 9502)```

**Comment by dufernst** [comment]
@fluxurion thanks for sharing, I will take a look at this later this week.
But it looks good :+1:

**Comment by dufernst** [comment]
@fluxurion fixed in https://github.com/dufernst/LegionCore-7.3.5/commit/010a90885f91859e23498436de4a950d3054146b
thanks for providing the fix :)
