### ISSUE TITLE
Extra Backpack Slots

### ISSUE THREAD

**Issue by fluxurion** [dufernst/LegionCore-7.3.5#20]
By blizzard athentication we can get extra 4 backpackslots.

Replace this line in src/server/game/Entities/Player/Player.h

`#define INVENTORY_DEFAULT_SIZE  16`

to

`#define INVENTORY_DEFAULT_SIZE  20`

Also we should change the characters database characters table inventorySlots default value to 20.
```
ALTER TABLE `characters`
	CHANGE COLUMN `inventorySlots` `inventorySlots` TINYINT(3) UNSIGNED NOT NULL DEFAULT '20' AFTER `horn`;
```

**Comment by dufernst** [comment]
@fluxurion thanks for sharing!
Just to make certain, the client accept DEFAULT_SIZE 20 without any other changes?
We don't have to send some kind of 2FA enabled flag?

**Comment by fluxurion** [comment]
no that's working with these two changes

[Test Screenshot](https://ibb.co/sWcwTc4)

**Comment by dufernst** [comment]
Great, I'll get to this later this week then :)

**Comment by dufernst** [comment]
@fluxurion fixed in https://github.com/dufernst/LegionCore-7.3.5/commit/041611bb16f9e3f05a1852037d6944f06b1c73bc
thanks you for providing the fix :)
