### ISSUE TITLE
How to change this server version to 7.3.5 26365?

### ISSUE THREAD

**Issue by ivanup3** [dufernst/LegionCore-7.3.5#209]
I would like to know how to change the server version to 26365 or make this version shareable with my client version.

**Comment by Etoyspeh** [comment]
@ivanup3 Hi. You can do this by editing the following files
worldserver.conf
bnetserver.conf
Specifically: Game.Build.Version = 26972, for the version you need.
And also in the auth database - table realmlist, column gamebuild
