### ISSUE TITLE
In Krokun, it does not show the coordinates where the quest is being performed.

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#21]
Doesn't show Velen's location on the ridge in the quest "Alone in the Abyss" https://www.wowhead.com/quest=46938/alone-in-the-abyss
Accordingly, the rest of the quests in the chain also do not have a designation where the quest is being performed on the map.

**Comment by Elgrimm** [comment]
I understand that it is possible to set coordinates in the quest_poi and quest_poi_points tables, but I cannot figure out what to set in the quest_poi table in the blobindex and idx1 columns, which of these columns is associated with quest_poi_points and which column is idx1 or idx2 in this table?

**Comment by fluxurion** [comment]
Idx1 and idx2 are category shorts. It means you can make sub pois to the quest. For a simple poi you can leave it 0. I'll check after work what can i do..😁

**Comment by Elgrimm** [comment]
Thank

**Comment by fluxurion** [comment]
```
INSERT INTO `quest_poi` (`QuestID`, `BlobIndex`, `Idx1`, `ObjectiveIndex`, `QuestObjectiveID`, `QuestObjectID`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `WoDUnk1`, `AlwaysAllowMergingBlobs`, `VerifiedBuild`) VALUES (46938, 0, 0, -1, 0, 0, 1669, 1135, 0, 0, 0, 0, 0, 1290584, 0, 26124);

INSERT INTO `quest_poi` (`QuestID`, `BlobIndex`, `Idx1`, `ObjectiveIndex`, `QuestObjectiveID`, `QuestObjectID`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `WoDUnk1`, `AlwaysAllowMergingBlobs`, `VerifiedBuild`) VALUES (46938, 0, 1, 0, 289897, 121131, 1669, 1135, 0, 0, 0, 0, 0, 1308255, 0, 26124);

INSERT INTO `quest_poi` (`QuestID`, `BlobIndex`, `Idx1`, `ObjectiveIndex`, `QuestObjectiveID`, `QuestObjectID`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `WoDUnk1`, `AlwaysAllowMergingBlobs`, `VerifiedBuild`) VALUES (46938, 0, 2, 32, 0, 0, 1669, 1135, 0, 0, 0, 0, 0, 1305904, 0, 26124);
```

**Comment by fluxurion** [comment]
Check how many rows do you have in the quest_poi table and quest_poi_points.

I have some db for this core. I don't remember which one is from dufernst.

I have one with quest_poi: 89 357 rows, quest_poi_points: 155 010 rows

**Comment by Elgrimm** [comment]
I have quest_poi 89360 rows

**Comment by Elgrimm** [comment]
in the quest "Alone in the Abyss" yes there is a designation of the first criterion. The map shows where the first NPC is located. But the rest of the criteria are not shown there. There the second criterion is "Meet Velen on the ridge"

**Comment by Elgrimm** [comment]
No one has a quest_poi for this quest chain?

**Comment by fluxurion** [comment]
Cuz you have to port out to the ridge for meeting velen

**Comment by Elgrimm** [comment]
fluxurion do you have a Discord?
