### ISSUE TITLE
World Quest "Barrels of Fun"

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#22]
Spell script
SQL
INSERT INTO spell_script_names VALUES (230884, 'spell_gen_leg_start_round');

C++

// Start Round
// 230884
class spell_gen_leg_start_round : public SpellScriptLoader
{
public:
    spell_gen_leg_start_round() : SpellScriptLoader("spell_gen_leg_start_round") { }
 
    class spell_gen_leg_start_round_SpellScript : public SpellScript
    {
        PrepareSpellScript(spell_gen_leg_start_round_SpellScript);
 
        void After()
        {
            Unit* caster = GetCaster();
            if (!caster)
                return;
 
            if (Creature* creature = caster->SummonCreature(116459, caster->GetPositionX() + 3.f, caster->GetPositionY() - 3.f, caster->GetPositionZ(), 0.f, TEMPSUMMON_MANUAL_DESPAWN, 60000))
            {
                creature->SetOwnerGUID(caster->GetGUID());
                creature->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
            }
            if (Creature* creature = caster->SummonCreature(116459, caster->GetPositionX() - 3.f, caster->GetPositionY() - 3.f, caster->GetPositionZ(), 0.f, TEMPSUMMON_MANUAL_DESPAWN, 60000))
            {
                // 230878 fail
                // 230877 win
                creature->SetOwnerGUID(caster->GetGUID());
            }
            if (Creature* creature = caster->SummonCreature(116459, caster->GetPositionX() - 3.f, caster->GetPositionY() + 3.f, caster->GetPositionZ(), 0.f, TEMPSUMMON_MANUAL_DESPAWN, 60000))
            {
                creature->SetOwnerGUID(caster->GetGUID());
            }
 
            if (Creature* creature = caster->FindNearestCreature(116010, 30, true))
                creature->AI()->Talk(1);
        }
 
        void Register() override
        {
            AfterCast += SpellCastFn(spell_gen_leg_start_round_SpellScript::After);
        }
    };
 
    SpellScript* GetSpellScript() const override
    {
        return new spell_gen_leg_start_round_SpellScript();
    }
};

**Comment by dufernst** [comment]
@Elgrimm thanks for sharing
I will assign this issue to myself to check the code and to include it in my repo if needed.

**Comment by Elgrimm** [comment]
> @Elgrimm thanks for sharing
> I will assign this issue to myself to check the code and to include it in my repo if needed.

Have you abandoned this repository? Will it not be updated anymore?

**Comment by Elgrimm** [comment]
> My repo as in this repo :D
> No worries, I will still be updating this/my repo, just busy with other work at the moment :)

I realized. Thank you!
