### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by lbsoliver** [dufernst/LegionCore-7.3.5#24]
Hello, thanks for hosting this project on Github!

I got some problems with the database, when I import the updates I get errors because the varchar is 512.

Could u give me a little Tutorial on how to create the Database and what Mysql Version I need to install?

**Comment by Elgrimm** [comment]
I am using MariaDB-10.3
Which table can't you fill in?

**Comment by Elgrimm** [comment]
This project has ceased to be supported, I have now made a separate branch on BitBucket. I'll work it out a bit and open it up.

**Comment by lbsoliver** [comment]
Hello Elgrim, thanks for your answer! 

I switched from mysql 5.7 to 8.0, i could import all files without any problem, but now i get some SQL syntax errors from worldserver, do i need MariaDB to work properly?


![image](https://user-images.githubusercontent.com/82239211/118365523-6a216b00-b59d-11eb-8598-fcb15c426bc6.png)

**Comment by Elgrimm** [comment]
MariaDB-10.3

**Comment by dufernst** [comment]
> 
> 
> Hello, thanks for hosting this project on Github!
> 
> I got some problems with the database, when I import the updates I get errors because the varchar is 512.
> 
> Could u give me a little Tutorial on how to create the Database and what Mysql Version I need to install?

This project is still somewhat supported, just with very low priority on my part :)
Unfortunately this is not the type of problem I can help with.

**Comment by dufernst** [comment]
@lbsoliver please run the following query on your auth database:
ALTER TABLE `account` DROP INDEX `sha_pass_hash`;

That should fix the issue, for future users the index has been removed in https://github.com/dufernst/LegionCore-7.3.5/commit/dafba61a1f31674f24e43e3831e3b629a2b38d99
