### ISSUE TITLE
 https://www.wowhead.com/quest=42740/the-battle-for-broken-shore

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#25]
When teleporting to the Broken Shore, is kicked out of the game.

https://drive.google.com/file/d/1-2Qx4z8ETePgOxRtvQRDebUayNKemkPA/view?usp=sharing

**Comment by fluxurion** [comment]
what do the console says when it's happen?

**Comment by Elgrimm** [comment]
For some reason, the logs on the player's actions do not write to me.

worldserver_conf 
Logger.Root=0,3,Console Server
Logger.Chat=22,3,Chat
Logger.DBErrors=26,2,DBErrors
Logger.GM=27,3,Console Server GM
Logger.RA=28,3,RA
Logger.Warden=29,4,Warden
Logger.WorldServer=31,3,Console Server
Logger.Character=34,3,Char
Logger.Arenas=35,3,Arenas
Logger.SQLDriver=36,0,SQLDriver
Logger.SQLDev=37,0,SQLDev
Logger.Load=40,3,Console Server
Logger.Opcodes=41,0,Console Server
Logger.Network=7,0,Console Server
Logger.Bg=13,0,Console Server
Logger.Items=20,3,Console Server
Logger.Maps=17,0,Console Server
Logger.mscript=6,3,Console Server
Logger.veh=3,3,Console Server
Logger.spell=8,0,Console Server
Logger.plr=18,0,Console Server
Logger.skills=21,0,Console Server
Logger.Smart=5,0,Console Server
Logger.Script=4,0,Console Server
Logger.guild=24,0,Console Server
Logger.comditions=10,0,Console Server
Logger.units=1,0,Console Server
Logger.lfg=16,0,Console Server
Logger.SI=35,0,Console Server

#Logger.GameEvents=32,3,Console Server
#Logger.Calendar=33,3,Console Server
#
#    Loggers
#        Description: List of Loggers to read from config
#                     (Using spaces as separator).
#        Default:     "Root Chat DBErrors GM RA Warden Character Load"

Loggers=Root Chat DBErrors GM RA Warden Character Load WorldServer Opcodes Network SI Bg mscript veh spell Items plr Smart skills guild Script comditions units lfg

**Comment by Elgrimm** [comment]
Corrected. The problem is in Anti-Cheat. Disabled it.

**Comment by Elgrimm** [comment]
SAC: FakeTransport (Tick: 1) Kicked.

**Comment by Elgrimm** [comment]
void PlayerCheatData::OnTransport(Player* plMover, ObjectGuid transportGuid)
{
    // The anticheat is disabled on transports, so we need to be sure that the player is indeed on a transport.
    GameObject* transportGobj = plMover->GetMap()->GetGameObject(transportGuid);
    float maxDist2d = 70.0f; // Transports usually dont go far away.
    if (plMover->GetMapId() == 369) // Deeprun tram
        maxDist2d = 3000.0f;
    if (!transportGobj || !transportGobj->IsTransport() || !transportGobj->IsWithinDist(plMover, maxDist2d, false))
        AddCheats(1 << CHEAT_TYPE_FAKE_TRANSPORT);
}

**Comment by dufernst** [comment]
Thanks for posting :+1:

**Comment by Elgrimm** [comment]
I am reworking the anti-cheat, as I will finish writing here. Have you abandoned this repository?

**Comment by dufernst** [comment]
I am not going to abandon this repository, I am just busy with other things I need to work on.
Eventually (might take a couple of weeks, or worst case a couple of months) I will have more time again to work on this.

Before I had to switch focus to another project, I was working on WoD garrisons, those are almost in a decent enough state. But I need more time first before I can finish that up.

**Comment by dufernst** [comment]
Closing this issue as resolved, if something similar happens for another reason feel free to open a new issue.
