### ISSUE TITLE
No realm!!!!!

### ISSUE THREAD

**Issue by Arshiya051** [dufernst/LegionCore-7.3.5#26]
![Capture](https://user-images.githubusercontent.com/23295554/119260832-dd545e00-bbe9-11eb-8e54-8685e167dcaa.PNG)
 

I had never encountered such an error before. There is no problem with the database. I even use the Repack database, it gives this error again. Can you help me get in?

**Comment by fluxurion** [comment]
Yeah check the client version. It have to set to the same in the realm database, the bnetserver.conf and the worldserver.conf. And for sure you can only join with that version. E.g.: 7.3.5.26972 ...Btw I use 26365 because it has minimal client and character templates only work with that.

**Comment by fluxurion** [comment]
![help](https://user-images.githubusercontent.com/25673748/119262294-002b4600-bbdb-11eb-8678-08bb7682e3ce.png)

**Comment by dufernst** [comment]
Thanks for all the help you have been giving @fluxurion :+1: 
But yeah, with the default database everything should work fine, and with @fluxurion instructions it should work out @Arshiya051

**Comment by Arshiya051** [comment]
very ty @fluxurion 
worked.
