### ISSUE TITLE
The tactical map is not working

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#27]
Hunters. You cannot send mercenaries on a mission on the tactical map. When you press "Start quest" nothing happens.

**Comment by dufernst** [comment]
This is specifically only not working for hunters?

**Comment by Elgrimm** [comment]
At least for paladins, the starting quests work properly, and when quests are taken from the NPC, they are added to the tactical map, but there are no hunters.

**Comment by dufernst** [comment]
Do you have an example of one of those hunters? I don't quite get what you mean by those. Do you mean the NPCs that you can send out on missions?

**Comment by fluxurion** [comment]
Can u make a video of this situation? I don't even get what's wrong xd

**Comment by Ragelezz** [comment]
the actual bug is that when you press Start Mission on your Class Hall, it won't do nothing at all, just get back to Missions list. 
A pic here:
![Uploading WoWScrnShot_040822_214543.jpg…]()

**Comment by Ragelezz** [comment]
fixed in new commit.

**Comment by dufernst** [comment]
Great, thanks for letting me now :)
