### ISSUE TITLE
keystone

### ISSUE THREAD

**Issue by Arshiya051** [dufernst/LegionCore-7.3.5#28]
the keystone 2 and more is problem?

I took the key. Then I went to upgrade it, but in the end the box does not give the prize and the next key.

**Comment by dufernst** [comment]
Could you link the quest in question?

**Comment by EvilCalf** [comment]
> the keystone 2 and more is problem?
> 
> I took the key. Then I went to upgrade it, but in the end the box does not give the prize and the next key.

Hello,have you solved it.

**Comment by Arshiya051** [comment]
> > the keystone 2 and more is problem?
> > I took the key. Then I went to upgrade it, but in the end the box does not give the prize and the next key.
> 
> Hello,have you solved it.

No....

**Comment by qyh214** [comment]
Have you completed instance in the group?

**Comment by Arshiya051** [comment]
Yes . I made a group and tried it. Kay Stone has no problem. It is absolutely true.
@qyh214
