### ISSUE TITLE
 Navigation not working on Argus

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#31]
The map does not show where to turn in the quest, where to get it and where to complete it.

**Comment by hygfrtqwe** [comment]
give me discord id

**Comment by wplatform** [comment]
Some issues were encountered with me in Ogrimmar. talk to an NPC to know where is the class trainer. The map does not show the location flag. And the map does not show where to turn in the quest. How to fix this issue. I know the NPC menu action implemented by the function gross_ip, but don't know which code to implement this.

**Comment by EvilCalf** [comment]
> The map does not show where to turn in the quest, where to get it and where to complete it.

Have you solved this problems?
