### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#32]
The project was closed?

**Comment by fluxurion** [comment]
I switched to shadowlands

**Comment by Elgrimm** [comment]
> I switched to shadowlands

Don't know how to fix an Architectural table in the Garrison? It is not clickable.

**Comment by Elgrimm** [comment]
![unknown](https://user-images.githubusercontent.com/36525398/127644216-8dc78b40-98bd-4514-8467-1f017ac93993.png)

**Comment by fluxurion** [comment]
Change flags to corect flag id

**Comment by fluxurion** [comment]
8589934592

**Comment by Elgrimm** [comment]
> 8589934592
This flag is not present in the source code

**Comment by Elgrimm** [comment]
And when I put it down, the table disappears

**Comment by Elgrimm** [comment]
> 8589934592

Do you know what else might be the problem?

void WorldSession::HandleGarrisonPurchaseBuilding(WorldPackets::Garrison::GarrisonPurchaseBuilding& packet)
{
    if (!_player->GetNPCIfCanInteractWith(packet.NpcGUID, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAG2_GARRISON_ARCHITECT))
        return;

    if (Garrison* garrison = _player->GetGarrison())
        garrison->PlaceBuilding(packet.PlotInstanceID, packet.BuildingID);
}

Where UNIT_NPC_FLAG2_GARRISON_ARCHITECT = 2

**Comment by Elgrimm** [comment]
I did it!
