### ISSUE TITLE
 Character templates

### ISSUE THREAD

**Issue by Payk1488** [dufernst/LegionCore-7.3.5#35]
How do I include a character template when I create it? On other servers, I saw the inclusion of templates in the worldserver.conf settings. But there is no such option, although there are character_template tables in the SQL world database.

**Comment by dufernst** [comment]
@Payk1488 it is a matter of adding the required information to the tables you already mentioned:

- `character_template`
- `character_template_class`
- `character_template_item`
- `character_template_quest`
- `character_template_spell`
- `character_template_title`

What you need to add exactly to get the desired effect I wouldn't know, I never used these tables, but from as far as I can tell (looking at the source code) setting up templates using these tables should work perfectly fine.
