### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by wplatform** [dufernst/LegionCore-7.3.5#38]
[ 25%] Building CXX object dep/cds/CMakeFiles/cds.dir/src/topology_linux.cpp.o
In file included from /usr/include/mysql/mysql.h:83,
                 from /opt/coderepo/LegionCore/src/common/Database/Field.h:24,
                 from /opt/coderepo/LegionCore/src/common/Database/DatabaseEnv.h:26,
                 from /opt/coderepo/LegionCore/src/server/bnetserver/PrecompiledHeaders/bnetPCH.h:6,
                 from /opt/coderepo/LegionCore/src/server/bnetserver/PrecompiledHeaders/bnetPCH.cpp:1:
/usr/include/mysql/client_plugin.h: At global scope:
/usr/include/mysql/client_plugin.h:117:8: error: using typedef-name ‘MYSQL’ after ‘struct’
  117 | struct MYSQL;
      |        ^~~~~
compilation terminated due to -Wfatal-errors.
make[3]: *** [src/server/bnetserver/CMakeFiles/bnetPCH.cpp_dephelp.dir/build.make:72: src/server/bnetserver/CMakeFiles/bnetPCH.cpp_dephelp.dir/PrecompiledHeaders/bnetPCH.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1135: src/server/bnetserver/CMakeFiles/bnetPCH.cpp_dephelp.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

**Comment by dufernst** [comment]
Which version of MySQL are you using?

**Comment by dufernst** [comment]
Great, and yeah, if someone wants to go over all of them to fix them that would be great :D
