### ISSUE TITLE
Worldserver issue.

### ISSUE THREAD

**Issue by FatGrandpa007** [dufernst/LegionCore-7.3.5#39]
MySQL 5.7
Cmake newest version available.
Boost 1.64.0
OpenSSL 1.1.1k

I had some issues with the database included at first, so I used world from the UWoW project.
Worldserver doesn't throw anymore errors, but it doesn't open for long either, it closes after Loading Hotifx info
The crash log is empty, it holds absolutely no info barely, and neither does the log.

I haven't been able to sort it out, but I'm fairly certain it's a database issue.
The wiki links included on the repositories main page aren't available anymore so there's little to no info on them.
What is the steps to take with database? Do I use the included Auth, Characters, world and hotfixes and nothing else?
I've tried using base only, but was errors on hotfixes and world SQL, I tried base with updates.
And I tried a variation of uwow database and the ones included with this source, none of it worked for me.
I of course ran all the DB updates and base files included with source, but using that only comes with a ton of errors when you launch both auth and world, missing tables and what not.
Are we suppose to use the UWoW ones from the repack page linked on the repo main page?
I've tried a ton of things but can't get it working, really wanna get it up and running though.

I'm sorry if this is not enough information included, let me know if there's anything else you need and I'll gladly give it

![Worldserverlog](https://user-images.githubusercontent.com/77056013/148459093-20f84dbb-b9b8-4dad-9dc6-9d116c096429.jpg)

![WorldserverCrashLog](https://user-images.githubusercontent.com/77056013/148459105-45a3b37f-6652-412d-8437-0248bbb62643.jpg)
.

**Comment by dufernst** [comment]
You should be using the source and database files from this repo:
https://github.com/dufernst/LegionCore-7.3.5/tree/master/sql
be sure to also apply the updates in the sql/updates folder.

A link to the required data files can be found here:
https://github.com/dufernst/LegionCore-7.3.5#data-files

That combined should work, might take some fiddling around but otherwise no issues worth mentioning.

**Comment by FatGrandpa007** [comment]
I've tried that, I'm uploading the SQL files through HeidiSQL, MariaDB or MySQL (TCP/IP)

Auth and characters goes fine, but for hotfixes and world there's errors on import, not entirely sure what we're doing wrong there.
I'll attach an image with errors in question down below.

I've opened the SQL files using Notepad++, and removed the lines with the variables sql_mode and such (errors are shown below in image), but even then it says there's errors, the output just doesn't show exactly which errors anymore.
I'm wondering if this might be due to the GUI I'm using? or version of MySQL, and or if it's cause I'm on Windows.
It still imports most of the SQL files, but if I leave it at that after importing the update files as well, the worldserver won't launch with same issues as I mentioned in above post, there's nothing in crash log, and worldserver output doesn't show anything either.
I'm stomped by it, never experienced anything like this before.

![SQLErrorOnImport](https://user-images.githubusercontent.com/77056013/148536029-e8e0b3c7-67ed-4f95-8c3c-c2d511bb020a.jpg)

**Comment by dufernst** [comment]
I don't know how your MySQL database is configured, but maybe it is not happy with these very large sql files.
You could try splitting up the hotfix and world database queries and run those step by step.
If that works, you could configure MySQL to accommodate for those large queries for in the future.

**Comment by FatGrandpa007** [comment]
I can run larger SQL files no issue, we often run backups of our live servers DB onto our PTR realm for testing.
It finds the encoding automatically without issue so it's not that either.

It's super strange, I've tried just about everything I can think of but can't get the worldserver running properly.
Usually if it's a DB issue it would call an outdated error or something, but just hangs on whatever comes after the hotfixes load.
And without any output on crash log or dump, or the worldserver logs it's difficult to pinpoint the exact issue.

**Comment by FatGrandpa007** [comment]
You were right, at some point I must have reinstalled the MySQL server, max_allowed_packet_size was set to 4M, changed it to 256M and it fixed the error.

But the worldserver still hangs and crashes after the hotfixes load, so it's not a SQL error I guess.

**Comment by dufernst** [comment]
Are you sure you are not just running out of memory or something?
The core is "very" memory hungry :|

**Comment by FatGrandpa007** [comment]
Fairly certain, got 32 GB DDR4 3600.
Crash log says 28 was available, I made sure no heavy load programs or anything was open at the time in case it was something like that.
I suspect that should be enough though?

**Comment by dufernst** [comment]
Yeah 32GB is more than enough, maybe you can run the worldserver in a debugger so we can see where it crashes :)?

**Comment by FatGrandpa007** [comment]
Yeap I'll try that, just recompiling to make sure was no error or warning in cmake or anything I might have missed.
If still happening I'll run it through debugger and see.

I appreciate the quick replies and everything!

**Comment by dufernst** [comment]
No problem 👍 
Going offline now though, will be able to assist further this evening (if it is not solved by then) :)

**Comment by FatGrandpa007** [comment]
This is what I got so far, I'm not an avid debugger so sadly doesn't tell me much.

![Debug](https://user-images.githubusercontent.com/77056013/148554400-6a963fbd-587f-41ec-b53e-6e877ef83c8c.jpg)

**Comment by dufernst** [comment]
Well considering you compiled it before, this shouldn't be the issue :P?

**Comment by FatGrandpa007** [comment]
Was an issue due to outdated visual studio lmao.
Okay now for the real issue, it still hangs, and debug shows me this, but not a avid debugger so doesn't tell me insanely much

![LegionDebug1](https://user-images.githubusercontent.com/77056013/148564131-eda7149c-ab5f-4829-8203-e1d00185d5cd.jpg)
.

It doesn't look like it's a source issue?

**Comment by dufernst** [comment]
Using 2017 is not a requirement for as far as I know.
But this issue really doesn't ring a bell for me, don't think I can help you with this :|
In general it looks like the worldserver is not being properly initalized currently, but why, no idea.

**Comment by FatGrandpa007** [comment]
Yeah I don't get it either, I run a public live AC 3.3.5 server, compiling that without issues daily.
I can compile TC as well, so there shouldn't be any issues with MSVC or anything of the sorts.
But this I just cannot get working, and we really wanna do so, both to contribute to the project and to host a 7.3.5 realm on the side.

Both me and my Co-Owner is unable to read the issue and fix it.
Running all DLL's as 64, OpenSSL, MySQL etc, everything is x64 so that's not a compatibility issue either.
Latest Cmake, latest MSVC, correct 1.64.0 boost, MySQL 5.7 on both libs and server.
Database is imported without errors now, so I'm unable to see what the issue might be..

**Comment by dufernst** [comment]
Well the DatabaseWorker seems to be uninitialized, you could take a look if the others objects are initialized in which case something might be suboptimal in terms of SQL setup. Maybe wrong libs/dlls for MySQL combined with the server version e.g. But I am now just guessing, this is really not something I can easily help with :D

**Comment by FatGrandpa007** [comment]
I'll keep trying, just go from A to Z until we sort it out, if you do recollect something or anything do let me know!
And of course if I find a solution, which I must, I'll post it here and close issue in case other's run into it as well.

**Comment by dufernst** [comment]
If I think of something I'll let you know, hopefully it turns out to be something easy to fix 👍

**Comment by FatGrandpa007** [comment]
We've tried on 2, in a few minutes 3 completely different computers, with different setups and it has the same issue
This makes absolutely no sense to me

**Comment by FatGrandpa007** [comment]
Yeah officially tried absolutely everything I can think of..
You guys have any other ideas what it could be? I checked if it's SQL stuff not being initializes but I can't see any, if there is any.

**Comment by dufernst** [comment]
Could you share the output of when you run cmake? Maybe that provides some insights.

**Comment by FatGrandpa007** [comment]
Solved the issue, it was a config issue, took a lot of debugging to figure out, and it was so simple.
To anyone else having this issue, make sure the data folders correspond with the config.
As default our data folder and a few folders inside was named differently then what the config said, and due to very low and mostly non existent logging the worldserver wasn't able to detail the exact issue.

Any chance you have a Discord I can have? I need to ask you a question regarding something else that I don't necessarily want public, I'd appreciate it tons!

**Comment by dufernst** [comment]
You can mail me your discord handle: dufernst @ epicduf . nl

**Comment by FatGrandpa007** [comment]
I emailed you, thanks a lot, I'll close this issue now then.
