### ISSUE TITLE
dbc/maps for this core

### ISSUE THREAD

**Issue by c0per0** [dufernst/LegionCore-7.3.5#4]
Hello, could someone do me the favor of telling me where to get such data? I tried with this repack https://www.emucoach.com/forums/threads/legioncore-7-3-5-repack-version-2020_04_25_final.7097/, but I still deleted the mediafire files and there is no way to find functional ones, I just want more specifically the vmaps and mmaps, thanks in advance and sorry for my English.

**Comment by dufernst** [comment]
The dbc/vmaps/maps/mmaps etc for this core can be found here:
https://www.emucoach.com/forums/threads/new-repack-7-3-5-legion-wow-repack-wow-legion-7-3-5-repack-blizzlike-fun.6945/

**Comment by c0per0** [comment]
thanks.

**Comment by dufernst** [comment]
Closing because it is resolved, a link to the datafiles has also been added to the readme.
