### ISSUE TITLE
Broken Island Missions.

### ISSUE THREAD

**Issue by Ramys** [dufernst/LegionCore-7.3.5#5]
Several missions on broken islands do not appear the name.

**https://ibb.co/GVrpDHd**

**Comment by dufernst** [comment]
@Ramys Are you playing with .gm on there? Looking at the spawns I would otherwise assume you are using the wrong dbc/vmaps/maps/mmaps. Could you make sure you are using the ones linked to here:
https://github.com/dufernst/LegionCore-7.3.5/issues/4

**Comment by Ramys** [comment]
True..I messed up the maps
