### ISSUE TITLE
Mythic Key not upgrade from level 2  , not give a loot chest and not update table 

### ISSUE THREAD

**Issue by Donado91** [dufernst/LegionCore-7.3.5#50]
Mythic plus any instance  didn't appear the chests and don't upgrade the key when completing lvl 2key to + 3 chest ,and it give me the achiev of completing a key 10 on time, while the key was 2  and it don't count for the weekly chest too
https://paste.pics/40c21dc06a15ec33b97b13367be0240b 
https://paste.pics/f9c9bdb66edff9478eb7f1d01c10d32b

**Comment by eXPeRi91** [comment]
Last time, I tested it, was working...

**Comment by Elgrimm** [comment]
If so, that's the problem. Take a look at the update function
void Challenge::Update(uint32 diff)

In general, the Group function is prescribed for the group

**Comment by Elgrimm** [comment]
The problem, as I understand it, is that you go alone, and not with a group, although you should go try it in two.

**Comment by eXPeRi91** [comment]
I mean, I have tested it with group of 5 players. not solo.. Was working

**Comment by Donado91** [comment]
> If so, that's the problem. Take a look at the update function void Challenge::Update(uint32 diff)
> 
> In general, the Group function is prescribed for the group

Yes I test în group and is working , sory for non valid bug report , thankyou very much for all support

**Comment by EvilCalf** [comment]
> > If so, that's the problem. Take a look at the update function void Challenge::Update(uint32 diff)
> > In general, the Group function is prescribed for the group
> 
> Yes I test în group and is working , sory for non valid bug report , thankyou very much for all support

Have you solved it. I met the same problems.

**Comment by qyh214** [comment]
> > > If so, that's the problem. Take a look at the update function void Challenge::Update(uint32 diff)
> > > In general, the Group function is prescribed for the group
> > 
> > 
> > Yes I test în group and is working , sory for non valid bug report , thankyou very much for all support
> 
> Have you solved it. I met the same problems.

you should with 4 players test it
