### ISSUE TITLE
Architectural table

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#51]
The question is, after filling in the progress scale at the table, its state changes from Building to Active to 100 percent. Accordingly, an Event is triggered and a spell is cast on the player. And the question is, what spell does which building have?
CONTRIBUTION_MAGE_TOWER:
CONTRIBUTION_COMMAND_CENTER:
CONTRIBUTION_NETHER_DISRUPTOR:

**Comment by eXPeRi91** [comment]
No Idea what are you talking about, but okay.

**Comment by dufernst** [comment]
I assume it is related to:
https://github.com/dufernst/LegionCore-7.3.5/issues/44
