### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#52]
Worldserver crashes
Call stack:
Address   Frame     Function      SourceFile
00007FF708E57CC4  000000AE7C6FE230  CharmInfo::InitCharmCreateSpells+64  C:\Uwow\src\server\game\Entities\Unit\CharmInfo.cpp line 160
00007FF7088BC6C6  000000AE7C6FE300  Unit::SetCharmedBy+716  C:\Uwow\src\server\game\Entities\Unit\Unit.cpp line 22643
00007FF708ABAAF6  000000AE7C6FE330  AuraEffect::HandleEffect+E6  C:\Uwow\src\server\game\Spells\Auras\SpellAuraEffects.cpp line 1875
00007FF7088EDEE4  000000AE7C6FE440  AuraApplication::_HandleEffect+224  C:\Uwow\src\server\game\Spells\Auras\SpellAuras.cpp line 142
00007FF7088CEB7D  000000AE7C6FE4A0  Unit::_ApplyAura+15D  C:\Uwow\src\server\game\Entities\Unit\Unit.cpp line 4623
00007FF7088ED0D1  000000AE7C6FE590  Aura::_ApplyEffectForTargets+241  C:\Uwow\src\server\game\Spells\Auras\SpellAuras.cpp line 1183
00007FF708FD630A  000000AE7C6FE5F0  Spell::EffectApplyAura+13A  C:\Uwow\src\server\game\Spells\SpellEffects.cpp line 2281
00007FF708D7D512  000000AE7C6FE6A0  Spell::HandleEffects+252  C:\UwowElisGrimm\src\server\game\Spells\Spell.cpp line 6600
00007FF708D7C3A2  000000AE7C6FE950  Spell::DoSpellHitOnUnit+10A2  C:\Uwow\src\server\game\Spells\Spell.cpp line 3422
00007FF708D79EFE  000000AE7C6FEB90  Spell::DoAllEffectOnTarget+3AE  C:\Uwow\src\server\game\Spells\Spell.cpp line 2720
00007FF708D8F344  000000AE7C6FEBD0  Spell::handle_immediate+64  C:\Uwow\src\server\game\Spells\Spell.cpp line 4766
00007FF708D8E63A  000000AE7C6FF140  Spell::cast+1E2A  C:\Uwow\src\server\game\Spells\Spell.cpp line 4719
00007FF708D91152  000000AE7C6FF1C0  Spell::update+372  C:\Uwow\src\server\game\Spells\Spell.cpp line 5083
00007FF708D7C7A1  000000AE7C6FF230  SpellEvent::Execute+31  C:\Uwow\src\server\game\Spells\Spell.cpp line 9313
00007FF7091F2428  000000AE7C6FF260  EventProcessor::Update+68  C:\Uwow\src\common\Utilities\EventProcessor.cpp line 56
00007FF7088CAC83  000000AE7C6FF2C0  Unit::Update+73  C:\Uwow\src\server\game\Entities\Unit\Unit.cpp line 457
00007FF70897A7D9  000000AE7C6FF590  Player::Update+1B9  C:\Uwow\src\server\game\Entities\Player\Player.cpp line 1481
00007FF7087BC6BC  000000AE7C6FF800  Map::Update+17C  C:\Uwow\src\server\game\Maps\Map.cpp line 1086
00007FF7087BC504  000000AE7C6FF830  InstanceMap::Update+14  C:\Uwow\src\server\game\Maps\Map.cpp line 4287
00007FF708F472D7  000000AE7C6FF900  MapInstanced::Update+127  C:\Uwow\src\server\game\Maps\MapInstanced.cpp line 104
00007FF7087BDF85  000000AE7C6FF9F0  Map::UpdateLoop+365  C:\Uwow\src\server\game\Maps\Map.cpp line 5362
00007FF707DC8192  000000AE7C6FFA20  std::thread::_Invoke<std::tuple<void (__cdecl Map::*)(unsigned int),Map *,unsigned int>,0,1,2>+12  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\thread line 56
00007FF8C524268A  000000AE7C6FFA50  _o_exp+5A
00007FF8C6917974  000000AE7C6FFA80  BaseThreadInitThunk+14
00007FF8C900A2F1  000000AE7C6FFB00  RtlUserThreadStart+21

**Comment by Elgrimm** [comment]
> Did you use any spell and if yes, which one did you use?

I'm trying to repeat, crash doesn't come out.

**Comment by Elgrimm** [comment]
> Did you use any spell and if yes, which one did you use?

Do you have a Discord? Can you add me as a friend?  ElisGrimm#2790

**Comment by eXPeRi91** [comment]
Try with Control Undead, and sorry I don't have time for disco now.

**Comment by Elgrimm** [comment]
> Try with Control Undead, and sorry I don't have time for disco now.
Yes Undead Control Spell

**Comment by dufernst** [comment]
@Elgrimm if you have a way for me to reproduce this reliably then I will sort it out 👍

**Comment by eXPeRi91** [comment]
> @Elgrimm if you have a way for me to reproduce this reliably then I will sort it out 👍

It's Control Undead (DK spell 111673) .npc add 49240 =(Captain Ironhill's Ghost) and use the spell.
Sometimes will not crash, but most of the times it crash because the target get NULL 
But for me the crash Call stack is related for guardians ... Exactly here: [LINK](https://github.com/dufernst/LegionCore-7.3.5/blob/701f3d4332c204c86fb53d6f0fe84ce5ba6264e6/src/server/scripts/World/npcs_special.cpp#L1466)

**Comment by Elgrimm** [comment]
No idea?
=)

**Comment by Elgrimm** [comment]
Fix, close

**Comment by Elgrimm** [comment]
It's a pity that this project was abandoned.

**Comment by dufernst** [comment]
This project has not been abandoned, it just takes time for me to get to these issues.
Hardly anyone is making merge requests or making their fixes public, so I also have to do myself what others probably have done for their own servers already.
