### ISSUE TITLE
Archeology Crash

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#53]
Call stack:
Address   Frame     Function      SourceFile
00007FF708FAE71A  000000BA055FEA40  Player::_SaveArchaeology+13A  C:\Uwow\src\server\game\Skills\Archaeology.cpp line 761
00007FF7089600D3  000000BA055FF1B0  Player::SaveToDB+2173  C:\Uwow\src\server\game\Entities\Player\Player.cpp line 24974
00007FF70897B124  000000BA055FF480  Player::Update+B04  C:\Uwow\src\server\game\Entities\Player\Player.cpp line 1751
00007FF7087BC6BC  000000BA055FF6F0  Map::Update+17C  C:\Uwow\src\server\game\Maps\Map.cpp line 1086
00007FF7087BDF85  000000BA055FF7E0  Map::UpdateLoop+365  C:\Uwow\src\server\game\Maps\Map.cpp line 5362
00007FF707DC8192  000000BA055FF810  std::thread::_Invoke<std::tuple<void (__cdecl Map::*)(unsigned int),Map *,unsigned int>,0,1,2>+12  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\thread line 56
00007FF8C524268A  000000BA055FF840  _o_exp+5A
00007FF8C6917974  000000BA055FF870  BaseThreadInitThunk+14
00007FF8C900A2F1  000000BA055FF8F0  RtlUserThreadStart+21

**Comment by VILRIETTA** [comment]
I checked the archeology, it does not cause crash for me.
