### ISSUE TITLE
VAS Autobalance Script possible add in this core ? 

### ISSUE THREAD

**Issue by Zydrax** [dufernst/LegionCore-7.3.5#54]
Hello , Dufernst is posible to implement this : [https://github.com/conan513/SingleCore_TC/commit/3f4a7ac358a6d0d4443b9b5336734a13bed4698d](url)  on this core , do you have a discord  name ? I realy need speck with you . Thank you !

**Comment by dufernst** [comment]
Sure it is possible to add it, but I am not going to add it to this repository.
But if you want to maintain a fork (and keep it up to date) I can refer people that want this kind of functionality to your repository :)

**Comment by Zydrax** [comment]
ok will be nice , i will made a fork and you can add there , also if need pay for this plss just give me some info or discord to give me your price , thank you again !

**Comment by dufernst** [comment]
@Zydrax I meant for you to integrate it yourself, and then I don't mind referring other people to your work when they are interested in VAS Autobalance :)
