### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Nexon99** [dufernst/LegionCore-7.3.5#6]
Hi, i've a problem for compile the core. 

With Cmake i've everytime "**Boost_DIR-NOTFOUND**" but the Configuring and Generating is done. (?)

> Error : https://zupimages.net/up/20/41/oo1g.png

> `CMake Warning (dev) at dep/boost/CMakeLists.txt:29 (find_package):
>   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   Environment variable Boost_ROOT is set to:
> 
> C:/local/boost_1_72_0
> 
>   For compatibility, CMake is ignoring the variable.
> This warning is for project developers.  Use -Wno-dev to suppress it.`

---------------------------------------------------------------------------
so, during Visual studio compilation i've multiple errors that I can't fix. 

> https://zupimages.net/up/20/41/jex6.png

BOOST : 1.66.0 or 1.72.0 (msvc-14.1) / or  (msvc-14.2)  [64bits]
OpenSSL : 1.1.1h [64bits]
Visual Studio : 2017 or 2019 

I had already succeeded in compiling my source before, but after a changing pc, it's impossible. Any idea ?

**Comment by Ramys** [comment]
You need the version mentioned!
Boost 1.64
Compiled with her without any problems.
https://sourceforge.net/projects/boost/files/boost/1.64.0/

**Comment by Nexon99** [comment]
Working thanks. ^^
