### ISSUE TITLE
Found new question,no found model in table creature_template

### ISSUE THREAD

**Issue by qqwqqwe** [dufernst/LegionCore-7.3.5#60]
ERROR Creature (entry: 230000) has no model defined in table `creature_template`, can't load.
ERROR Creature (entry: 220011) has no model defined in table `creature_template`, can't load.
ERROR Creature (entry: 230005) has no model defined in table `creature_template`, can't load.

**Comment by Elgrimm** [comment]
> 230000

230000	Battle Coin Vendor								SPP			4	0	7	0	3	0	0	0	20387	0	0	0	1000000000	72	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1

**Comment by Elgrimm** [comment]
add in table creature_template_wdb

**Comment by Elgrimm** [comment]
230005	Transmogrifier Special								SPP		Transmogrify	4	0	7	0	3	0	0	0	38804	0	0	0	1000000000	72	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1

**Comment by Elgrimm** [comment]
220011 no displayid =(

**Comment by qqwqqwe** [comment]
Good in table creature_template_wdb is ok,

**Comment by Elgrimm** [comment]
Then I don't know what you want.....

**Comment by qqwqqwe** [comment]
I start testing the cord and try to fix database error
