### ISSUE TITLE
Bpay won't "trigger"

### ISSUE THREAD

**Issue by Ragelezz** [dufernst/LegionCore-7.3.5#62]
Hi there, ran this core and i have an issue.. battle pay won't load, it stays like this forever: https://i.imgur.com/RWtoOzR.png
any clue ?

**Comment by qqwqqwe** [comment]
Yes， you can fix another don't fix Bpay.

**Comment by qqwqqwe** [comment]
Yes， you can fix another don't fix Bpay.

**Comment by Ragelezz** [comment]
not helpful :v

**Comment by Crandalius** [comment]
Are you using this source? As far as I know this source only has the lvl 90 boost working

**Comment by Ragelezz** [comment]
Yes and i just add the items, I checked aswell with the 90 boost and its still stuck at Loading (before adding items)

**Comment by Crandalius** [comment]
Hmm okay, did you make any changes in the source? Mine shows only the 90 boost in bpay

**Comment by Ragelezz** [comment]
Yes, i added the rest of the options so you can buy different stuff but the thing is, as mentioned, is was stuck in loading even after launching the bpay with lvl 90 boost only.
Give me something, discord or something so I can show you in private, maybe you have a clue.

**Comment by fluxurion** [comment]
Hi guys! I just fixed this in my wod server (Thank you Dufernst! <3)

Also when i used this source the problem was the same when i wanted to add more items (now my pr is in closed by me).

You can try this method:

- open src/server/game/Server/Packets/BattlePayPackets.cpp
- search the function: WorldPackets::BattlePay::DistributionListResponse::Write()
- i commented out hardCodedDistributionListResponse & uncommented the old packetdata like the code above


```
WorldPacket const* WorldPackets::BattlePay::DistributionListResponse::Write()
{
    //for (const uint8_t byte : hardCodedDistributionListResponse)
        //_worldPacket << byte;

    _worldPacket << Result;
    _worldPacket.WriteBits(DistributionObject.size(), 11);
    for (BattlePayDistributionObject const& objectData : DistributionObject)
        _worldPacket << objectData;

    return &_worldPacket;
}
```

**Comment by Crandalius** [comment]
> Yes, i added the rest of the options so you can buy different stuff but the thing is, as mentioned, is was stuck in loading even after launching the bpay with lvl 90 boost only. Give me something, discord or something so I can show you in private, maybe you have a clue.

Hmm okay, I'd like to test it with you. My discord is Falklore#8305

**Comment by Crandalius** [comment]
> Hi guys! I just fixed this in my wod server (Thank you Dufernst! <3)
> 
> Also when i used this source the problem was the same when i wanted to add more items (now my pr is in closed by me).
> 
> You can try this method:
> 
> * open src/server/game/Server/Packets/BattlePayPackets.cpp
> * search the function: WorldPackets::BattlePay::DistributionListResponse::Write()
> * i commented out hardCodedDistributionListResponse & uncommented the old packetdata like the code below
> 
> ```
> WorldPacket const* WorldPackets::BattlePay::DistributionListResponse::Write()
> {
>     //for (const uint8_t byte : hardCodedDistributionListResponse)
>         //_worldPacket << byte;
> 
>     _worldPacket << Result;
>     _worldPacket.WriteBits(DistributionObject.size(), 11);
>     for (BattlePayDistributionObject const& objectData : DistributionObject)
>         _worldPacket << objectData;
> 
>     return &_worldPacket;
> }
> ```

@fluxurion thanks for this, I'll try this out too. I had a look at your previous pull request and merged it to my own core but can't build the core with your fixes none of the less this might solve the issue by Ragelezz, fingers crossed

**Comment by qqwqqwe** [comment]
Good its work perfect

**Comment by Ragelezz** [comment]
Thank you guys for the response.
@fluxurion code is already like this :(

**Comment by Ragelezz** [comment]
issue resolved.

**Comment by Axdrell** [comment]
> issue resolved.

@Ragelezz - Can you share how you fix your Battlepay Loading loop?

Thanks

**Comment by Axdrell** [comment]
Just for fun, I ported over the BattlePets code (fully working with world quests and battle pet NPCs) to the Mobius Legion branch. Also ported over the BattlePay code from the DuferNST branch. The battlepay store loads and I can see the products loaded from the database but the Loading Please wait gluescreen does not go away. If anyone can share ideas on what part of the code controls this loop, would be helpful.

Thanks

**Comment by Ragelezz** [comment]
@Axdrell Sorry, by any chance do you still need it? I swinged by randomly. I managed to fix the whole system, added new items/bundles etc, increase (adding balance), decrease when purchasing + messages/instant delivery. If you still need it I can share the file from my repo but I forgot the logic behind it since it was.. 2 years+ from now :p

**Comment by Axdrell** [comment]
@Ragelezz , thanks for the reply, yes please share.

**Comment by Ragelezz** [comment]
Ping me on discord please, "rageless".
