### ISSUE TITLE
Found new question  wrong gender (4294967295) ，cannot found gender (4294967295)

### ISSUE THREAD

**Issue by qqwqqwe** [dufernst/LegionCore-7.3.5#63]
Table `creature_model_info` has wrong gender (4294967295) for display id (39360).
Table `creature_model_info` has wrong gender (4294967295) for display id (21263).
Table `creature_model_info` has wrong gender (4294967295) for display id (20688).
Table `creature_model_info` has wrong gender (4294967295) for display id (20698).
Table `creature_model_info` has wrong gender (4294967295) for display id (39464).
Table `creature_model_info` has wrong gender (4294967295) for display id (20690).
Table `creature_model_info` has wrong gender (4294967295) for display id (39949).

**Comment by fluxurion** [comment]
UPDATE creature_model_info SET gender = 2 WHERE modelid IN (21263, 20688, 20698, 39464, 20690, 39949);
UPDATE creature_model_info SET gender = 0 WHERE modelid = 39360;

**Comment by qqwqqwe** [comment]
Table `creature_model_info` has not existed alt.gender model (2) for existed display id (20688)

**Comment by qqwqqwe** [comment]
No found gender， set displayid_other_gender=2 has not existed alt.gender model (2)

**Comment by qqwqqwe** [comment]
SET displayid =displayid_other_gender ERROR ,Table creature_model_info has wrong gender (4294967295) for display id (39360).

**Comment by qqwqqwe** [comment]
Test set displayid_other_gender=（displayid=4，displayid=20690，displayid=20852...），ERROR ,Table creature_model_info has wrong gender (4294967295) for display id (39360， 21263....).
