### ISSUE TITLE
Trinity tool to generate files

### ISSUE THREAD

**Issue by CalsRanna** [dufernst/LegionCore-7.3.5#67]
Can I use trinity tools to generate all files simulator needs instead of downloading from emucoach? Is there any difference between those two?

**Comment by qqwqqwe** [comment]
What  tools

**Comment by CalsRanna** [comment]
extractor

**Comment by qqwqqwe** [comment]
NO

**Comment by CalsRanna** [comment]
Then why the readme told me to use TrinityCore tool to generate gt/xp.txt?Just because the file is a text file and describe the exprience to leve up?

**Comment by qqwqqwe** [comment]
Cannot use Trinity data file

**Comment by CalsRanna** [comment]
ok,thx.
