### ISSUE TITLE
Exiting the battle

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#70]
The character does not always exit the battle and remains in a state of combat even when there are no opponents. Below is a fix for this problem.
In Player.cpp
.................
+
    m_operationsAfterDelayMask = 0;
    m_updateCRsMask = 0;
    m_duelLock = false;

    +m_combatExitTime = 0;

    m_zoneId = 0;
    m_zoneUpdateTimer = 0;
    m_zoneUpdateAllow = false;
...........

     +void Player::OnCombatExit()
     +{
     +UpdatePotionCooldown();
     +m_combatExitTime = getMSTime();
     +}

In Player.h
.....
+
     void SetPersonnalXpRate(float PersonnalXpRate);

     +void OnCombatExit();
.......

**Comment by eXPeRi91** [comment]
@Elgrimm Can you give an example where this happened and/or is it a Player or NPC?
