### ISSUE TITLE
Stable Masters

### ISSUE THREAD

**Issue by Axdrell** [dufernst/LegionCore-7.3.5#73]
The stable masters do not show the pet slots for hunters to store/retrieve their pets.

**Comment by mgracia012020** [comment]
Any suggestions on how to troubleshoot this? I turned on logging and I am not seeing any errors. I see the client opcodes being sent and receiving a response. But the Stable masters still do not show the stable windows. I also confirmed the optionNPC flag (14) , Npc creature_template flag (4194433) and gossip menu (9821) are correct (as per TrinityCore). 

Thanks

**Comment by mgracia012020** [comment]
I am tracing the code and fixed the Stables to display whenever talking to the stable masters. Also made some changes in gossip_menu_option. I am revising the code to add support for stable slot updates (not working yet). Once I wrap this up I will share the fixes. I also checked an old UWOW legion repack and stables master were not working either.

**Comment by dufernst** [comment]
@Axdrell sharing a fix for this would be great.
I have also noticed some issues on this front, but was never high enough priority to take a closer look.

**Comment by Axdrell** [comment]
Want to provide an update to my local code revisions. Below you will find what is needed to enable stable masters to show the Hunter Pet stables and allow swapping of pets within the stables. Right now, the hunter can only use up to 6 slots and swap up to 8 times within the stables. There is something broken with the logic in which the stable slots are handled (have not figured it out yet). If anyone else can take a look, you may be able to find where the problem is within the logic. I will continue trying to fix it (unless I hear someone else found the problem - ideally :). 

The code within the release (i think) is efficient is minimizing the need to add new code. Thus, the reason I tried very hard to minimize my code changes (just trying to reuse what is there). 

FILES CHANGED
	Worldsession.h
	PetHandler.cpp
	Opcodes.cpp
	Player.cpp
	SpellEffects.cpp
	Pet.cpp


SQL: Stable Master - Crossroads - Creature_template ID: 9981. 
Note: Similar SQL query must be executed for all Stable Masters. TrinityCore forum provides some sample queries to fix most stable masters.
=========================
insert into `creature_template` (`entry`, `gossip_menu_id`, `minlevel`, `maxlevel`, `SandboxScalingID`, `ScaleLevelMin`, `ScaleLevelMax`, `ScaleLevelDelta`, `ScaleLevelDuration`, `exp`, `faction`, `npcflag`, `npcflag2`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Mana_mod_extra`, `Armor_mod`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ControllerID`, `WorldEffects`, `PassiveSpells`, `StateWorldEffectID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `IgnoreLos`, `AffixState`, `MaxVisible`, `ScriptName`) values('9981','9821','30','30','5','10','60','0','0','0','29','4194433','0','1','1','1.14286','1','79.8','106.4','0','194','1','2000','0','1','512','2048','0','0','3','0','0','0','55.1','79.8','12','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','SmartAI','0','3','1','1','1','1','0','2','0','','','0','0','0','0','0','0','0','');

SQL: gossip_menu_option
Note: Must add option to show hunters (stable option) -- The Code already handles condition to show option only to hunters - No need for entry into conditions table. The non huner options will be presented to any players using Battlepet spell.
=========================
insert into `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) values('9821','0','5','I\'d like to stable my pet here.','14','4194304','0','0','0','0','0','0','','16131','0','0');
insert into `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) values('9821','1','1','I want to browse your goods.','3','128','0','0','0','0','0','0','','56613','0','0');
insert into `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) values('9821','2','0','I\'d like to heal and revive my battle pets.','1','1','0','0','0','0','1000','0','A small fee for supplies is required.','64115','66369','0');


src/server/game/server/WorldSession.h
		- void SendStablePet(ObjectGuid const& guid = ObjectGuid::Empty);
		+ void SendStablePet(ObjectGuid guid);
		
		- void HanleSetPetSlot(WorldPackets::PetPackets::SetPetSlot& packet); -- Misspelled /hanle/
		+ void HandleSetPetSlot(WorldPackets::PetPackets::SetPetSlot& packet);

src/server/game/Handlers/PetHandler.cpp
		- void WorldSession::SendStablePet(ObjectGuid const& /*guid*/ /*= ObjectGuid::Empty*/)
		+ void WorldSession::SendStablePet(ObjectGuid guid)
				
		void WorldSession::SendStablePet(ObjectGuid guid)
		{
			...
			+ Creature* stableNPC = player->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_STABLEMASTER); //identify stablemaster guid to display stables;
			WorldPackets::PetPackets::StableList list;
			+ list.StableMaster = stableNPC->GetGUID(); //assign stable master guid to list
			...
		}
		
		void WorldSession::HandlePetAbandon(WorldPackets::PetPackets::PetAbandon& packet)
		{
			+ ObjectGuid guid = _player->GetGUID();
			...
			- _player->GetSession()->SendStablePet();
			+ _player->GetSession()->SendStablePet(guid);
			...
		}

		- void WorldSession::HanleRequestStabledPets(WorldPackets::NPC::RequestStabledPets& packet) - Misspelled /hanle/
		+ void WorldSession::HandleRequestStabledPets(WorldPackets::NPC::RequestStabledPets& packet)
		
		void WorldSession::HandleSetPetSlot(WorldPackets::PetPackets::SetPetSlot& packet)
		{
		...
		- PetSlot curentSlot = GetPlayer()->GetSlotForPetId(GetPlayer()->m_currentPetNumber); //Mispelling 
		-	if (pet && curentSlot == packet.NewSlot) //Mispelling
		
		+ PetSlot currentSlot = GetPlayer()->GetSlotForPetId(GetPlayer()->m_currentPetNumber); 
		+	if (pet && currentSlot == packet.NewSlot)
		...
		}


src/server/game/protocol/Opcodes.cpp
- DEFINE_HANDLER(CMSG_SET_PET_SLOT, STATUS_LOGGEDIN,  PROCESS_THREADUNSAFE, &WorldSession::HanleSetPetSlot); //Misspelled /hanle/
+ DEFINE_HANDLER(CMSG_SET_PET_SLOT, STATUS_LOGGEDIN,  PROCESS_THREADUNSAFE, &WorldSession::HandleSetPetSlot);


src/server/game/Entities/Player/Player.cpp
		void Player::OnGossipSelect(WorldObject* source, uint32 gossipListId, uint32 menuId)
		{
			GossipMenu& gossipMenu = PlayerTalkClass->GetGossipMenu();
		  +	ObjectGuid guid = source->GetGUID();
		 ... 
		  GossipMenuItem const* item = gossipMenu.GetItem(gossipListId);
		  if (!item)
		  return;
		  uint32 gossipHandlerType = item->OptionType;
		- ObjectGuid guid = source->GetGUID();
			...
		}
		  
		void Player::SendInitialPacketsAfterAddToMap(bool login)
		{
		  + ObjectGuid guid = ToPlayer()->GetGUID();
		  
		- GetSession()->SendStablePet();
		+ GetSession()->SendStablePet(guid);
		...
		}
		
		void Player::CreateDefaultPet()
		{
		 + ObjectGuid guid = ToPlayer()->GetGUID();
		 ...
		 - ToPlayer()->GetSession()->SendStablePet();
		 + ToPlayer()->GetSession()->SendStablePet(guid);
		 ...
		 }

src/server/game/Spells/SpellEffects.cpp
		void Spell::EffectCreateTamedPet(SpellEffIndex effIndex)
		{
		+ ObjectGuid guid = m_caster->GetGUID();
		...
		- player->GetSession()->SendStablePet();
		+ player->GetSession()->SendStablePet(guid);
		}
		
		void Spell::EffectTameCreature(SpellEffIndex /*effIndex*/)
		{
		+ ObjectGuid guid = m_caster->GetGUID();
		...
		- player->GetSession()->SendStablePet();
		+ player->GetSession()->SendStablePet(guid);
		}


src/server/game/Entities/Pet/Pet.cpp
	void Pet::SavePetToDB(bool isDelete)
	{
	...
	- PetSlot curentSlot = GetSlot();
	+ PetSlot currentSlot = GetSlot();
	 ...
	- if((curentSlot >= PET_SLOT_HUNTER_FIRST && curentSlot <= owner->GetMaxCurentPetSlot())) //Mispelled curentslot word
		owner->cleanPetSlotForMove(curentSlot, m_charmInfo->GetPetNumber());     //could be already remove by early call this function
	
	+ if((currentSlot >= PET_SLOT_HUNTER_FIRST && currentSlot <= owner->GetMaxCurentPetSlot()))
		owner->cleanPetSlotForMove(currentSlot, m_charmInfo->GetPetNumber());     //could be already remove by early call this function
	...
	}

**Comment by dufernst** [comment]
Regarding the first queries. I doubt those are needed as plenty of supposed stable masters already have the correct flag:
`SELECT * FROM creature_template AS ct WHERE ct.npcflag & 4194304 != 0 LIMIT 100;`

**Comment by Axdrell** [comment]
Update:

I found the bug in the code that prevented all the hunter pet slots from being used. The wrong data was being passed to the function getting called:

src/server/game/handlers/PetHandler.cpp

- _queryProcessor.AddQuery(CharacterDatabase.AsyncQuery(stmt).WithPreparedCallback(std::bind(&WorldSession::HandleStableChangeSlotCallback, this, std::placeholders::_1, packet.PetIndex)));  <-- packet.PetIndex is the wrong value being passed.
 + _queryProcessor.AddQuery(CharacterDatabase.AsyncQuery(stmt).WithPreparedCallback(std::bind(&WorldSession::HandleStableChangeSlotCallback, this, std::placeholders::_1, packet.NewSlot)));

**Comment by Axdrell** [comment]
Check your code. I do not experience dead pets when summoning.

**Comment by qqwqqwe** [comment]
Yes，hunters summoned pets is good

**Comment by qqwqqwe** [comment]
Stable masters pet slots well too.
