### ISSUE TITLE
HDD used 100% ，you've got this problem，how to deal with this

### ISSUE THREAD

**Issue by qqwqqwe** [dufernst/LegionCore-7.3.5#74]

**Comment by dufernst** [comment]
@qqwqqwe please reopen this issue with more information if you think there is some issue with this emulator.

**Comment by qqwqqwe** [comment]
Hard disk occupancy rate 100% whan enter the game and in game

**Comment by dufernst** [comment]
How much GB is the game on disk, and how much for the emulator + data files?

**Comment by qqwqqwe** [comment]
Hard disk activity time during a long time 100%

**Comment by qqwqqwe** [comment]
You can focus on this

**Comment by qqwqqwe** [comment]
This will increase  the time to enter the game

**Comment by dufernst** [comment]
Well maybe it is just loading assets?
I really need more information to help you further, is it the emulator that has high disk activity, or is it the game itself?
