### ISSUE TITLE
Battlepay Code Revisions

### ISSUE THREAD

**Issue by Axdrell** [dufernst/LegionCore-7.3.5#78]
Hi,

I want to share some of the revisions I made to the Battlepay functionality within my local copy of the code.

NOTE!!! - For this functionality to work, you need to be sure your local branch has the changes suggested by fluxurion on https://github.com/dufernst/LegionCore-7.3.5/pull/18/commits/cddb780e32556b15725fbc4a0d4da9e73801fc24 

In the web links below you find the enhanced battlepay_services.cpp script and sql data if you want to test it with your local instance. I believe the code can be optimized. Please let me know any revisions you make to make it better.

- https://drive.google.com/file/d/1SV_Sko3ky-YAUNkySbO2NYddxrutlC3j/view?usp=sharing
- https://drive.google.com/file/d/1FtkMpBen8ylrReht9jkjmwLNdSBrtDoy/view?usp=sharing

My battlepay functionality is shown in the screen below. All fully works including Character restore.

To fix Character Restore, ensure all the following statements in characterdatabase.cpp are changed to use CONNECTION_ASYNC.

Character Restore Fix
src/common/database/implementation/Characterdatabase.cpp

//Restore Character - Ensure the following statements use CONNECTION_ASYNC and Not CONNECTION_SYNCH
PrepareStatement(CHAR_SEL_LAST_CHAR_UNDELETE, "SELECT LastCharacterUndelete FROM characters WHERE account = ?", CONNECTION_ASYNC);
PrepareStatement(CHAR_UPD_LAST_CHAR_UNDELETE, "UPDATE characters SET LastCharacterUndelete = UNIX_TIMESTAMP() WHERE account = ?", CONNECTION_ASYNC);
PrepareStatement(CHAR_UPD_RESTORE_DELETE_INFO, "UPDATE characters SET name = ?, account = ?, deleteDate = NULL, deleteInfos_Name = NULL, deleteInfos_Account = NULL WHERE deleteDate IS NOT NULL AND guid = ?", CONNECTION_ASYNC);
PrepareStatement(CHAR_SEL_CHAR_DEL_INFO_BY_GUID, "SELECT guid, deleteInfos_Name, deleteInfos_Account, deleteDate FROM characters WHERE deleteDate IS NOT NULL AND guid = ?", CONNECTION_ASYNC);
PrepareStatement(CHAR_SEL_CHAR_DEL_INFO_BY_NAME, "SELECT guid, deleteInfos_Name, deleteInfos_Account, deleteDate FROM characters WHERE deleteDate IS NOT NULL AND deleteInfos_Name LIKE CONCAT('%%', ?, '%%')", CONNECTION_ASYNC);
PrepareStatement(CHAR_SEL_CHAR_DEL_INFO, "SELECT guid, deleteInfos_Name, deleteInfos_Account, deleteDate FROM characters WHERE deleteDate IS NOT NULL", CONNECTION_ASYNC);

I also added a play time reward script that rewards players with battlepay points for time played. Let me know if interested.

![Bpay1](https://user-images.githubusercontent.com/59615375/166809908-9931e392-7b1f-4dd8-b997-674fa657b599.jpg)

![Bpay2](https://user-images.githubusercontent.com/59615375/166810051-1087b861-b5ec-40b1-9e3a-cabfa1fe5fcc.jpg)

**Comment by Crandalius** [comment]
Awesome! Thanks for sharing this

**Comment by qqwqqwe** [comment]
Very nice, this is the most valuable sharing. your work is the most valuable.

**Comment by qqwqqwe** [comment]
Battlepay perfect job now.

**Comment by Thordekk** [comment]
Hi great job can u share play time reward script ? thanks

**Comment by fluxurion** [comment]
I have a playedtime reward script Thor Bro! xD

Also good idea the rewarding with battle coin i had this idea too when i played with this source!

**Comment by qyh214** [comment]
very cool and thanks for your sharing
