### ISSUE TITLE
Worldserver errors

### ISSUE THREAD

**Issue by Nexon99** [dufernst/LegionCore-7.3.5#8]
**See the errors :** https://zupimages.net/up/20/42/qlvm.png

I used hotfixes and world include in the source + test with the database of the legion repack (this source) + test with my old database _(my previous work)_ and it doesn't work... 

and i've this errors with **LegionCore_world_2020_04_25.sql** :

> /* Error SQL (1231) : Variable 'sql_mode' can't be set to the value of 'NULL' */ 
> /* Error SQL (1231) : Variable 'foreign_key_checks' can't be set to the value of 'NULL' */ 
> /* Error SQL (1231) : Variable 'unique_checks' can't be set to the value of 'NULL' */ 
> /* Error SQL (1231) : Variable 'sql_notes' can't be set to the value of 'NULL' */
> /* File "LegionCore_world_2020_04_25.sql" executed, with 806 queries and 1 219 532 affected rows */ 
> /* 1 file(s) processed, in 00:01:21.6 */
> 

I'm completely lost lmao, I've never had these errors before and my database was working well...

**Comment by Ramys** [comment]
They are different databases, it will not work.
i did it too.

**Comment by Nexon99** [comment]
Which hotfixes and world should I use?

**Comment by Ramys** [comment]
This .
https://github.com/dufernst/LegionCore-7.3.5/tree/master/sql/base

**Comment by Nexon99** [comment]
That's what I did, I wrote it lol. T-T

I tested 3 different databases... (and I have errors with LegionCore_world_2020_04_25.sql) 

> /* Error SQL (1231) : Variable 'sql_mode' can't be set to the value of 'NULL' /
> / Error SQL (1231) : Variable 'foreign_key_checks' can't be set to the value of 'NULL' /
> / Error SQL (1231) : Variable 'unique_checks' can't be set to the value of 'NULL' /
> / Error SQL (1231) : Variable 'sql_notes' can't be set to the value of 'NULL' /
> / File "LegionCore_world_2020_04_25.sql" executed, with 806 queries and 1 219 532 affected rows /
> / 1 file(s) processed, in 00:01:21.6 */

When I start Worldserver I have the same errors problem :/

**Comment by Nexon99** [comment]
No one has a solution?

**Comment by fluxurion** [comment]
Where did u get these update sql files? Btw remove these 4 variable what makes the error.

**Comment by Nexon99** [comment]
I use this : https://github.com/dufernst/LegionCore-7.3.5/tree/master/sql/base. It's include in the source :/ normally it's working

**Comment by Ramys** [comment]
This is fixed for linux, test!
https://github.com/nathalis/NCX-LegionLegacy

**Comment by Nexon99** [comment]
That's just the original source code without dufernst fix no ? 🤔 but I can try 

Just a question : using **this** source and the database provided with it, does it work for you or not ? normally it's working 😅

**Comment by Nexon99** [comment]
Should I try to compile this source ? or ? 🤔 Why "LegionCore-7.3.5" not working for me ? Working for you ?

Just a question : using **this** source and the database provided with it, does it work for you or not ? normally it's working 😅

**Comment by Nexon99** [comment]
not solved..

**Comment by dufernst** [comment]
I had not noticed this discussion here, feel free to get my attention with @dufernst next time. Then I get an e-mail when you post something.

Now regarding this issue, could you try importing the database from the commandline? That might fix it.
Either way the sql file in the zip is just a database dump from my version of the database, it might not play nice with the version of mysql (or the way it is configured) you are running. But that is not something I can look into from my end.

**Comment by dufernst** [comment]
You could try to remove the following lines from the top of the file:

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

**Comment by Nexon99** [comment]
@dufernst lol, I can't import the database anymore. I re-downloaded the SQL files but it doesn't change anything. wtf **(T-T)**

```
/* Connected. Process ID: 129 */
/* SQL error (2006): MySQL server has gone away */
/* Connection to 127.0.0.1 closed at 2020-10-18 11:15:33 */
/* Login to 127.0.0.1 for MySQL (TCP/IP), root username, password: Yes... */
SELECT CONNECTION_ID();
/* Character set: utf8mb4 */
SHOW /*!50002 GLOBAL */ STATUS;
SELECT NOW();
SHOW VARIABLES;
USE `world_legion`;
/* Connected. Process ID: 130 */
/* File "LegionCore_world_2020_04_25.sql" executed, with 796 queries and 1 219 532 affected rows */
/* 1 file(s) processed, in 00:02:29.7 */
```

I tried to import my "old" database which should work with this source (it's the same as this one normally "https://github.com/welder1976/LegionLegacy") and it worked _(the importation)_ but not working with worldserver.

I'm lost.

**Comment by dufernst** [comment]
@Nexon99 looks like your mysql thinks the query is taking too long, so it aborts.
The MySQL server that I run is configured to be more tolerant of long queries.

You could try to split the file up in multiple parts and execute those one after the other, that should work, but is a bit of manual work.

**Comment by Nexon99** [comment]
@dufernst I have a problem here. When I try to run only this part I get an error.
> insert  into `creature`(`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnMask`,`phaseMask`,  [...]

```
/* SQL error (2006) : MySQL server has gone away */
/* Connection to 127.0.0.1 close > 2020-10-19 00:52:25 */
/* Connection to 127.0.0.1 for MySQL (TCP/IP), username root, password : Yes…
```
Can you export your database and upload it? I would like to try and see if it works. Because it's strange...

**Comment by dufernst** [comment]
@Nexon99 The database in this repository is an export of mine.
As I mentioned before this most likely has to do with the configuration of your mysql server.

Look at for example: https://stackoverflow.com/questions/7942154/mysql-error-2006-mysql-server-has-gone-away
for a potential solution.

**Comment by Nexon99** [comment]
@dufernst // Okay, It works. I had already done it _(net_read_timeout, et_write_timeout, etc...)_, but I didn't think it would disappear after a reboot... mb (˘･_･˘)

However, I still have red errors in Worldserver, is this normal ? https://pastebin.com/UM8JKXdD

> ERROR `spell_proc` table entry for spellId 209493 doesn't have `spellPhaseMask` value defined, but it's required for defined `typeMask` value, proc will not be triggered

> ERROR SmartAIMgr: Entry 11555700 SourceType 9 Event 8 Action 1 uses min/max params wrong (8000/5000), skipped.

> ERROR Table `quest_start_scripts` has quest (ID: 14279) in SCRIPT_COMMAND_QUEST_EXPLORED in `datalong` for script id 14279, but quest not have flag QUEST_SPECIAL_FLAGS_EXPLORATION_OR_EVENT in quest flags. Script command or quest flags wrong. Quest modified to require objective.

**Comment by dufernst** [comment]
@Nexon99 Yeah those errors are "normal".
Definitely wouldn't mind if someone fixed them, but other than that I think you are set :)

**Comment by Nexon99** [comment]
Okay thank u ! And which launcher should I use ? Do I need a client patcher ? My launcher doesn't work (_downloaded from EpicWoW_) // @dufernst

**Comment by dufernst** [comment]
@Nexon99 This core works with a 26972 client, it is up to you to find one that works :)
And you can connect with your server using SET portal "something".

**Comment by Nexon99** [comment]
> 10/19 19:15:59.823  Connection Initialize
> 10/19 19:16:13.420  Glue Start Login
> 10/19 19:16:13.420  BattleNet Attempt Logon
> 10/19 19:16:15.487  BattleNet Front Disconnected
> 10/19 19:16:15.487  Glue Fatal Error: 1002
> 10/19 19:16:15.487  BattleNet Defer Disconnect
---

> 10/19 21:43:12.808  Connection Initialize
> 10/19 21:43:56.708  Glue Start Login
> 10/19 21:43:56.708  BattleNet Attempt Logon
> 10/19 21:43:56.968  BattleNet Front Connected
> 10/19 21:43:56.968  BattleNet External Challenge
> 10/19 21:43:56.968  BattleNet Get Logon Form
> 10/19 21:43:57.129  BattleNet Logon Form
> 10/19 21:43:57.312  BattleNet Logon Complete
> 10/19 21:43:57.312  BattleNet Game Account Name
> 10/19 21:43:57.312  BattleNet Attempt Complete Login
> 10/19 21:43:57.342  BattleNet Realm List Ticket
> 10/19 21:43:57.342  BattleNet Sub Region List
> 10/19 21:43:57.362  BattleNet Last Played Char
> 10/19 21:43:57.372  BattleNet Realm List
> 10/19 21:43:57.372  Glue Fatal Error: 2147483957
> 10/19 21:43:57.372  BattleNet Defer Disconnect
> 10/19 21:43:57.372  BattleNet Front Disconnecting
> 10/19 21:43:57.372  BattleNet Front Disconnected

Have you ever had or seen these errors ?                                                                                       
Sorry to bother you @dufernst, but normally I don't have any problems, but not here.  (っ °Д °;)っ

**Comment by dufernst** [comment]
@Nexon99 your realmlist is properly configured?

**Comment by Nexon99** [comment]
@dufernst | 

> SET portal "127.0.0.1"
> SET textLocale "frFR"
> SET audioLocale "frFR"
> SET installLocale "frFR"

**Comment by dufernst** [comment]
@Nexon99 I mean your realmlist table in your authentication database.

**Comment by Nexon99** [comment]
https://zupimages.net/up/20/43/dr4j.png

**Comment by Nexon99** [comment]
https://zupimages.net/up/20/43/dr4j.png | @dufernst

**Comment by dufernst** [comment]
@Nexon99 could you try setting the region to 1 instead of 2?
I could imagine that might help.

**Comment by Nexon99** [comment]
@dufernst | **No realm is currently available** (WOW51900309) 

> 10/19 23:33:55.832  Connection Initialize
> 10/19 23:34:09.757  Glue Start Login
> 10/19 23:34:09.757  BattleNet Attempt Logon
> 10/19 23:34:10.877  BattleNet Front Connected
> 10/19 23:34:10.970  BattleNet External Challenge
> 10/19 23:34:10.970  BattleNet Get Logon Form
> 10/19 23:34:11.665  BattleNet Logon Form
> 10/19 23:34:11.877  BattleNet Logon Complete
> 10/19 23:34:12.050  BattleNet Game Account Name
> 10/19 23:34:12.050  BattleNet Attempt Complete Login
> 10/19 23:34:12.063  BattleNet Realm List Ticket
> 10/19 23:34:12.076  BattleNet Sub Region List
> 10/19 23:34:12.090  BattleNet Last Played Char
> 10/19 23:34:12.117  BattleNet Realm List
> 10/19 23:34:12.117  Glue Fatal Error: 2147483957
> 10/19 23:34:12.117  BattleNet Defer Disconnect
> 10/19 23:34:12.117  BattleNet Front Disconnecting
> 10/19 23:34:12.130  BattleNet Front Disconnected

The problem is not that I didn't use a "connection_patcher"?

**Comment by dufernst** [comment]
Depends, if the binary was already patched then it should be fine without using the connection_patcher.
@Nexon99 can you verify that you have the correct game version? You need to have 26972 otherwise your client won't be able to find a matching realm to connect to in the realmlist.

**Comment by dufernst** [comment]
The fact that it is even connecting with your locally running authserver suggests that the client is properly patched.

**Comment by Nexon99** [comment]
@dufernst | Working, I tried with an other legion client \(@^0^@)/ Thank you for your help !

I hope that if one day you have the time, that you will work on this source or another project. You work well :)

**Comment by dufernst** [comment]
@Nexon99 I will definitely continue work on this source. I have been busy converting the characters from my current WoD source to this new database, that takes some time.
After that I will probably continue working on this source for the coming years.
