### ISSUE TITLE
Battlepay store outside game

### ISSUE THREAD

**Issue by Axdrell** [dufernst/LegionCore-7.3.5#80]
The shop button outside the game world does not work (characters screen). If you want to hide it outside the world, apply the code changes listed below.

The code below allows the use of the battlepay store in-world - with the option to disable it via worldconf.con. However, the battlepay button will not show on the character selection screen on login or logout.

Link to a file with the documented changes: https://drive.google.com/file/d/1uoKSQ9J8y_zyoDTVDMA9vZyD4zUkkhm0/view?usp=sharing

Battlepay Store button hidden outside world session.

src/server/game/handlers/Authhandler.cpp
void WorldSession::SendFeatureSystemStatusGlueScreen()
{
	+ Player* player = GetPlayer();
    WorldPackets::System::FeatureSystemStatusGlueScreen features;
    features.TokenPollTimeSeconds = 300;
    features.TokenRedeemIndex = 0; // ForSubAmount30Days
	- features.BpayStoreAvailable = sWorld->getBoolConfig(CONFIG_FEATURE_SYSTEM_BPAY_STORE_ENABLED);
    features.BpayStoreDisabledByParentalControls = false;
    features.CharUndeleteEnabled = HasAuthFlag(AT_AUTH_FLAG_RESTORE_DELETED_CHARACTER);
    - features.BpayStoreEnabled = sWorld->getBoolConfig(CONFIG_FEATURE_SYSTEM_BPAY_STORE_ENABLED);
	
	+ if (!player || !player->IsInWorld())
	+ {
	+	features.BpayStoreEnabled = false;
	+	features.BpayStoreAvailable = false;
	+ }
	+ else
	+ {
	+ 	features.BpayStoreEnabled = sWorld->getBoolConfig(CONFIG_FEATURE_SYSTEM_BPAY_STORE_ENABLED);
	+ 	features.BpayStoreAvailable = sWorld->getBoolConfig(CONFIG_FEATURE_SYSTEM_BPAY_STORE_ENABLED);
	+ }
	...
}

src/server/game/handlers/CharacterHandler.cpp
void WorldSession::HandlePlayerLogin(LoginQueryHolder* holder)
{
		...
	/// Send FeatureSystemStatus
    {
        WorldPackets::System::FeatureSystemStatus features;
        features.ComplaintStatus = 2;
		...
		- features.BpayStoreEnabled = GetBattlePayMgr()->IsAvailable();
        - features.BpayStoreAvailable = GetBattlePayMgr()->IsAvailable();
		
		+ //Disable Battlepay by default - Only available in world.
		+ features.BpayStoreEnabled = false;
        + features.BpayStoreAvailable = false;
		...
	    SendPacket(features.Write());
    }
	
    // Send MOTD
    {
        WorldPackets::System::MOTD motd;
        motd.Text = &sWorld->GetMotd();
        SendPacket(motd.Write());
		
		+ //Activate Battle Pay in-world - resend client packet after character logs in.
		+ WorldPackets::System::FeatureSystemStatus features;
		+ features.BpayStoreEnabled = sWorld->getBoolConfig(CONFIG_FEATURE_SYSTEM_BPAY_STORE_ENABLED);
		+ features.BpayStoreAvailable = sWorld->getBoolConfig(CONFIG_FEATURE_SYSTEM_BPAY_STORE_ENABLED);
		+ SendPacket(features.Write());
	}
	...
}

void WorldSession::HandleLogoutRequest(WorldPackets::Character::LogoutRequest& /*packet*/)
{
	...
	WorldPackets::Character::LogoutResponse logoutResponse;
    logoutResponse.LogoutResult = reason;
    logoutResponse.Instant = instantLogout;
    SendPacket(logoutResponse.Write());
	...
	+ //Deactivate Battle Pay outside-world (on logout) - resend client packet - This hides the BattlePay shop button on Character screen.
	+ WorldPackets::System::FeatureSystemStatus features;
	+ features.BpayStoreEnabled = false;
	+ features.BpayStoreAvailable = false;
	+ SendPacket(features.Write());
	...
}

**Comment by dufernst** [comment]
Maybe resending the packet with information about if bpay is enabled or not would work.

**Comment by qqwqqwe** [comment]
?

**Comment by qqwqqwe** [comment]
Its ok

**Comment by qqwqqwe** [comment]
Its Please later

**Comment by qqwqqwe** [comment]
You say its like 548 battle pay,

**Comment by Axdrell** [comment]
> Maybe resending the packet with information about if bpay is enabled or not would work.

Thanks for the tip. That was the fix. I will post my changes on my original post.

**Comment by qqwqqwe** [comment]
I test this and the battle pay disappeared (characters screen)

**Comment by Crandalius** [comment]
@Axdrell would it be possible for you to add your fixes in a pull request to this source?

**Comment by dufernst** [comment]
Note that making some changes to the BattlePay system is quite high on my todolist at the moment.
While that might still take a lot of time before I get to it, it might still mean that time is better spent on something else for @Axdrell.
