### ISSUE TITLE
A pet dies when entering or exiting a raid and dungeon

### ISSUE THREAD

**Issue by Elgrimm** [dufernst/LegionCore-7.3.5#82]
after leaving the raid, the pet is already dead and cannot be resurrected. helps only relog, games.

**Comment by Elgrimm** [comment]
Perhaps it is necessary in the file Pet.cpp make changes to LoadFromDB functions

**Comment by Elgrimm** [comment]
Yn awr yr wyf i'n ei wneud a phrofi. Os bydd yn gweithio, byddaf yn anfon yr ateb yma.

**Comment by Elgrimm** [comment]
My attempts have come to nothing. The point is that the pet is not even dead, but simply its health level reaches 0 and it disappears.

**Comment by Elgrimm** [comment]
I realized that no one here knows how to fix it at all.

**Comment by Elgrimm** [comment]
The question is, who knows when exiting a Raid or teleporting a player with a pet, which function is responsible for updating the pet's status?

**Comment by qqwqqwe** [comment]
It is ok no question

**Comment by qqwqqwe** [comment]
Up to date core

**Comment by Elgrimm** [comment]
> Up to date core

Everything is the same for me here, except that I added solocraft

**Comment by Elgrimm** [comment]
+ added an implementation contribution

**Comment by qqwqqwe** [comment]
I just test， and  it is good,   pet  was fixed  by Axdrell， you can see his issue

**Comment by Elgrimm** [comment]
> I just test， and it is good, pet was fixed by Axdrell， you can see his issue

Yes, I saw his correction and added it, but this correction concerns more StableMaster than the behavior of the pets themselves.

**Comment by Elgrimm** [comment]
> New hunter

Create a new character?

**Comment by anonymous33rus** [comment]
I have the same problem, after exiting the raid, the pet's health level is 0

**Comment by anonymous33rus** [comment]
My pet also disappears when leaving the dungeon

**Comment by qqwqqwe** [comment]
Human hunter pet White Tiger you can try.

**Comment by Elgrimm** [comment]
moment

**Comment by Elgrimm** [comment]
He has the same problem.

**Comment by Elgrimm** [comment]
![WoWScrnShot_051322_221607](https://user-images.githubusercontent.com/36525398/168315136-ae9b210a-b4cd-4b3f-b68a-b9f3b8d116d6.jpg)
Also, when you hover over the pet icon after it disappears and when you click on the right mouse button, no dialog box appears.

**Comment by Elgrimm** [comment]
The window is not active with the pet at all.

**Comment by qqwqqwe** [comment]
Where is coordinate， i test

**Comment by qqwqqwe** [comment]
it is ok
![ZCQ9K2)XPJD1B9S@(K)7 WU](https://user-images.githubusercontent.com/50628131/168318639-a5ba9821-576b-4256-89dc-9abf784776af.png)

**Comment by qqwqqwe** [comment]
No die

**Comment by Elgrimm** [comment]
exit dungeon

**Comment by Elgrimm** [comment]
When I enter, and then immediately exit through the portal, he dies for some reason, I still have a thought that this is happening because of the SoloLFG that I added.

**Comment by qqwqqwe** [comment]
![_{AF46K99WWZ~KB({4NMKFF](https://user-images.githubusercontent.com/50628131/168320093-2995bcbb-8cd8-414e-8b1e-4c0344494ce9.png)

**Comment by qqwqqwe** [comment]
No handle all pet

**Comment by qqwqqwe** [comment]
![%HJ2J~ 9UQYYQ5_%NZ5ORRH](https://user-images.githubusercontent.com/50628131/168320442-df4be159-90fd-4f7d-8a8d-a7d52d5b0e0f.png)

**Comment by Elgrimm** [comment]
moment

**Comment by Elgrimm** [comment]
I got it, so I did something wrong

**Comment by Elgrimm** [comment]
Thanks

**Comment by yudian1944** [comment]
> Thanks



> and void WorldSession::HandleRequestStabledPets(WorldPackets::NPC::RequestStabledPets& packet) is not in PetHandler.cpp , and in NPCHandler.cpp
how did you solve this problem friend?
