### ISSUE TITLE
Not a issue but rather a thank you

### ISSUE THREAD

**Issue by Dusteyy** [dufernst/LegionCore-7.3.5#83]
Hey Dufernst, 

Ik wil je graag bedanken voor deze top project ik zou graag contact met willen opnemen via discord/e-mail.
Als je daar wellicht open voor staat. Mijn excuses voor het gebruiken van de issues optie er was geen ander manier om je te bereiken.

x Dustey

DC: Dusteyy#1333

**Comment by Dusteyy** [comment]
@dufernst

**Comment by dufernst** [comment]
Solved :)
