### ISSUE TITLE
account creation website

### ISSUE THREAD

**Issue by k4s1pro** [dufernst/LegionCore-7.3.5#84]
hello, sorry for writing here but I don't know what kind of web page I need to create accounts, since the battlenet tables are changed, any help?

**Comment by Axdrell** [comment]
You can create the accounts using the worldserver console directly.

**Comment by k4s1pro** [comment]
Yes, I know from the console, but I have already tried the website that you say and the tables do not match due to the change that this code had to remove the battlenet tables, that is why I ask if there is any compatible website for this code, thanks
