### ISSUE TITLE
Disconnecting issue

### ISSUE THREAD

**Issue by Dusteyy** [dufernst/LegionCore-7.3.5#85]
So I’ve compiled ur source all works fine bnet and world are up chanted all realm settings but now I keep getting disconnecting when I enter my mail and pass in wow. It won’t let me in do I know a solution is it maybe because I am using a wow client from a existing private server ? Even tho I changed realmlist?
![84D06D5D-9123-4EE4-AE73-0311D282BFD1](https://user-images.githubusercontent.com/105640565/169558568-54558902-0240-4fc4-9eca-b5a12a25b3a8.jpeg)

**Comment by Axdrell** [comment]
go into your client game folder under WTF directory, there is a file called config.wtf. 

Make sure Set portal is set  to local host or the IP address you set within your auth.realmlist table.

setr line SET portal "127.0.0.1"

**Comment by Dusteyy** [comment]
Got that using a host for public

**Comment by Dusteyy** [comment]
![2E70299A-3080-42F4-B6D9-6A8FEB3A66A2](https://user-images.githubusercontent.com/105640565/169641952-55a439f6-6f50-4219-9855-9a7e214e26cc.png)
