### ISSUE TITLE
Quest problem

### ISSUE THREAD

**Issue by Nexon99** [dufernst/LegionCore-7.3.5#9]
@dufernst 

https://zupimages.net/up/20/43/rxly.jpg

https://zupimages.net/up/20/43/ra9j.jpg

https://zupimages.net/up/20/43/z6ib.jpg

**Comment by dufernst** [comment]
@Nexon99 I don't remember running into that issue when I was testing that questline.
Are you having this issue with more quests or are these your only examples?

If you link the quests (wowhead link) I can take a look if I get a different result on my testserver.

**Comment by Nexon99** [comment]
@dufernst |There are other quests that are just like this one. Normally, if the translation is not available in my language, it is displayed in English, but here I have nothing.

**Comment by dufernst** [comment]
@Nexon99 Ah, that could be, I only tested with enUS/enGB.
Unfortunately not something I can spend time on atm, but feel free to make a pull request with a fix :D

**Comment by Nexon99** [comment]
@dufernst | It's strange, aren't this core and the database the same as _"https://github.com/welder1976/LegionLegacy"_ ? 
I had no problem with this core and with the uWoW database.

I can use the **LegionLegacy** source and transfer your commits if it's don't work for me...  Because my old database doesn't work with your source but I don't have any problem with quests.

---
Where does the database for this source come from ? Are there any personal patches on it ?

**Comment by dufernst** [comment]
@Nexon99 There are hardly any differences between the database in this repo and the one from:
https://www.emucoach.com/forums/threads/new-repack-7-3-5-legion-wow-repack-wow-legion-7-3-5-repack-blizzlike-fun.6945/

You could make a diff of the source and database to find what has exactly changed.

**Comment by Nexon99** [comment]
@dufernst | I compared the tables of the 2 databases. I'm missing tables in my old one. I will try to export them and add them (battlepet_npc_team_member, ...) maybe it work  :D

**Comment by dufernst** [comment]
@Nexon99 I don't know how much of the data in the databases is different, if it is not a lot I don't mind patching it into this repository.

**Comment by Nexon99** [comment]
@dufernst | Fixed. I managed to adjust my old database with your database. I added the 2 missing tables. 

For my quest problem, my **__locales_** are more complete and contains additional translations (including French). Now it's good.

I've no more problems ! I will report the bugs now.

**Comment by dufernst** [comment]
Great, I will probably check in the coming days the database from:
https://github.com/welder1976/LegionLegacy
and see if I can merge anything useful from it into the database in this repository.
