### ISSUE TITLE
crash server priest holy artifact

### ISSUE THREAD

**Issue by k4s1pro** [dufernst/LegionCore-7.3.5#94]
When I use the dispel spell, the server crashes.

https://www.wowhead.com/quest=41966/house-call

I put the txt file, because in pasted bin it tells me that I have to be pro.
https://drive.google.com/file/d/1unh6ry-_H9-kG_LPyZkfAR9f3Lz-YWpQ/view?usp=sharing

**Comment by ImmortalusDev** [comment]
> When I use the dispel spell, the server crashes.
> 
> https://www.wowhead.com/quest=41966/house-call

Use pastebin and post crashlog

**Comment by yudian1944** [comment]
Also this happens to me if it is of help here I leave you the files generated by the crash, I compile in release.(https://drive.google.com/drive/folders/1ld2Y6FrAqlrPXnaFN9LGMUw1fOnAJJBe?usp=sharing)

**Comment by ImmortalusDev** [comment]
> Also this happens to me if it is of help here I leave you the files generated by the crash, I compile in release.(https://drive.google.com/drive/folders/1ld2Y6FrAqlrPXnaFN9LGMUw1fOnAJJBe?usp=sharing)

That will not help us. Compile RelDeb, not other releases.

**Comment by k4s1pro** [comment]
I put the txt file, because in pasted bin it tells me that I have to be pro.
https://drive.google.com/file/d/1unh6ry-_H9-kG_LPyZkfAR9f3Lz-YWpQ/view?usp=sharing

**Comment by ImmortalusDev** [comment]
> I put the txt file, because in pasted bin it tells me that I have to be pro. https://drive.google.com/file/d/1unh6ry-_H9-kG_LPyZkfAR9f3Lz-YWpQ/view?usp=sharing

Good log.

**Comment by dufernst** [comment]
@k4s1pro thanks for reporting.
I just checked your logs and this crash can only occur if the following npc is spawned manually:
https://www.wowhead.com/npc=105586/defender-barrem
The script assumes that there is some ingame player summoning the npc, if not that would break the script.

Can you confirm that that npc is only spawned if summoned by a player, or if the npc is spawned via the database?

**Comment by k4s1pro** [comment]
I have not spawned any npc is the one in the database, when dispel the magic of the server crashes.

**Comment by dufernst** [comment]
@k4s1pro is the one in the database? My database does not have that npc spawned?

**Comment by dufernst** [comment]
Still don't think it should occur on a clean code/with a clean database.
But a fix nonetheless:
https://github.com/dufernst/LegionCore-7.3.5/commit/82343e0205973e9668ad7cfa2f69dd17b508f02a
