### ISSUE TITLE
Oplote chest crash server [fix]

### ISSUE THREAD

**Issue by Fragrus** [dufernst/LegionCore-7.3.5#98]
https://github.com/dufernst/LegionCore-7.3.5/blob/619a46fb224cdb4528c92ca75c471e42bcfc1635/src/server/game/World/World.cpp#L1476

Change item ID from 138019 to 1533, this parameter is responsible for issuing the currency (https://www.wowhead.com/currency=1533), not the key.
And in this form, since 'Challenge.AddItemType' has a value of 1 - the server tries to issue the key item in the form of currency and this crashes the server. I spent about two hours in debager until I realized what was the matter. Change this)
This is used in issuing loot from the oplote chest.

**Comment by dufernst** [comment]
@Fragrus wouldn't it be better to change Challenge.AddItemType to 0?
I take it users should actually get a mythic keystone from this chest?

**Comment by Fragrus** [comment]
> @Fragrus wouldn't it be better to change Challenge.AddItemType to 0? I take it users should actually get a mythic keystone from this chest? In that case Challenge.AddItemCount should probably also be changed?

Yes, I definitely checked. The key is issued elsewhere

https://github.com/dufernst/LegionCore-7.3.5/blob/a3cef8ddf218a7403b535981d0b3f020fcd7c46b/src/server/game/Loot/LootMgr.cpp#L3120

**Comment by dufernst** [comment]
Makes sense, thanks for the fix.

**Comment by dufernst** [comment]
Merged
